### ISSUE TITLE
Deploying gMSA workloads to namespaces not specified by the upstream gMSA webhook results in `In Progress` stuck state

### ISSUE THREAD

**Issue by markusewalker** [rancher/dashboard#10004]
**Is your feature request related to a problem? Please describe.**

When deploying gMSA workloads in Rancher, they will only deploy in the namespace in which the Windows gMSA charts are deployed to. As of right now, the upstream gMSA webhook ignores pods created within the namespace it is deployed to.

The issue is when you attempt to deploy to a different namespace, say `default`. You are left with the following:

<img width="1236" alt="image" src="https://github.com/rancher/dashboard/assets/52591819/4269e07b-98aa-4166-8a2f-e2c738110c0e">

Whether the daemonset should successfully deploy or not, you are just left with the above limbo state. The workaround is to deploy to the namespace that the gMSA webhook expects, i.e. the namespace specified when installing the Windows gMSA charts.

See below steps to reproduce (prerequisite is that a Windows Active Directory server is setup and configured with Rancher):
1. As a standard user, provision a downstream RKE2 custom cluster (I had 3 etcd, 1 cp, 2 Linux workers, 4 Windows workers).
2. Navigate to cluster explorer > cluster > Apps > Repositories.
3. Add the https://github.com/rancher/Rancher-Plugin-gMSA and specify `main` as the branch.
4. Install the following charts:
     - Windows GMSA
     - Rancher gMSA CCG Plugin
     - Rancher gMSA Account Provider
5. Create a `GMSACredentialSpec` following the below template but with your information:
```
apiVersion: windows.k8s.io/v1
kind: GMSACredentialSpec
metadata:
  name: test-gmsa-spec
credspec:
  ActiveDirectoryConfig:
    HostAccountConfig: # This section is required for non-domain-joined nodes
      PluginGUID: '{e4781092-f116-4b79-b55e-28eb6a224e26}' # This field indicates that the Rancher CCG Plugin should be used
      PluginInput: 'rancher-domain-account-provider-namespace:rancher-domain-user-credentials' # <ACCOUNT_PROVIDER_NAMESPACE>:<ACCOUNT_CREDENTIAL_SECRET_NAME> 
      PortableCcgVersion: '1' # This must always be '1', until a new CCG version is released 
    GroupManagedServiceAccounts:
    - Name: GMSA1        # Username of the GMSA account
      Scope: RANCHER     # NETBIOS Domain Name
    - Name: GMSA1        # Username of the GMSA account
      Scope: rancher.ad.com # DNS Domain Name
  CmsPlugins:
  - ActiveDirectory
  DomainJoinConfig:
    DnsName: rancher.ad.com     # DNS Domain Name
    DnsTreeName: rancher.ad.com # DNS Domain Name Root
    Guid: 244818ae-87ac-4fcd-92ec-e79e5252348a  # GUID Of the Active Directory Domain
    MachineAccountName: GMSA1 # Username of the GMSA account
    NetBiosName: RANCHER      # NETBIOS Domain Name
    Sid: S-1-5-21-2126449477-2524075714-3094792973 # SID of the Active Directory Domain
```
6. Create a secret following this template with your specific information:
```
apiVersion: v1
kind: Secret
metadata:
  name: rancher-domain-user-credentials 
  namespace: rancher-domain-account-provider-namespace
type: Opaque
data:
  username: <base64 encoded username>
  password: <base64 encoded password>
  domainName: <base64 encoded domainName>
```
7. Attempt to deploy a daemonset into the `default` namespace; validate that you see the above screenshot.

**Describe the solution you'd like**

When introducing PSACT into Rancher, we had a similar [issue](https://github.com/rancher/dashboard/issues/8502) where we introduced a growl considering not much could be done from a UI perspective. If possible, we should explore the same solution here for gMSA workloads.

**Comment by aiyengar2** [comment]
Regarding reproduction steps, in step 7 are you deploying a DaemonSet attached to a ServiceAccount that has a RoleBinding referencing the service account + a role / clusterrole that allows the DaemonSet to use the GMSACredentialSpec? i.e.

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: use-test-gmsa-spec
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-test-gmsa-spec
  namespace: default
rules:
- apiGroups: ["windows.k8s.io"]
  resources: ["gmsacredentialspecs"]
  verbs: ["use"]
  resourceNames: ["test-gmsa-spec"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: use-test-gmsa-spec
  namespace: default
subjects:
- kind: ServiceAccount
  name: use-test-gmsa-spec
  namespace: default
roleRef:
  kind: Role
  name: use-test-gmsa-spec
  namespace: default
  apiGroup: rbac.authorization.k8s.io
```

That may be why you are seeing this error. If this is the case, you should also see that your workloads are failing because the Pods that are being created by it don't have `securityContext.windowsOptions.gmsaCredentialSpec`, only `securityContext.windowsOptions.gmsaCredentialSpecName`, since the webhook would have rejected it because it explicitly checks for this:

https://github.com/kubernetes-sigs/windows-gmsa/blob/37b14194707592359a08f7c78c118fb26c4470b1/admission-webhook/kube_client.go#L55-L91
