### ISSUE TITLE
Monitoring Helm chart sometimes `add selector:{}` and it's interpreted as an active Selector

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#10016]
Internal reference: SURE-7074
Reported in 2.7.6

Issue description:
Trying to upgrade the monitoring APP from the UI to add Data Persistence.

We were stuck on a pending PVC for prometheus.
Looking at the PVC we can see 

```
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector: {}
  storageClassName: si0dcs12-sds
  volumeMode: Filesystem
status:
  phase: Pending 
``` 

Impact:
rancher-monitoring chart installation completes, but the prometheus-rancher-monitoring-prometheus-db-prometheus-rancher-monitoring-prometheus-0 volume in the cattle-monitoring-system Namespace will fail to provision successfully and monitoring will not work until user manually intervenes to remove the empty selector from the prometheus volumeClaimTemplate in the values for the chart and recreate the PVC without the selector{}

Troubleshooting steps:

Looking at the csi-provisioner pod in longhorn, the following logs show:

```
2023-10-10T11:45:53.590796493Z I1010 11:45:53.590640       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"cattle-monitoring-system", Name:"prometheus-rancher-monitoring-prometheus-db-prometheus-rancher-monitoring-prometheus-0", UID:"b136a1e8-1d48-4e7a-b047-d9081a74f507", APIVersion:"v1", ResourceVersion:"479742099", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "si0dcs12-sds": claim Selector is not supported 
Looking at the PVC, the selector is set to {} which should not be cought as an active Selector.
```

It seems the empty Selector is added when in the UI, you add a rule then remove it, clicking on the "Remove" link next to the rule.

 ![image-2023-10-12-16-08-33-311.png](https://zube.io/files/rancher/c1e6d5e3697baa5c4854fd3c158a38c0-image-2023-10-12-16-08-33-311.png)

Repro steps:

- Create a 2.7.6 Rancher cluster.
- Create a downstream cluster.
- Add longhorn to the downstream cluster.
- Add the rancher-monitoring app in the downstream cluster.
- Select "Persistent Storage for Prometheus"
- Click on "Add Rule"
- Then remove the Rule
- Check on 'Edit yaml' and you'll see the following:
```
   storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          selector:
            matchExpressions: []
            matchLabels: {} 
```
- Applying this config will bring up the bug

Workaround:
Update the App removing 

```
 selector:
            matchExpressions: []
            matchLabels: {}  
```
from the storageSpec. Then recreate the PVC without the selector{}

Actual behavior:
The prometheus pod in not scheduled on longhorn.

Expected behavior:
The prometheus pod should run with the associated bound PVC.
