### ISSUE TITLE
Rancher UI error reading 'storageclass.kubernetes.io/is-default-class' if a storageclass doesn't have an annotations block

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10090]
Internal Reference: SURE-7199

When installing the Rancher Backups chart via the Rancher UI on the local cluster, you get an error when trying to select "Use an existing storage class" when you have a storage class without annotations.

Steps to reproduce - on the local cluster:

1. import the following YAML to create a new Storage Class, using the 'Import YAML' feature:

```
allowVolumeExpansion: false
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-annotations
parameters:
  encrypted: 'true'
  iopsPerGB: '0'
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
3. Go to Charts, Rancher Backups and click Install
4. Click Next to go to 'Edit Options'
5. Click on 'Use an existing storage class' under 'Default Storage Location'

Browser console logs shows an error:

```
TypeError: Cannot read properties of undefined (reading 'storageclass.kubernetes.io/is-default-class')
    at index.vue:68:1
    at Array.filter (<anonymous>)
    at a.defaultStorageClass (index.vue:68:1)
...
```
