### ISSUE TITLE
Upload artifacts as output of check-plugins check for debugging

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#10116]
# Description

As step to ease the debugging process (https://github.com/rancher/dashboard/issues/10112), upload generated files on fail.

E.g.:

```yaml
    - name: Upload files
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test
        path: |
          /tmp/tmp.**/test-app
          !/tmp/tmp.**/test-app/node_modules/
          /tmp/tmp.**/pkg/test-pkg/
          !/tmp/tmp.**/pkg/test-pkg/node_modules/
        
```
