### ISSUE TITLE
Multiple Nodepools availability zones not getting honored while creation

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#10125]
Rancher version:
```
2.8.0-rc1
aks-operator:v1.2.0-rc4
```
**Describe the bug**
Multiple Nodepools availability zones not getting honored while creation. The zones selected on UI and API payload are not matching, so AZs for nodepools are incorrect after creation.

**Steps**
Provision AKS cluster with multiple nodepools and different AZs
eg.
System pool - AZ: 1,2,3
User pool1 - AZ: 1
User pool2 - AZ: 2
User pool3 - AZ: 3

**Screenshots**
![image](https://github.com/rancher/aks-operator/assets/73099870/34a69e0a-620c-49a1-8491-fbdb6507da2e)

![image](https://github.com/rancher/aks-operator/assets/73099870/a81e7c54-9bd0-4c83-a71b-e0bbcc8e8592)

![image](https://github.com/rancher/aks-operator/assets/73099870/2c88d2df-733f-413a-b4bd-8d4b8facacf1)

**Payload**
```
{
  "dockerRootDir": "/var/lib/docker",
  "enableClusterAlerting": false,
  "enableClusterMonitoring": false,
  "enableNetworkPolicy": false,
  "windowsPreferedCluster": false,
  "type": "cluster",
  "name": "cpinjani-aks3",
  "aksConfig": {
    "imported": false,
    "azureCredentialSecret": "cattle-global-data:cc-jj9k8",
    "clusterName": "cpinjani-aks3",
    "dnsPrefix": "cpinjani-aks3",
    "kubernetesVersion": "1.27.1",
    "linuxAdminUsername": "azureuser",
    "loadBalancerSku": "Standard",
    "networkPlugin": "kubenet",
    "networkPolicy": "calico",
    "nodePools": [
      {
        "availabilityZones": [
          "1",
          "2",
          "3"
        ],
        "count": 1,
        "enableAutoScaling": false,
        "maxPods": 110,
        "maxSurge": "1",
        "mode": "System",
        "name": "agentpool",
        "nodeLabels": {
          
        },
        "nodeTaints": [
          
        ],
        "orchestratorVersion": "1.27.1",
        "osDiskSizeGB": 128,
        "osDiskType": "Managed",
        "osType": "Linux",
        "type": "aksnodepool",
        "vmSize": "Standard_DS2_v2",
        "isNew": true
      },
      {
        "availabilityZones": [
          "1"
        ],
        "count": 1,
        "enableAutoScaling": false,
        "maxPods": 110,
        "maxSurge": "1",
        "mode": "User",
        "name": "pool1",
        "nodeLabels": {
          
        },
        "nodeTaints": [
          
        ],
        "orchestratorVersion": "1.27.1",
        "osDiskSizeGB": 128,
        "osDiskType": "Managed",
        "osType": "Linux",
        "type": "aksnodepool",
        "vmSize": "Standard_DS2_v2",
        "isNew": true
      },
      {
        "availabilityZones": [
          "3"
        ],
        "count": 1,
        "enableAutoScaling": false,
        "maxPods": 110,
        "maxSurge": "1",
        "mode": "User",
        "name": "pool2",
        "nodeLabels": {
          
        },
        "nodeTaints": [
          
        ],
        "orchestratorVersion": "1.27.1",
        "osDiskSizeGB": 128,
        "osDiskType": "Managed",
        "osType": "Linux",
        "type": "aksnodepool",
        "vmSize": "Standard_DS2_v2",
        "isNew": true
      },
      {
        "availabilityZones": [
          "2"
        ],
        "count": 1,
        "enableAutoScaling": false,
        "maxPods": 110,
        "maxSurge": "1",
        "mode": "User",
        "name": "pool3",
        "nodeLabels": {
          
        },
        "nodeTaints": [
          
        ],
        "orchestratorVersion": "1.27.1",
        "osDiskSizeGB": 128,
        "osDiskType": "Managed",
        "osType": "Linux",
        "type": "aksnodepool",
        "vmSize": "Standard_DS2_v2",
        "isNew": true
      }
    ],
    "privateCluster": false,
    "resourceGroup": "cpinjani-aks3",
    "resourceLocation": "eastus",
    "tags": {
      
    },
    "type": "aksclusterconfigspec",
    "nodeResourceGroup": "<REDACTED>"
  },
  "labels": {
    
  }
}
```

**Comment by mantis-toboggan-md** [comment]
This will be covered by the port of AKS provisioning from Ember to Vue: https://github.com/rancher/dashboard/pull/9669

**Comment by cpinjani** [comment]
Validated as fixed on build: `v2.9-98d8b8975948ce5929e38e8603950ceb223349de-head` - :white_check_mark: 
Provisioned AKS cluster with multiple nodepools and different AZs
System pool - AZ: 1,2,3
User pool1 - AZ: 1
User pool2 - AZ: 2
User pool3 - AZ: 3

Payload sent while creation:
```
    "nodePools": [
      {
        "availabilityZones": [
          "1",
          "2",
          "3"
        ],
        "count": 1,
        "enableAutoScaling": false,
        "maxPods": 110,
        "maxSurge": "1",
        "mode": "System",
        "name": "agentpool",
        "nodeLabels": {
          
        },
        "nodeTaints": [
          
        ],
        "orchestratorVersion": "",
        "osDiskSizeGB": 128,
        "osDiskType": "Managed",
        "osType": "Linux",
        "vmSize": "Standard_DS2_v2"
      },
      {
        "availabilityZones": [
          "1"
        ],
        "count": 1,
        "enableAutoScaling": false,
        "maxPods": 110,
        "maxSurge": "1",
        "mode": "User",
        "name": "pool1",
        "nodeLabels": {
          
        },
        "nodeTaints": [
          
        ],
        "orchestratorVersion": "",
        "osDiskSizeGB": 128,
        "osDiskType": "Managed",
        "osType": "Linux",
        "vmSize": "Standard_DS2_v2"
      },
      {
        "availabilityZones": [
          "2"
        ],
        "count": 1,
        "enableAutoScaling": false,
        "maxPods": 110,
        "maxSurge": "1",
        "mode": "User",
        "name": "pool2",
        "nodeLabels": {
          
        },
        "nodeTaints": [
          
        ],
        "orchestratorVersion": "",
        "osDiskSizeGB": 128,
        "osDiskType": "Managed",
        "osType": "Linux",
        "vmSize": "Standard_DS2_v2"
      },
      {
        "availabilityZones": [
          "3"
        ],
        "count": 1,
        "enableAutoScaling": false,
        "maxPods": 110,
        "maxSurge": "1",
        "mode": "User",
        "name": "pool3",
        "nodeLabels": {
          
        },
        "nodeTaints": [
          
        ],
        "orchestratorVersion": "",
        "osDiskSizeGB": 128,
        "osDiskType": "Managed",
        "osType": "Linux",
        "vmSize": "Standard_DS2_v2"
      }
    ]
```

**Spec:**
```
    nodePools:
      - availabilityZones:
          - '3'
        count: 1
        enableAutoScaling: false
        maxPods: 110
        maxSurge: '1'
        mode: User
        name: pool3
        orchestratorVersion: 1.28.3
        osDiskSizeGB: 128
        osDiskType: Managed
        osType: Linux
        vmSize: Standard_DS2_v2
      - availabilityZones:
          - '1'
          - '2'
          - '3'
        count: 1
        enableAutoScaling: false
        maxPods: 110
        maxSurge: '1'
        mode: System
        name: agentpool
        orchestratorVersion: 1.28.3
        osDiskSizeGB: 128
        osDiskType: Managed
        osType: Linux
        vmSize: Standard_DS2_v2
      - availabilityZones:
          - '1'
        count: 1
        maxPods: 110
        maxSurge: '1'
        mode: User
        name: pool1
        orchestratorVersion: 1.28.3
        osDiskSizeGB: 128
        osDiskType: Managed
        osType: Linux
        vmSize: Standard_DS2_v2
      - availabilityZones:
          - '2'
        count: 1
        enableAutoScaling: false
        maxPods: 110
        maxSurge: '1'
        mode: User
        name: pool2
        orchestratorVersion: 1.28.3
        osDiskSizeGB: 128
        osDiskType: Managed
        osType: Linux
        vmSize: Standard_DS2_v2
```
