### ISSUE TITLE
Apps - Upgrade using Values YAML option should use specific values to upgrade original install but all the options are currently needed

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1016]
Rancher version `master-head (08/12/2020)` _d19f179c4_ HA k8s

- Go to the Dashboard in the `local` cluster
- Apps -> Charts -> `rancher-gatekeeper` Install.
- After installation succeeds got o Apps -> Installed Apps
- `rancher-gatekeeper` click the three dots menu and `Upgrade`
- Values YAML

Try using :

```yaml
auditInterval: 20
```

The upgrade fails checking the logs.

```
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Deployment.spec.template.metadata.annotations.container): invalid type for io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.annotations: got "map", expected "string", ValidationError(Deployment.spec.template.spec.nodeSelector.kubernetes): invalid type for io.k8s.api.core.v1.PodSpec.nodeSelector: got "map", expected "string"]
```

Go to Apps ->`Installed Apps` -> `rancher-gatekeeper` click the three dots menu and `Upgrade`

Use the original installation values and edit the values you want to edit and Upgrade.

```yaml
affinity: {}
auditChunkSize: 0
auditFromCache: false
auditInterval: 20
constraintViolationsLimit: 20
disableValidatingWebhook: false
emitAdmissionEvents: false
emitAuditEvents: false
global:
  kubectl:
    repository: rancher/istio-kubectl
    tag: 1.5.8
  systemDefaultRegistry: ''
image:
  pullPolicy: IfNotPresent
  repository: rancher/opa-gatekeeper
  tag: v3.1.0-beta.11
logLevel: INFO
nodeSelector:
  kubernetes.io/os: linux
podAnnotations:
  container.seccomp.security.alpha.kubernetes.io/manager: runtime/default
replicas: 3
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
tolerations: []
```

This works but **the Expectation** is to be able to use specific yaml values not the entire installation values yaml.
