### ISSUE TITLE
Creating a ClusterRepo through the Rancher UI, both `url` and `gitRepo` fields persist in the generated YAML

### ISSUE THREAD

**Issue by skanakal** [rancher/dashboard#10216]
**Setup**
- Rancher version: 2.7.9
- Rancher UI Extensions:
- Browser type & version: Chrome

**Describe the bug**

When creating a ClusterRepo through the Rancher UI, both `url` and `gitRepo` fields persist in the generated YAML.

**To Reproduce**

Create a cluster repo, in targets add both Helm and Git urls... 

**Result**

https://github.com/rancher/dashboard/assets/124564266/e658b60f-eeaa-4a00-a936-3bd6d321dfcf

```
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
spec:
  clientSecret: null
  gitBranch: main
  gitRepo: https://github.com/bitnami/charts.git
  url: https://rancher.charts.io
```

**Expected Result**

```
spec:
  clientSecret: null
  gitBranch: ''
  gitRepo: ''
  url: https://charts.rancher.io
```
https://github.com/rancher/dashboard/assets/124564266/563c41df-b0ea-4d95-8e45-79abf282ad33

**Screenshots**

**Additional context**
