### ISSUE TITLE
User-Base default role doesn't grant project owners ability to see members

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10215]
Internal Reference: SURE-6262

A user created with User-Base only role, when added as a project owner, doesn't have access to view members when editing a project they are owner of.

Repro steps:

- Create two users, at least one with User-Base as the only role
- Create a project, add user with User-Base as only role as project owner
- Log in as user and attempt to edit the project, members list is not available

Workaround:

Users copied the Standard-User role and removed the cluster creation and other roles that they didn't want to give to users and this seemed to give enough access to the user to view members

Actual behavior:
User-Base role limited users cannot manage members in projects they are owner of.

Expected behaviour:
All level of users can manage projects they are project owners of.

**Comment by gaktive** [comment]
Theory: users can see bindings but not roles, which may be confusing.

Input from @MbolotSuse:
> I was able to reproduce this issue on 2.7.5, though this does appear to be a UI issue (I was able to see the bindings in both the v3 and v1 apis). [...] This is a possible side-effect of the use of the base-user role. That role has very limited permissions, and you may need to add additional permissions on top of it for use cases like this one. [...] Adding permissions to view role templates (see the below rule) allowed me to view the bindings in at least a minimal way:

```
apiVersion: management.cattle.io/v3
displayName: view-bindings
kind: GlobalRole
metadata:
  name: gr-s64ct
rules:
  - apiGroups:
      - management.cattle.io
    resources:
      - roletemplates
    verbs:
      - get
      - list
      - watch
```

@richard-cox working on something similar. We should look at a warning in the UI to show that a bit is missing and a permission is required to view things. Wording would have to come from backend.
