### ISSUE TITLE
Display a single PR check for E2E

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#10288]
# Description

Group up E2E matrix check into a single result, avoiding cluttering displayed informations and simplifying requirements for the PR in the repo settings (@richard-cox ).

Suggested code:

```yaml
  # Display results as a single check in the PR
  e2e-results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: E2E tests
    needs: [e2e-test]
    steps:
      - run: exit 1
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
```

Existing Github discussion: https://github.com/orgs/community/discussions/26822
Current displayed results:

![Screenshot 2024-01-17 at 18 09 36](https://github.com/rancher/dashboard/assets/5009481/7fbb33a5-2386-46de-9307-962ee3049f39)
