### ISSUE TITLE
[BUG][UI] Cant save cluster with edit as yaml, corrupts encryption.yaml (worse in 2.7.0)

### ISSUE THREAD

**Issue by BobVanB** [rancher/dashboard#10330]
**Rancher Server Setup**
- Rancher version: 2.7.0
- Installation option Docker:
- Proxy/Cert Details: -

**Information about the Cluster**
- Kubernetes version: Does not matter
- Cluster Type (Local/Downstream): RKE

**User Information**
- What is the role of the user logged in? Does not matter

**Describe the bug**
This bug is still present: https://github.com/rancher/rancher/issues/36197

**To Reproduce**

1. `docker run -d --rm -p 443:443 --privileged --name rancher "rancher/rancher:v2.7.0"`
2. open https://localhost

These steps are all in the ui:

3. bootstrap the cluster as told in the ui
4. generate a random password
5. create a new cluster with `RKE`
6. use a random name for the cluster
7. merge the encryption config from https://rancher.com/docs/rke/latest/en/config-options/secrets-encryption/
8. selecteer all rollen
9. click op done
10. edit the cluster as yaml
12. click on save
13. edit the cluster as yaml

**Result**

The config at step 10:

```yaml
resources:
  - providers:
      - aescbc:
          keys:
            - name: k-fw5hn
              secret: RTczRjFDODMwQzAyMDVBREU4NDJBMUZFNDhCNzM5N0I=
        aesgcm: {}
        identity: {}
        kms: {}
        secretbox: {}
      - aescbc: {}
        aesgcm: {}
        identity: {}
        kms: {}
        secretbox: {}
```

The config at step 13:

```yaml
resources:
  - providers:
      - aescbc:
          keys:
            - name: k-fw5hn
              secret: RTczRjFDODMwQzAyMDVBREU4NDJBMUZFNDhCNzM5N0I=
        aesgcm:
          keys: null
        identity: {}
        kms:
          endpoint: ''
          name: ''
          timeout: {}
        secretbox:
          keys: null
      - aescbc:
          keys: null
        aesgcm:
          keys: null
        identity: {}
        kms:
          endpoint: ''
          name: ''
          timeout: {}
        secretbox:
          keys: null
```

**Expected Result**

The configuration should be the same as on stap 7 and thus the configuration on this page:
https://rancher.com/docs/rke/latest/en/config-options/secrets-encryption/

**Screenshots**

No Screenshots.

**Additional context**

It worse than version 2.6 and lower, but ever still present.
https://github.com/rancher/rancher/issues/36197
