### ISSUE TITLE
[BUG] UI - additionalPrinterColumns values empty when fields have periods or slashes in them

### ISSUE THREAD

**Issue by ekristen** [rancher/dashboard#10777]
**Rancher Server Setup**
- Rancher version: 2.7.9
- Installation option (Docker install/Helm Chart): RKE2

**Information about the Cluster**
- Kubernetes version: 1.26.9
- Cluster Type (Local/Downstream): Local

**Describe the bug**
The UI will not render the values of labels and annotations from the metadata block when periods or slashes are involved leaving to missing fields in the rancher UI especially when it comes to CRDs.

**To Reproduce**
Install any CRD that has additionalPrinterColumns that reference .metadata.labels or annotations with an annotation for example that has a period or slash in it.

```
  - additionalPrinterColumns:
    - jsonPath: .metadata.labels.node\.kubernetes\.io/instance-type
      name: Type
      type: string
    - jsonPath: .metadata.labels.topology\.kubernetes\.io/zone
      name: Zone
      type: string
    - jsonPath: .status.nodeName
      name: Node
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .metadata.labels.karpenter\.sh/capacity-type
      name: Capacity
      priority: 1
      type: string
    - jsonPath: .metadata.labels.karpenter\.sh/provisioner-name
      name: Provisioner
      priority: 1
      type: string
    - jsonPath: .spec.machineTemplateRef.name
      name: Template
      priority: 1
      type: string
```

**Result**

Empty fields in the UI.

**Expected Result**

The fields to be populated with the correct values.

**Screenshots**
![Screenshot 2024-04-05 at 8 52 27 AM](https://github.com/rancher/rancher/assets/48329/6bbfcfea-2590-4995-8534-63504b935519)

**Additional context**

My guess it has to do with the escaping of the special characters that's breaking the UI from rendering them properly.
