### ISSUE TITLE
[BUG] Deployment yaml gets mangled at hostAlias after form edition

### ISSUE THREAD

**Issue by baptisterajaut** [rancher/dashboard#10942]
Hey, i noticed i had this annoying bug.

**Rancher Server Setup**
- Rancher version: 2.8.3
- Installation option : Docker Install

**User Information**
- What is the role of the user logged in? : Admin

**Describe the bug**
When creating a host alias, everything is well.
Example , here's the yaml of a service which works : 
```yaml
     hostAliases:
        - hostnames:
            - mysql
          ip: 192.168.10.10
      restartPolicy: Always
```

However when i went and edited it with the form, i can't apply it because 
`Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal string into Go struct field HostAlias.spec.template.spec.hostAliases.hostnames of type []string`

And as it stands, indeed the hostAliases spec is flipped: 

```yaml
      hostAliases:
        - ip: 192.168.10.10
          hostnames: mysql
#        - hostnames:
#            - string
#          ip: string
      hostNetwork: false
      hostname: my-db-hostname
      restartPolicy: Always
```

**Result**

Have to re-set the yaml by hand

**Expected Result**
It shouldn't be necessary

**Screenshots**

**Additional context**
I added the network hostname. I did not add the hostNetwork property.
