### ISSUE TITLE
[v2.9] AKS: Unable to edit imported cluster

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#10966]
**Setup**
Rancher version: `v2.9-6d87a11ea46b7571646d7c3d7af704584c39fd62-head`
Browser type & version: Chrome latest

**Describe the bug**
AKS (Vue UI): Unable to manage and edit imported cluster. Most of fields on UI are grayed out and Save button is not enabled. 

**To Reproduce**
- Create AKS cluster and import it from Rancher UI
- Once cluster becomes Active, edit cluster and check the fields

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/73099870/e6b0f9c8-8661-4f61-819f-a2328b30387c)

**Additional Info**
Cluster spec after importing:
```
spec:
  agentImageOverride: ''
  aksConfig:
    authBaseUrl: null
    authorizedIpRanges: null
    azureCredentialSecret: cattle-global-data:cc-897k6
    baseUrl: null
    clusterName: cpinjani-aks1
    dnsServiceIp: null
    dockerBridgeCidr: null
    httpApplicationRouting: null
    imported: true
    kubernetesVersion: null
    loadBalancerSku: null
    logAnalyticsWorkspaceGroup: null
    logAnalyticsWorkspaceName: null
    managedIdentity: null
    monitoring: null
    networkPlugin: null
    networkPolicy: null
    nodePools: null
    outboundType: null
    podCidr: null
    privateCluster: null
    privateDnsZone: null
    resourceGroup: cpinjani-aks
    resourceLocation: eastus
    serviceCidr: null
    subnet: null
    tags: null
    userAssignedIdentity: null
    virtualNetwork: null
    virtualNetworkResourceGroup: null
  answers: {}
  clusterSecrets: {}
  description: ''
  desiredAgentImage: ''
  desiredAuthImage: ''
  displayName: cpinjani-aks1
  dockerRootDir: /var/lib/docker
  enableNetworkPolicy: false
  fleetWorkspaceName: fleet-default
  internal: false
  localClusterAuthEndpoint:
    enabled: false
  windowsPreferedCluster: false
```
