### ISSUE TITLE
Constraint create from YAML stuck saving

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#1100]
Go to the Dashboard in the local cluster
Apps -> Charts -> rancher-gatekeeper Install.
Under OPA Gatekeeper -> Constraints -> Create from YAML
Enter name and YAML.
Ex:
```
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: ns-must-have-gk
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    labels: ["gatekeeper"]
```

Result:
Creation is stuck saving
![Screen Shot 2020-08-25 at 2 32 14 PM](https://user-images.githubusercontent.com/57409052/91230159-dee70900-e6df-11ea-9a98-bd448084c8bf.png)
Rancher server `rancher\rancher:master-head` `version 9b6984d5f` `master-9b6984d5fa33c65ebcc3dee04bb918300451cf37-head`
