### ISSUE TITLE
[Bug] Cannot create RKE2 cluster from yaml view

### ISSUE THREAD

**Issue by jordojordo** [rancher/dashboard#11020]
**Setup**
- Rancher version: `v2.9-head`  (`2b53406`) 
- Rancher UI Extensions: N/A
- Browser type & version: FF 125.0.3

**Describe the bug**

When attempting to provision an RKE2 cluster from the YAML view, the formatting of the generated yaml is incorrect, causing the creation to fail.

**To Reproduce**

- Install Rancher `v2.9-head` 
- Create RKE2 cluster
- Select "Edit as YAML"
- Attempt to create the cluster

**Result**
An error banner shows:

<details open>

```console
bad indentation of a mapping entry (13:56)

10 | ...
11 | ... t
12 | ...
13 | ... ustomization: overrideAffinity: {}
-----------------------------------------^
14 | ...
15 | ... ments: {}
```

</details>

**Screenshots**

![rke2-yaml](https://github.com/rancher/dashboard/assets/40806497/83d6ee5b-b4e8-4a87-b952-8d93473a588e)

**Additional context**

It appears that the schema returned is broken, there are a few instances with incorrect spacing and two duplicate entries.

- Incorrect spacing:
  - `clusterAgentDeploymentCustomization: overrideAffinity: {}`
  - `fleetAgentDeploymentCustomization: overrideAffinity: {}`
  - `rkeConfig: chartValues:`
- duplicate entries:
  - `appendTolerations: []`
  - `overrideResourceRequirements: {}`

<details open><summary>Yaml returned for rke2 config</summary>

```yaml
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
    #  key: string
  labels:
    {}
    #  key: string
  namespace: fleet-default
spec:
  clusterAgentDeploymentCustomization: overrideAffinity: {}
  appendTolerations: []
  overrideResourceRequirements: {}
  defaultPodSecurityAdmissionConfigurationTemplateName: ''
  fleetAgentDeploymentCustomization: overrideAffinity: {}
  appendTolerations: []
  overrideResourceRequirements: {}
  kubernetesVersion: v1.28.9+rke2r1
  localClusterAuthEndpoint:
    caCerts: ''
    enabled: false
    fqdn: ''
  rkeConfig: chartValues:
    rke2-calico: {}
  upgradeStrategy:
    controlPlaneConcurrency: '1'
    controlPlaneDrainOptions:
      deleteEmptyDirData: true
      disableEviction: false
      enabled: false
      force: false
      gracePeriod: -1
      ignoreDaemonSets: true
      skipWaitForDeleteTimeoutSeconds: 0
      timeout: 120
    workerConcurrency: '1'
    workerDrainOptions:
      deleteEmptyDirData: true
      disableEviction: false
      enabled: false
      force: false
      gracePeriod: -1
      ignoreDaemonSets: true
      skipWaitForDeleteTimeoutSeconds: 0
      timeout: 120
  machineGlobalConfig:
    cni: calico
    disable-kube-proxy: false
    etcd-expose-metrics: false
    profile: null
  machineSelectorConfig:
    - config:
        protect-kernel-defaults: false
  etcd:
    disableSnapshots: false
    s3: null
    snapshotRetention: 5
    snapshotScheduleCron: 0 */5 * * *
  registries:
    configs: {}
    mirrors: {}
  machinePools: []
  machineSelectorConfig:
    - config: {}
#  agentEnvVars: string
#  cloudCredentialSecretName: string
#  clusterAPIConfig: string
#  defaultClusterRoleForProjectMembers: string
#  defaultPodSecurityPolicyTemplateName: string
#  enableNetworkPolicy: string
#  redeploySystemAgentGeneration: int
__clone: true
```

</details>
