### ISSUE TITLE
[v2.9] EKS: Unable to edit imported cluster

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#11100]
**Setup**
Rancher version: `v2.9-3c48a195381ad55f9fef7e9bf32b1593d43368ca-head`
Browser type & version: Chrome latest

**Describe the bug**
AKS (Vue UI): Unable to manage and edit imported cluster. Error on UI: At least one of public or private access must be enabled.

**To Reproduce**
- Create EKS cluster and import it from Rancher UI
- Once cluster becomes Active, edit cluster and check the fields

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/73099870/a0ba7c4d-c7ae-4cb7-9254-28434b24eb07)

**Additional Info**
Cluster spec after importing:
```
spec:
  agentImageOverride: ''
  answers: {}
  clusterSecrets: {}
  description: ''
  desiredAgentImage: ''
  desiredAuthImage: ''
  displayName: cpinjani-imp
  dockerRootDir: /var/lib/docker
  eksConfig:
    amazonCredentialSecret: cattle-global-data:cc-4v4rm
    displayName: cpinjani-imp
    ebsCSIDriver: null
    imported: true
    kmsKey: null
    kubernetesVersion: null
    loggingTypes: null
    nodeGroups: null
    privateAccess: null
    publicAccess: null
    publicAccessSources: null
    region: ca-central-1
    secretsEncryption: null
    securityGroups: null
    serviceRole: null
    subnets: null
    tags: null
  enableNetworkPolicy: false
  fleetWorkspaceName: fleet-default
  internal: false
  localClusterAuthEndpoint:
    enabled: false
  windowsPreferedCluster: false
```
