### ISSUE TITLE
[v2.9] EKS: Cluster details not displayed

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#11104]
**Setup**
Rancher version: `v2.9-3c48a195381ad55f9fef7e9bf32b1593d43368ca-head`
Browser type & version: Chrome latest

**Describe the bug**
AKS (Vue UI): Cluster details not displayed, Subnet and service role information is missing.

**To Reproduce**
- Create EKS cluster and import it from Rancher UI
- Once cluster becomes Active, edit cluster and check the fields

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/73099870/71b8a62e-5347-472e-9017-0cdb41699b1d)

**Spec:**
```
eksConfig:
    amazonCredentialSecret: cattle-global-data:cc-4v4rm
    displayName: cpinjani-eks29
    ebsCSIDriver: null
    imported: false
    kmsKey: null
    kubernetesVersion: '1.28'
    loggingTypes: []
    nodeGroups:
      - arm: null
        desiredSize: 1
        diskSize: 20
        ec2SshKey: null
        gpu: false
        imageId: null
        instanceType: t3.medium
        labels: {}
        launchTemplate: null
        maxSize: 1
        minSize: 1
        nodeRole: >-
          arn:aws:iam::REDACTED:role/cpinjani-eks29-node-instance-role-REDACTED
        nodegroupName: group1
        requestSpotInstances: false
        resourceTags: {}
        spotInstanceTypes: null
        subnets:
          - subnet-08d04305e92081795
          - subnet-02b9ee3a4ea2fab0d
          - subnet-07e95c09365177dfd
        tags: {}
        userData: null
        version: '1.28'
    privateAccess: false
    publicAccess: true
    publicAccessSources:
      - 0.0.0.0/0
    region: us-west-2
    secretsEncryption: false
    securityGroups: []
    serviceRole: null
    subnets: []
    tags: {}
```
