### ISSUE TITLE
List of container drop capabilities has mangled SYSLOGSYS_ADMIN item

### ISSUE THREAD

**Issue by skaven81** [rancher/dashboard#11548]
**Setup**
- Rancher version: latest
- Rancher UI Extensions: n/a
- Browser type & version: n/a

**Describe the bug**
When creating or editing a Pod spec, in the security context tab, the drop-down list that lets the user select from capabilities to drop, includes an invalid item, `SYSLOGSYS_ADMIN` which is actually the concatenation of the two valid items, `SYSLOG`, and `SYS_ADMIN`.  The issue can be seen in the list here: https://github.com/rancher/dashboard/blob/master/shell/components/form/Security.vue#L51 which just needs to be split into two items.

**To Reproduce**
* Create a new Workload (Deployment, StatefulSet, whatever)
* In the "container-0" tab, select the "security context" page
* In the "drop capabilities" drop-down, observe the invalid `SYSLOGSYS_ADMIN` item

**Result**
* Invalid list of dropped capabilities is rendered in the Pod spec

**Expected Result**
* `SYSLOG` and `SYS_ADMIN` should be separate drop capabilities to select.

**Screenshots**
![image](https://github.com/user-attachments/assets/3f9f33ab-10dd-48c6-9e28-8e926f9543bf)

**Additional context**
See https://man7.org/linux/man-pages/man7/capabilities.7.html for the valid list of root capabilities.  Observe that `SYSLOG` and `SYS_ADMIN` are separate capabiltiies.

**Comment by rancher-max** [comment]
### Validated using rancher `head` build

#### Version:

#### Validation:

- The two capabilities are now separate items:
<img width="604" alt="image" src="https://github.com/user-attachments/assets/6cb10694-9413-4b0e-a99e-53e6459f10d9">

- Confirmed when adding multiple containers that they remain separate items
- Confirmed different types of workloads that they remain separate items
- Confirmed in both create and edit views
- Confirmed when navigating to the pages differently (from top-level Workloads page vs. sub-item workloads, for example from the Pod page directly)
- Simple `nginx` container has the correct YAML defined:
```yaml
spec:
  affinity: {}
  containers:
    - image: nginx
      imagePullPolicy: Always
      name: container-0
      resources: {}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - SYSLOG
            - SYS_ADMIN
        privileged: false
        readOnlyRootFilesystem: false
        runAsNonRoot: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-tjzhp
          readOnly: true
```
