### ISSUE TITLE
Data Directory Configuration uses same directory for all configs

### ISSUE THREAD

**Issue by jakefhyde** [rancher/dashboard#11560]
**Describe the bug**

When selecting `Use the same path for System-agent, Provisioning and K8s Distro data directories configuration`, all of the same paths are used. This results in the system agent, provisioning, and distro components to reuse the same data directory.

**To Reproduce**

Select the checkbox.

**Result**
All data directories are configured with the same directory, e.g. in the case of `/opt/rancher` the following dataDirectories are configured on the cluster spec:
```
    dataDirectories:
      k8sDistro: opt/rancher
      provisioning: opt/rancher
      systemAgent: opt/rancher
```

**Expected Result**

Each configuration should use the same root directory (for example, `/opt/rancher`), but get the default names appended to each (e.g. `/opt/rancher/agent`, `/opt/rancher/provisioning`, and `/opt/rancher/rke2`).

**Screenshots**

**Additional context**

Follow-up to https://github.com/rancher/dashboard/issues/10824

**Comment by brandond** [comment]
1. If a single path is specified and the "use the same path" option is left checked, the specified path should be used as a common prefix for the 3 components. For example, if the user specifies `/var/lib/rancher` as the prefix for a k3s cluster, the value should be set to:
    ```yaml
    dataDirectories:
      k8sDistro: /var/lib/rancher/k3s
      provisioning: /var/lib/rancher/provisioning
      systemAgent: /var/lib/rancher/agent
    ```
2. If the user unchecks the box while a path is set, the unified path should be copied into the 3 suggested paths as a prefix, with the `/<DISTRO>`, `/provisioning`, and `/agent` paths appended to each value as appropriate.
3. This probably belongs in backend validation somewhere, and not enforced solely via the UI, but the provided paths MUST be:
  * Be absolute paths (start with /)
  * Not be set to the same thing
  * Not nested one within another
  * Be clean (not contain env vars, shell expressions, ., or ..)
