### ISSUE TITLE
Expose global fields to construct the proxy URLs for chart deployment

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1168]
Feature charts like monitoring will need access to global fields for the Rancher URL and Cluster ID of the cluster it is being deployed into in order to be able to properly set required URLs that utilize the Dashboard magic links such as:

`<rancher-url>/k8s/clusters/<cluster-id>/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy`

Specifically, it would be great if these could be provided to feature charts on deployment as part of the `values.yaml` in the following fields:
```yaml
global:
  rancher:
    url: <rancher-url>
    clusterId: <cluster-id>
```

Related Issue: https://github.com/rancher/rancher/issues/28495
