### ISSUE TITLE
v2 Istio - Message should be displayed that Istio requires v2 monitoring to be installed

### ISSUE THREAD

**Issue by bmdepesa** [rancher/dashboard#1170]
rancher/rancher:master-head c428bc9

The default v2 Istio prometheus metrics URLs in the values YAML point to Prometheus installed by Rancher's monitoring:
```
external_services:
    prometheus:
      custom_metrics_url: 'http://rancher-monitoring-prometheus.cattle-monitoring-system.svc:9090'
      url: 'http://rancher-monitoring-prometheus.cattle-monitoring-system.svc:9090'
```

With the default settings, if Rancher's monitoring is not installed, Kiali will not function correctly. A message should be displayed to the user that they should install Rancher's monitoring, or provide their own Prometheus configuration.
