### ISSUE TITLE
OPA -Unable to edit constraint created from kubectl

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#1194]
What kind of request is this:
Bug

Steps:
Create cluster, navigate to dashboard
Apps -> Charts -> rancher-gatekeeper Install
Create constraint yaml
Example yaml:
```

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: all-must-have-owner
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    message: "All namespaces must have an `owner` label that points to your company username"
    labels:
      - key: owner
        allowedRegex: "^[a-zA-Z]+.agilebank.demo$"
```
Set cluster kubectl
Run
```
kc apply -f constraint.yaml
```
Edit newly created constraint from dashboard as form

Result:
Constraint cannot be edited
![Screen Shot 2020-09-08 at 11 45 33 AM](https://user-images.githubusercontent.com/57409052/92515658-d0f9b380-f1c8-11ea-82fa-c82f129d0e18.png)

Rancher server `rancher\rancher:master-head` `version 76c26fb`

**Comment by aaronRancher** [comment]
After creating the constraint, edit as yaml works. Edit as form cannot be accessed.

**Comment by aaronRancher** [comment]
This behavior is still seen in Rancher server `rancher\rancher:master-head` `version 0390ff5`

Steps:
Create cluster, navigate to dashboard
Apps -> Charts -> rancher-gatekeeper Install
Create constraint yaml
Example yaml:

```
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: all-must-have-owner
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    message: "All namespaces must have an `owner` label that points to your company username"
    labels:
      - key: owner
        allowedRegex: "^[a-zA-Z]+.agilebank.demo$"
```

Set cluster kubectl
Run
```
kubectl apply -f constraint.yaml
```
Result:
![Screen Shot 2020-10-21 at 2 21 29 PM](https://user-images.githubusercontent.com/57409052/96788706-c5dd9a00-13a8-11eb-87db-a35c1051cef8.png)
Cannot edit with form. Edit with YAML is functional.
