### ISSUE TITLE
[RKE2/k3s] Configuration changes made as YAML lost

### ISSUE THREAD

**Issue by skanakal** [rancher/dashboard#12002]
**Setup**
- Rancher version: 2.9.2
- Rancher UI Extensions: 
- Browser type & version: Any

**Describe the bug**

**To Reproduce**

- Create a downstream RKE2 cluster (use defaults where desired, no editing as YAML at this step)
- After the cluster is provisioned, edit the cluster in Cluster Management with the "Edit YAML" button
- Add helm values to rkeConfig.chartValues (this is a basic way to repro the issue) and save, example:
```
         rkeConfig:
           chartValues:
             rke2-ingress-nginx:
               controller:
                 extraArgs:
                   enable-ssl-passthrough: true
                   watch-ingress-without-class: true
```
- Back in the form, make another basic change, such as disabling etcd recurring snapshots, and save
- Review the cluster YAML again, the chartValues are removed

**Result**

**Expected Result**

these values be modified in the YAML area without being reverted when the form is saved

**Screenshots**

https://github.com/user-attachments/assets/0a3902ed-8c49-44af-bccb-794ff873bac1

**Additional context**

Add-on Config (-----> rkeConfig.chartValues) currently only configures the CNI (Calico, Cilium,..) settings by default from the `values.yaml` in the RKE2 charts repository (https://github.com/rancher/rke2-charts/tree/main-source/packages) and does not apply to the ingress controller or other charts... 

Internal ref: SURE-8962
