### ISSUE TITLE
Extensions catalog build will add unnecessary default annotations 

### ISSUE THREAD

**Issue by jordojordo** [rancher/dashboard#12094]
**Setup**
- Rancher version: v2.9-head
- Rancher UI Extensions: N/A
- Browser type & version: N/A

**Describe the bug**

When building an ECI for an extension, regardless of what annotations are set in the `./pkg/<extension>/package.json` or  root `./package.json`, some annotations will be added.

For example, a new extension contain the annotations within the package.json file:
```json
"catalog.cattle.io/rancher-version": ">= v2.9.2",
"catalog.cattle.io/ui-extensions-version": ">= 2.0.0"
```

**To Reproduce**

```bash
yarn create @rancher/extension eci-test
cd eci-test && yarn install
yarn publish-pkgs -c -r testreg -o testorg
docker run -d --name eci-test testreg/testorg/ui-extension-eci-test:0.1.0
docker exec -it eci-test cat index.yaml
```

**Result**

<details open>
<summary>ECI index.yaml</summary>

```yaml
apiVersion: v1
entries:
  eci-test:
  - annotations:
      catalog.cattle.io/certified: rancher
      catalog.cattle.io/kube-version: '>= 1.16.0-0 < 1.29.0-0'
      catalog.cattle.io/namespace: cattle-ui-plugin-system
      catalog.cattle.io/os: linux
      catalog.cattle.io/permits-os: linux, windows
      catalog.cattle.io/rancher-version: '>= v2.9.2'
      catalog.cattle.io/scope: management
      catalog.cattle.io/ui-component: plugins
      catalog.cattle.io/ui-extensions-version: '>= 2.0.0'
    apiVersion: v2
    appVersion: 0.1.0
    created: "2024-10-02T09:09:01.771347716-04:00"
    description: eci-test plugin
    digest: 90a69b529517e0da14cc5775ddf4e3ed16762d24fd036c2777d5d896e14590a3
    name: eci-test
    type: application
    urls:
    - plugin/eci-test/eci-test-0.1.0.tgz
    version: 0.1.0
generated: "2024-10-02T09:09:01.771021172-04:00"
```

</details>

**Expected Result**

Only the necessary annotations should be added, the annotation for `kube-version` should not be added.
