### ISSUE TITLE
Cloning GlobalRole does not copy inheritedClusterRoles

### ISSUE THREAD

**Issue by inichols** [rancher/dashboard#12146]
**Setup**
- Rancher version: 2.8.5 and 2.9.2
- Rancher UI Extensions: None
- Browser type & version: Firefox 130.0.1

**Describe the bug**

With the introduction of inheritedClusterRoles, you can create Global roles with this field via Edit Yaml or CLI. However, if you wish to clone a Global role with an inheritedClusterRoles entry the inheritedClusterRoles entry does not get copied over with the clone.

**To Reproduce**

Create a Simple Global Role:
```
apiVersion: management.cattle.io/v3
kind: GlobalRole
displayName: Example Role
description: Base user + Read-only on all downstream clusters
metadata:
  name: example-gr
inheritedClusterRoles:
  - projects-view
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - preferences
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - settings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - features
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - project.cattle.io
  resources:
  - sourcecodecredentials
  verbs:
  - '*'
- apiGroups:
  - project.cattle.io
  resources:
  - sourcecoderepositories
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - rancherusernotifications
  verbs:
  - get
  - list
  - watch
 ```
Once Created, verify that Edit Yaml shows inheritedClusterRoles.
Then clone the new GlobalRole, and see that inheritedClusterRoles is not on new Global Role
 
**Result**

Cloned Global Role is missing inheritedClusterRoles section

**Expected Result**

Cloned Global Role has inheritedClusterRoles
