### ISSUE TITLE
Number of Failed and skipped tests are not available in dashboard UI

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1223]
**On master-head - commit id: `3ca11da829`**

- Deploy cis-operator from repo - `https://github.com/prachidamle/charts.git` branch: `cis-v2-chart` (on a HA setup, on a downstream custom rke cluster)
- scan app images:
```
cisoperator:
    repository: rancher/cis-operator
    tag: v0.0.4
  securityScan:
    repository: prachidamle/security-scan
    tag: v0.1.20
```
- Run a clusterscan - create a CR - scan Profile - `rke-profile-permissive`
- Scan run says `Pass` after the scan has completed.

 
<img width="1446" alt="Screen Shot 2020-09-06 at 12 33 55 PM" src="https://user-images.githubusercontent.com/26032343/92333949-44bb8500-f03e-11ea-8822-768225b0c40d.png">

- Scan summary is:
```
summary:
    fail: 0
    notApplicable: 34
    pass: 58
    skip: 0
    total: 92
```
- Skipped and Failed tests = 0 are not seen on the Dashboard UI. 

**Expected:**
Skipped and Failed tests = 0 should be available on the dashboard UI.
