### ISSUE TITLE
OPA- Namespace is not set in constraint

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#1229]
What kind of request is this:
Bug

Steps:
Create cluster, navigate to dashboard
Apps -> Charts -> rancher-gatekeeper Install
After gatekeeper is deployed, create a constraint from form
Set a namespace:
![Screen Shot 2020-09-11 at 1 05 53 PM](https://user-images.githubusercontent.com/57409052/92969319-95155700-f431-11ea-92b1-b47fe831181d.png)
Create constraint

Result:
Namespace is not set in YAML
```
spec:
  enforcementAction: deny
  match:
    excludedNamespaces:
    - cattle-gatekeeper-system
    - cattle-system
    - ingress-nginx
    - kube-node-lease
    - kube-public
    - kube-system
    - security-scan
    kinds:
    - apiGroups:
      - '*'
      kinds:
      - Pod
    labelSelector:
      matchExpressions: []
    namespaceSelector:
      matchExpressions: []
  parameters:
    repos:
    - only-this-repo
```
Example YAML with namespace set:
```
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "default"
  parameters:
    repos:
      - "only-this-repo"
```
Rancher server `rancher\rancher:master-head` `version 6a6f13c`

**Comment by aaronRancher** [comment]
Editing the constraint YAML and adding namespaces will update the YAML and the constraint will work normally. But namespaces cannot be added when editing the constraint as a form.

**Comment by codyrancher** [comment]
That's intended. We're supposed to only include the system namespaces there.

**Comment by aaronRancher** [comment]
System namespaces would be in `excluded namespaces`. We cannot set the namespaces where the constraint is enforced.

**Comment by codyrancher** [comment]
@aaronRancher can you elaborate on what the problem is? I'm not understanding what the lack of system namespaces is preventing you from doing.

This issue is the one that requested that we exclude the system namespaces. https://github.com/rancher/dashboard/issues/455

@prachidamle do we need show the system namespaces now?

**Comment by aaronRancher** [comment]
@codyrancher Excluding the system namespaces is fine. This is not about the system namespaces.
We are not able to set non-system namespaces (the default namespace in this case) under the enforced namespace field. Because of this, the namespace we want enforced by the constraint is not being enforced.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version ec04f78 `

Steps:
Create cluster, navigate to dashboard
Apps -> Charts -> rancher-gatekeeper Install
After gatekeeper is deployed, create a constraint from form
Set the default namespace in the enforced namespace field

Result:
Default namespace is set and constraint is enforced in namespace:
```
spec:
  enforcementAction: deny
  match:
    excludedNamespaces:
    - cattle-system
    - fleet-system
    - kube-node-lease
    - kube-public
    - kube-system
    kinds:
    - apiGroups:
      - '*'
      kinds:
      - Pod
    labelSelector:
      matchExpressions: []
    namespaceSelector:
      matchExpressions: []
    namespaces:
    - default
  parameters:
    repos:
    - only-this-repo
```
