### ISSUE TITLE
Feature Request: Support harvester-baremetal-container-workload clusters

### ISSUE THREAD

**Issue by iamwillbar** [rancher/dashboard#12518]
### Is your feature request related to a problem?

There does not appear to be any way to target Harvester clusters when the harvester-baremetal-container-workload feature flag is enabled. Harvester clusters are excluded from the "All clusters in this workspace" filter, "Advanced" filter, or cluster groups that contain Harvester clusters.

### Solution you'd like

When the harvester-baremetal-container-workload feature flag is enabled, don't filter Harvester clusters from the target.

### Alternatives you've considered

Using advanced targeting and cluster groups.

**Comment by richard-cox** [comment]
If the UI supplies an explicit list it needs to take into account the `harvester-baremetal-container-workload` FF before filtering them out. We do this in a number of places, possibly not here.

FF Enable - don't filter harvester clusters
FF Disable (default) - filter harvester clusters

**Comment by torchiaf** [comment]
The UI adds a specific target to exclude Harvester clusters:

```
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester
```
But it doesn't take in account the feature flag, so we need to implement a check here.
We also need to verify that Harvester clusters are listed in Fleet Clusters table when target by any Fleet applications
