### ISSUE TITLE
HPA objects configuration is empty when an external metric is present

### ISSUE THREAD

**Issue by eva-vashkevich** [rancher/dashboard#12699]
**Setup**
- Rancher version: 2.10
- Rancher UI Extensions: N/A
- Browser type & version: N/A
- JIRA: SURE-9299

**Describe the bug**

When an horizontal pod auto-scaler has metrics that include an external one, its configuration is no longer present in the Rancher UI. For example, this configuration (the problematic part is in bold) triggers the issue:

**To Reproduce**

Local -> Service discovery -> HorizontalPodAutoscalers

Create an HPA with metrics that include an external  (here is sample spec):
```
spec:
  maxReplicas: 9
  metrics:
    - external:
        metric:
          name: s1-prometheus
          selector:
            matchLabels:
              scaledobject.keda.sh/name: test
        target:
          averageValue: '5'
          type: AverageValue
      type: External
    - resource:
        name: cpu
        target:
          averageUtilization: 2
          type: Utilization
      type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test
```
Check the HPA in the Rancher UI, the configuration will be empty
Remove the external metric, the UI shows the HPA with the configuration tabs
This also happens when manually creating an HPA in the UI with a normal resource and an external one.

**Result**
Configuration is empty.
The following error is shown in the console:
```
entry-helpers.js:40 TypeError: Cannot read properties of undefined (reading 'name')
    at index.vue:48:1
    at Proxy.map (<anonymous>)
    at Proxy.mappedMetrics (index.vue:45:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:1)
    at get value (reactivity.esm-bundler.js:1171:1)
    at Object.get [as mappedMetrics] (runtime-core.esm-bundler.js:3488:1)
    at index.vue:102:1
    at renderFnWithContext (runtime-core.esm-bundler.js:868:1)
    at renderSlot (runtime-core.esm-bundler.js:3025:1)
    at Proxy.render (Tab.vue:113:1)
```
<img width="1834" alt="Screenshot 2024-11-27 at 12 25 44 PM" src="https://github.com/user-attachments/assets/6d806c04-0b2c-426b-8532-403ed4157b84">

**Expected Result**

Configuration tabs should be visible.

<img width="1576" alt="Screenshot 2024-11-27 at 12 27 35 PM" src="https://github.com/user-attachments/assets/6919d964-1249-44a9-b428-c0d98a5e068c">

**Screenshots**

**Additional context**
