### ISSUE TITLE
Issues in volume claim template for statefulsets

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1292]
**On master-head - commit id: `33f755f18`**

- Navigate to Dashboard --> Workload --> Overview --> Create Statefulset --> Volume claim templates --> Add claim

**Issue#1**
- There are no options like how we have in the Ember UI to define a template using Storage class OR a  Persistent Volume. Only a dropdown listen the persistent volume claims is available

**Expected:**
User should be able to create a volume claimtemplate from a Storage class or a PV

**Issue#2**

- Click on the drop down and select a value
- Value selected is NOT listed

<img width="1562" alt="Screen Shot 2020-09-17 at 3 46 42 PM" src="https://user-images.githubusercontent.com/26032343/93536252-71548400-f8fd-11ea-948b-7e2bc99b9916.png">
<img width="1460" alt="Screen Shot 2020-09-17 at 3 46 54 PM" src="https://user-images.githubusercontent.com/26032343/93536254-731e4780-f8fd-11ea-9835-c41a29594fa8.png">

**Comment by khushboo-rancher** [comment]
This use case is important for longhorn as the user might not be able to create statefulset (with more than 1 replica) attached to the volume in the form view because of this issue.
cc: @yasker

**Comment by yasker** [comment]
This is preventing the user to create a statefulset with a volume claim template, which will affect all the persistent storage systems.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `27000be`**

- Dashboard --> Workload --> Overview -->Create a stateful set
**Scenario#1**
Using storage class
- Select Volume claim templates  --> Give in details of storage class
- Replicas - 3. Stateful set is created successfully

**Scenario#2**
Using persistent volumes:
- Create a PV ( EBS Disk) (on a EKS HA cluster)
- Select Volume claim templates  --> Give in details
<img width="865" alt="Screen Shot 2020-09-27 at 10 36 40 AM" src="https://user-images.githubusercontent.com/26032343/94371766-cc306d00-00ad-11eb-8a5a-4a5f41aa5cb1.png">

- Request sent contains:
```
name: "vol1"
namespace: "default"
spec: {accessModes: ["ReadWriteOnce"], resources: {requests: {storage: "10Gi"}}, volumeName: "test-2"}
accessModes: ["ReadWriteOnce"]
resources: {requests: {storage: "10Gi"}}
requests: {storage: "10Gi"}
storage: "10Gi"
volumeName: "test-2"
type: "persistentvolumeclaim"
```
- Workload is stuck in `In progress` state.
- PVC that got created:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2020-09-27T17:36:43Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-test-2-pv
  name: vol1-test-2-pv-0
  namespace: default
....
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: test-2
status:
  phase: Pending
```
- Error seen in Ember UI on the PVC is : `Cannot bind to requested volume "test-2": storageClassName does not match`

Reopening the issue

**Comment by sowmyav27** [comment]
**On master-head - commit id: `ec04f7878c`**

- Dashboard --> Workload --> Overview -->Create a stateful set
- Volume Claim templates --> Select "Use an existing persistent volume"
- The dropdown does NOT change to available "Persistent Volumes". It still lists available "Storage classes."

<img width="1668" alt="Screen Shot 2020-09-28 at 12 27 15 PM" src="https://user-images.githubusercontent.com/26032343/94477097-42a09e00-0186-11eb-8401-cb5228d172da.png">

Reopening because of ^^^ issue

- Stateful set using Storage class in Volume claim template works.

**Comment by khushboo-rancher** [comment]
Verified on the latest dashboard.

On creating a stateful set with a volume claim template using longhorn class, the stateful set is stuck in ```in progress``` state.
The ```VolumeClaimTemplate``` is missing in the YAML and the name of the volume mount is empty.
The YAML generated:
```
spec:
      containers:
      - image: ubuntu
        imagePullPolicy: Always
        name: wk-3
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data
          name: ""
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```
The expected YAML should be:
```
spec:
      containers:
      - image: ubuntu
        imagePullPolicy: Always
        name: wk-3
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data
          name: ""
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 1Gi
```
