### ISSUE TITLE
Deployment details page contains pods from another deployment

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#12957]
**Setup**
- Rancher version: 2.10.1
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

The UI is probably filtering the pods by `labels`. The pods list should be `deployment.spec.template.spec.containers` array.

**To Reproduce**

- Create 2 deployments using the same labels/annotations:

```
# Source: sensors/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-controller
  labels:
    helm.sh/chart: sensors-0.1.0
    app.kubernetes.io/name: sensors
    app.kubernetes.io/instance: sensors
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sensors
      app.kubernetes.io/instance: sensors
  template:
    metadata:
      labels:
        helm.sh/chart: sensors-0.1.0
        app.kubernetes.io/name: sensors
        app.kubernetes.io/instance: sensors
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: sensors
      securityContext:
        {}
      containers:
        - name: sensors
          securityContext:
            {}
          image: "ghcr.io/torchiaf/sensors/controller:main"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {}
          envFrom:
            - secretRef:
                name: sensors-rabbitmq
                optional: false
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
---
# Source: sensors/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-raspberrypi
  labels:
    helm.sh/chart: sensors-0.1.0
    app.kubernetes.io/name: sensors
    app.kubernetes.io/instance: sensors
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sensors
      app.kubernetes.io/instance: sensors
  template:
    metadata:
      labels:
        helm.sh/chart: sensors-0.1.0
        app.kubernetes.io/name: sensors
        app.kubernetes.io/instance: sensors
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: sensors
      securityContext:
        {}
      containers:
        - name: sensors
          securityContext:
            privileged: true
          image: "ghcr.io/torchiaf/sensors/raspberrypi:main"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {}
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          envFrom:
            - secretRef:
                name: sensors-rabbitmq
                optional: false
      nodeSelector:
        sensors.role: worker
```

**Result**

![image](https://github.com/user-attachments/assets/7f6dd2cb-9d5b-4144-9134-6897f6d8dd88)

**Additional context**
