### ISSUE TITLE
Allow users to configure Cluster Agent Priority Classes And Pod Disruption Budgets on rke2 and k3s clusters

### ISSUE THREAD

**Issue by eva-vashkevich** [rancher/dashboard#13068]
RFC: Cluster Agent Priority Classes And Pod Disruption Budgets
JIRA: SURE-9007, SURE-8174

This feature will only be supported for node-driver provisioned and custom rke2/k3s clusters and generic imported clusters.

Please refer to the RFC for UI spec: RFC-22

**Comment by richard-cox** [comment]
@eva-vashkevich  Might have brought this up elsewhere, but might sure to review the description once / if the RFC is approved by the RATs team

**Comment by yonasberhe23** [comment]
Requires manual validation.

**Comment by izaac** [comment]
This looks good during testing. But I wanted to confirm these are the default values expected when the `Prevent Rancher cluster agent pod eviction` is checked.

```yaml
  clusterAgentDeploymentCustomization:
    schedulingCustomization:
      podDisruptionBudget:
        maxUnavailable: '0'
        minAvailable: '1'
      priorityClass:
        preemptionPolicy: PreemptLowerPriority
        value: 1000000000
```

@eva-vashkevich
