### ISSUE TITLE
[Logging v2] Installed App with one option true in additionalLoggingSources shows false for all when checking Values yaml view

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1316]
After installing `rancher-logging` in one of the supported Control Plane Additional sources I don't see the values used during installation properly.

Sample from a k3s openrc using 

```
   k3s:
    container_engine: openrc
    enabled: true
```

Checking the Installed App shows:

```
additionalLoggingSources:
  eks:
    enabled: false
  k3s:
    container_engine: systemd
    enabled: false
  rke:
    enabled: false
  rke2:
    enabled: false
```

![Screen Shot 2020-09-19 at 12 28 55 PM](https://user-images.githubusercontent.com/27659/93687658-20b36700-fa74-11ea-9c01-12c6fffa66c4.png)

_** The app was installed properly with the control plane option enabled **_
rancher/dashboard#1109

Rancher version `master-head (09/19/2020)` _bd88c23_ HA k8s
