### ISSUE TITLE
[Logging v2] do not add additionalLoggingSources on not yet supported platforms

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1335]
On AKS I tried installing the `rancher-logging` chart.

- Dashboard -> Apps -> `rancher-logging`
- Click Chart Options
- Click Preview YAML

We only support `rke` - `k3s` - `rke2` and `eks` on v2.5 but in this case Dashboard is adding **aks**

```
...
additionalLoggingSources:
  eks:
    enabled: false
  k3s:
    container_engine: systemd
    enabled: false
  rke:
    enabled: false
  rke2:
    enabled: false
  aks:         <------- HERE
    enabled: true
...
```
