### ISSUE TITLE
Implement CRD logic for SCC registration online

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#13387]
# Description

Implement existing UX to bind with developed CRD.

## Context

Based on new updates provided by @mallardduck due security and semplification of the process, this would require to just create a secret with hardcoded name.
To create a new registration:
- (if any) Delete current secret with namespace/name `cattle-scc-system/scc-registration`
- Create a new secret:

```
metadata:
  name: "scc-registration"
  namespace: cattle-scc-system
data:
  regCode: <base64 of regCode>
  registrationType: <base64 of "online" or "offline">
```

Returned value will contain a label to identify the registration:

```
metadata:
  labels:
    scc.cattle.io/managed-by: secret-broker
    scc.cattle.io/scc-hash: 15d21b95243939209e4ea79ef1d84558
```

Registration CRD: `scc.cattle.io.registration`
