### ISSUE TITLE
Can't create a usable deployment

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1352]
Issue:  To associate a service to a deployment, I need to be able to add labels to a pod.

Steps:
1.  Create a wordpress deployment
2.  Try to associate a Node port service to that deployment

Results:  The labels I attached to my deployment are not passed down to the pods... and there is no way to add a simple pod label in deployment.  The service requires a Selector to match a label in the pod.

This will go for all workloads.

**Comment by deniseschannon** [comment]
@mantis-toboggan-md There are 2 levels of metadata (labels/annotations) in workloads
```
metadata:
   labels:
   annotations:
spec:
  template:
      metadata:
          annotations:
          labels:
````

Currently, the labels/annotations in the UI is mapping to `metadata.labels` or `metadata.annotations` but it needs to map to `spec.template.metadata.labels` or `spec.template.metadata.annotations` instead.

This is the behavior of how we add labels and annotations in ember today. Without this change, the pods aren't getting labels which is what is used for selectors.
