### ISSUE TITLE
Difficult to stop logs from scrolling

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#13545]
**Setup**
- Rancher version: v2.10.3

**Describe the bug**
- When viewing the logs of a chatty pod the user should be able to scroll up (either by mouse wheel or manually using scroll bar) to see earlier entries. The `Follow` button should then become enabled and any new log entries should not impact the visible log lines. If the user wants to see those and keep the new log lines visible they could scroll back to the bottom or press the Follow button
- However... this often does not work
  - scrolling up using mouse wheel often just returns the user to the bottom of the logs showing the new log lines
  - the same goes for scroll bar
- Sometimes this does work, i'm guessing it's a timing issue with when the log line comes in

**To Reproduce**
- Deploy a pod with a chatty log (there must be some good examples out there in docker hub)
- Worklods --> Pods --> View log

**Result**
- as per description

**Expected Result**
- as per description

**Additional context**
- Setting this as a high priority, as it's a large application developer use case

**Comment by richard-cox** [comment]
Linking https://github.com/rancher/dashboard/issues/12644

**Comment by codyrancher** [comment]
To make a chatty pod you could use 

```
apiVersion: v1
kind: Pod
metadata:
  name: log-generator
  namespace: default
  labels:
    app: log-generator
spec:
  containers:
    - name: log-generator
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          i=0
          while true; do
            echo "$(date +%Y-%m-%dT%H:%M:%SZ) [INFO] Log entry $i - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore."
            i=$((i+1))
            sleep 0.01
          done
  restartPolicy: Never
```
