### ISSUE TITLE
[SURE-9943] Registry Secrets content not visible (created from json file)

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#13786]
**Setup**
- Rancher version: 2.10.2
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

Registry secrets are not shown correctly in the UI. we tracked the root cause down to the docker registry secrets being created by kubectl from a json file. The json file is obtained from docker login. the resulting secret does not have username, password fields. Which seem to be required for Rancher.

**To Reproduce**

Import this secret via YAML

```
apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: default
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0ZXN0LmVhZC5kb20iOnsiYXV0aCI6IllXRmhPbUZoIn19fQ==
type: kubernetes.io/dockerconfigjson
```

Go to the details view of the secret, UI crashes

**Result**
UI crashes

**Expected Result**

UI shouldn't crash

**Screenshots**

**Additional context**

SURE-9943
