### ISSUE TITLE
Inconsistent display of Internal & External IPv4/IPv6 addresses for Nodes

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#13792]
JIRA: SURE-9053

**Setup**
- Rancher version: SUSE Rancher 2.9.1, SUSE Rancher 2.10.2 
- Rancher UI Extensions: NA
- Browser type & version: Firefox/Chrome Latest

**Describe the bug**

The UI is showing "External IP"s as IPV4 and "Internal IP"s as IPV6 when looking at IPs for nodes.

**To Reproduce**

Create a node with multiple internal IP Addresses, for example:

```yaml
status:
  addresses:
    - address: 41.130.94.198
      type: InternalIP
    - address: 4f56:5ebe:f26f:c178:6aaf:3ae2:31e4:fa14
      type: InternalIP
    - address: 41.130.94.198
      type: ExternalIP
    - address: test01
      type: Hostname
```

**Result**

If a node has multiple IP addresses, inconsistent results can be displayed. 

**Expected Result**

IPV4 and IPV6 addresses are displayed in a consistent and predictable way.

**Screenshots**

NA

**Additional context**

To display ip addresses, we opt to display the last address with a type of `InternalIP`, for example, we would display `172.17.0.2` because there's only a single entry for `InternalIP`:

```yaml
status:
  addresses:
    - address: 172.17.0.2
      type: InternalIP
    - address: 6c68ff62b731
      type: Hostname
```

`node.status.addresses` is defined in the Node manifest and can fall under on of the following configurations:

> IPv4 only: The network plugin, kube-apiserver and kubelet/cloud-controller-manager are configured to assign only IPv4 addresses.
> IPv6 only: The network plugin, kube-apiserver and kubelet/cloud-controller-manager are configured to assign only IPv6 addresses.
> IPv4/IPv6 or IPv6/IPv4 [dual-stack](https://kubernetes.io/docs/concepts/services-networking/dual-stack/):
> - The network plugin is configured to assign IPv4 and IPv6 addresses.
> - The kube-apiserver is configured to assign IPv4 and IPv6 addresses.
> - The kubelet or cloud-controller-manager is configured to assign IPv4 and IPv6 address.
> All components must agree on the configured primary IP family.

- https://kubernetes.io/docs/concepts/cluster-administration/networking/#cluster-network-ipfamilies
- https://kubernetes.io/docs/reference/node/node-status/#addresses

## Proposed solution

Split the single "External/Internal IP" column into two: "External (IPv4) / External (IPv6)" and "Internal (IPv4) / Internal (IPv6)".

We can match IPV4 addresses by testing for valid octets/IPV6 for valid hextets
