### ISSUE TITLE
Rancher logging RKE2 UI bug when changing tolerations block

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#13980]
SURE-10002

**Setup**
- Rancher version: SUSE Rancher 2.10.3/2.11.0/head
- Rancher UI Extensions: NA
- Browser type & version: Latest Firefox & Chrome

**Describe the bug**

Editing the tolerations block for the fluentbit pods in the logging chart the existing block does not get removed, despite the fact that "helm -n cattle-logging-system get values rancher-logging" shows correct values:

**To Reproduce**

- Install latest logging chart Logging chart:  105.2.1+up4.10.0, in your environment with default values
- In Apps -> Installated Apps -> rancher-logging -> Values YAML: Replace the Toleration "value: true" to "operator: Exists" and save. You will notice two things: 1. the fluentbit pods now get scheduled on the control-plane node as well, and 2. when checking the yaml after save, the "value: true field" still exists and no matter how many times it gets deleted. So, if you update the rancher-logging chart to remove the value: "true" field from additionalLoggingSources.kubeAudit.tolerations or fluentbit.tolerations, the change is applied and reflected in the deployed helm values for the chart (helm -n cattle-logging-system get values rancher-logging), but the Rancher Apps feature still shows the field present (Apps -> Installated Apps -> rancher-logging -> Values YAML)

**Result**

The UI is misleading: If you update the rancher-logging chart to remove the value: "true" field from additionalLoggingSources.kubeAudit.tolerations or fluentbit.tolerations the change is applied and reflected in the deployed helm values for the chart (helm -n cattle-logging-system get values rancher-logging), but the Rancher Apps feature still shows the field present (Apps -> Installated Apps -> rancher-logging -> Values YAML)

**Expected Result**

Fluent-bit pods toleration block should  update as per edits.

**Screenshots**

**Additional context**

This behavior can be traced to the following merge behavior in Dashboard:

https://github.com/rancher/dashboard/blob/eb3cc9a096fdd0c3c3a9e2a895e8eabbf199fa1b/shell/pages/c/_cluster/apps/charts/install.vue#L315-L323

`versionInfo` contains the default `value: 'true'` lines that get merged with the `userValues` to produce the invalid result:

```yaml
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          value: 'true'
          operator: Exists
``` 

When checking "helm -n cattle-logging-system get values rancher-logging" the toleration block is correct

```bash
> helm -n cattle-logging-system get values rancher-logging
USER-SUPPLIED VALUES:
additionalLoggingSources:
  rke2:
    enabled: true
fluentbit:
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoExecute
    key: node-role.kubernetes.io/etcd
    operator: Exists
global:
  cattle:
    clusterId: c-m-tnw9vnk9
    clusterName: mandronic-rke2
    rkePathPrefix: ""
    rkeWindowsPathPrefix: ""
    systemDefaultRegistry: registry.rancher.com
    systemProjectId: p-fvmwv
    url: https://mandronic-tf-do-rke.do.support.rancher.space
  systemDefaultRegistry: registry.rancher.com
```

**Comment by gaktive** [comment]
@rak-phillip will gather a few more details around this but we've narrowed this down to something in dashboard.

**Comment by IsaSih** [comment]
I am not able to reproduce the issue (rancher-logging version rancher-logging:106.0.1+up4.10.0-rancher.4) , rancher version
[Rancher](https://github.com/rancher/rancher)	v2.12-6f23fe63e806c3278916280e7a1ad5ff2cce84f4-head
[Dashboard](https://github.com/rancher/dashboard)	master ac02757
[Rancher CLI](https://github.com/rancher/cli)	v2.11.0-rc.1

but I'm unsure that I'm following the correct steps:
By editing the Values YAML in the UI, the "operator: Exists" is replaced by "value: true"  in the tolerations block. But there's no Save button and in the reproduction steps it mentions clearly to make these changes and Save. I am just switching tabs after editing the YAML, and I don't know if this actually saves the changes. Aother thing that I observed is that the command `helm -n cattle-logging-system get values rancher-logging` does not return me the tolarations in the output. What I get is 
```
helm -n cattle-logging-system get values rancher-logging
USER-SUPPLIED VALUES:
additionalLoggingSources:
  rke2:
    enabled: true
global:
  cattle:
    clusterId: local
    clusterName: local
    rkePathPrefix: ""
    rkeWindowsPathPrefix: ""
    systemDefaultRegistry: ""
    systemProjectId: p-fztx9
    url: https://ig212.qa.rancher.space
  systemDefaultRegistry: ""

```
