### ISSUE TITLE
UI extensions have an 'experimental' label if any version of the extension is annotated as experimental

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#14080]
**Setup**
- Rancher version:
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
If one of any versions of a ui extension has the experimental label, the extension is labeled as experimental in the UI. It should only be labeled 'experimental' if the latest version of the extension is labeled experimental.

**To Reproduce**
The capi ui extension has experimental and non-experimental versions. Add the capi ui repo:

```
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: capi-ui
spec:
  url: https://rancher.github.io/capi-ui-extension
```

Navigate to the ui extensions page and select the 'available' tab

**Result**
The capi ui extension card is labeled 'experimental' even though the latest version of the capi ui is not labeled experimental.

**Expected Result**
The capi ui extension card shouldn't be labeled experimental

**Screenshots**

![Image](https://github.com/user-attachments/assets/b62b0006-950b-4116-b432-fcca9f4d164c)
