### ISSUE TITLE
Fleet: Bundles fail to deploy to target cluster

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#14146]
**Setup**
- Rancher version: v2.12

**Describe the bug**
Bundles fail to deploy to the target cluster. 

**To Reproduce**

1. Go to Continuous Delivery > Bundles
2. Create a Bundle with the following manifest:

```
apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: test
  namespace: fleet-local
#  annotations:  key: string
#  labels:  key: string
spec:
   targets:
    - clusterName: local
      clusterSelector:
        matchExpressions:
          - key: fleet.cattle.io/non-managed-agent
            operator: DoesNotExist
      ignore: {}
```
3. Observe the bundle's status

**Result**

- Bundle status remains Wait Applied
- Deployments show 0/1
- No errors are visible in the UI

**Expected Result**

- Bundle should deploy successfully to the local cluster
- Status should progress to Ready or Deployed with 1/1 deployments

**Screenshots**

<img width="933" alt="Image" src="https://github.com/user-attachments/assets/19c90359-fb07-4f29-b9a9-a7679593015f" />

**Additional context**
