### ISSUE TITLE
Ingress rules path are not saved

### ISSUE THREAD

**Issue by Carl-NRCan** [rancher/dashboard#14155]
**Setup**
- Rancher version: 2.10.2-2.10.3
- Rancher UI Extensions: None/Default
- Browser type & version: Chrome, FireFox, Edge

**Describe the bug**
Ingress rules' paths are not saved.

**To Reproduce**
Create a new ingress, enter the host, select the path, target service and port. Save

**Result**
Reopen the config and the path section is completely empty 

**Expected Result**
Ingress config should be saved

**Screenshots**

![Image](https://github.com/user-attachments/assets/db08484c-fa3e-4dc4-886b-29f728f49623)

**Additional context**
Using kubectl is a workaround

**Comment by richard-cox** [comment]
Could not reproduce in `v2.11.2` or latest (`v2.12-889b361b6e58f33e1d6c551a9b6020db256e65c0-head`).

Will pass this to QA just in case there's any angle i might have missed

**Comment by yonasberhe23** [comment]
Was able to repro on Rancher v2.12-a6cd41bab9f04624f1b2760de9ca335831ac6724-head / Dashboard master ff12e4a

1. go to Ingress Create page
2. enter name
3. enter Host, 
4. select Path: Prefix
5. leave second input blank (this is what causes the issue)
6. select Target Service
7. select Port
8. Create
9. List view > notice target column is blank
10. Edit Config > notice path section is blank

https://github.com/user-attachments/assets/761f2850-e934-4ad0-a601-834b0d2c8211

**Comment by rak-phillip** [comment]
I think that getting validation in place to assert that the paths are specified properly will resolve the issue. 

In reading the Kubernetes docs, a path of `null` or `undefined` is invalid[^1]. We can confirm this with the following Ingress manifest:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test1
spec:
  rules:
  - host: "example.com"
    http:
      paths:
      - pathType: Prefix
        path: ""
        backend:
          service:
            name: kubernetes
            port:
              number: 443
```

The following error is produced when we apply this manifest via `kubectl apply -f ingress.yaml`:

```
The Ingress "test1" is invalid: spec.rules[0].http.paths[0].path: Invalid value: "": must be an absolute path
```

There's still the question of why Rancher is successfully creating the rule, where kubectl will return an error. It looks like the invalid http block is completely dropped by Rancher when an invalid path is specified. 

[^1]: https://kubernetes.io/docs/concepts/services-networking/ingress/#examples
