### ISSUE TITLE
Table column data does not show for CRDs that use JSON Path notation with dots in field names

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#14358]
Internal Reference: SURE-10198

The `additionalPrinterColumns` for a CRD can use the JSON Path syntax that allows columns to reference fields where there is a period `.` in the field name - often used in k8s for labels, where the label name itself contains a period, for example:

```
.metadata.labels.node\.kubernetes\.io/instance-type
```

This does not work in Rancher and the column will show no data.

To reproduce, import this YAML into a cluster - this will add a test CRD and 2 resources of that CRD type.

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: shirts.stable.example.com
spec:
  group: stable.example.com
  scope: Namespaced
  names:
    plural: shirts
    singular: shirt
    kind: Shirt
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              color:
                type: string
              size:
                type: string
    selectableFields:
    - jsonPath: .spec.color
    - jsonPath: .spec.size
    additionalPrinterColumns:
    - jsonPath: .spec.color
      name: Color
      type: string
    - jsonPath: .spec.size
      name: Size
      type: string
    - jsonPath: .metadata.labels.node\.kubernetes\.io/instance-type
      name: Type
      type: string
    - jsonPath: .metadata.labels.karpenter\.sh/capacity-type
      name: Capacity
      type: string
    - jsonPath: .metadata.labels.topology\.kubernetes\.io/zone
      name: Zone
      type: string
---
apiVersion: stable.example.com/v1
kind: Shirt
metadata:
  name: test-shirt
  namespace: default
  labels:
    node.kubernetes.io/instance-type: "type-1"
    karpenter.sh/capacity-type: "large-capacity"
    topology.kubernetes.io/zone: "custom-zone"
spec:
  color: "red"
  size: "large"
---
apiVersion: stable.example.com/v1
kind: Shirt
metadata:
  name: test-shirt-2
  namespace: default
  labels:
    node.kubernetes.io/instance-type: "type-2"
    karpenter.sh/capacity-type: "medium-capacity"
    topology.kubernetes.io/zone: "custom-zone-2"
spec:
  color: "yellow"
  size: "small"
```

Explore the cluster and use the resource type search to find the custom resource (search for `Shirt').

List will render like this:

![Image](https://github.com/user-attachments/assets/2f3319e8-a720-47fd-97ed-d3e2f005d5df)

The `Capacity` and `Zone` columns for the two resources should show data and should nor be empty.
