### ISSUE TITLE
Fleet: Bundles fail to deploy to target cluster for ~8 minutes due to TLS handshake error

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#14559]
**Setup**
- Rancher version: v2.12
- Install type: Docker

**Describe the bug**
Bundles fail to deploy to the target cluster for ~8 minutes after Rancher is brought up via Docker.

**To Reproduce**

1. Start Rancher using the official Docker method
2. Go to Continuous Delivery > Bundles
3. Create a Bundle with the following manifest:

```
apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: test
  namespace: fleet-local
#  annotations:  key: string
#  labels:  key: string
spec:
   targets:
    - clusterName: local
      clusterSelector:
        matchExpressions:
          - key: fleet.cattle.io/non-managed-agent
            operator: DoesNotExist
      ignore: {}
```
3. Observe the bundle's status

**Result**

- Bundle status remains Wait Applied
- Deployments show 0/1
- No errors are visible in the UI

**Expected Result**

- Bundle should deploy successfully to the local cluster
- Status should progress to Active 
- Deployments show 1/1

**Screenshots**

<img width="933" alt="Image" src="https://github.com/user-attachments/assets/19c90359-fb07-4f29-b9a9-a7679593015f" />

**Additional context**
UPDATE: This issue is not related to Fleet itself. Investigation by the Fleet team confirms the delay is caused by TLS cert readiness in the Rancher backend, specifically when installed via Docker.

Logs shows that dynamic listener certs are not ready for several minutes after startup, blocking Fleet from applying bundles.

**Comment by mmartin24** [comment]
Tested and could not reproduce v2.12-62362dfd905a75f77865a47aff683a195cc6ac66-head with Fleet fleet:107.0.0+up0.13.0-alpha.3 and not observable:

![Image](https://github.com/user-attachments/assets/a7cbfdbc-dd2a-4e70-bf73-6fbaaff2481d)


Note: we tested with custom flags and when tried to add `aggregated-roletemplates` flag we noticed ad lock and we cannot modify this one. Not sure if this expected. 

![Image](https://github.com/user-attachments/assets/8b644c6f-0311-44ab-8853-88e752507515)

**Comment by mmartin24** [comment]
With the help of @torchiaf , I managed to deploy Rancher with `aggregated-roletemplates=true` and it worked for me:

![Image](https://github.com/user-attachments/assets/63fc80e9-f8d6-4d16-bf25-f58727f71fd2)

My setup (it contains other flags for other tests, not relevant here):

```
helm upgrade --install rancher rancher-latest/rancher \
  --devel \
  --set rancherImageTag=head \
  --namespace cattle-system --create-namespace \
  --set "extraEnv[0].name=CATTLE_SERVER_URL" \
  --set 'extraEnv[1].name=CATTLE_AGENT_IMAGE' \
  --set hostname=$SYSTEM_DOMAIN \
  --set bootstrapPassword=password \
  --set replicas=1 \
  --set agentTLSMode=system-store \
  --set-string "fleet.extraEnv[0].name=EXPERIMENTAL_HELM_OPS" \
  --set 'extraEnv[2].name=CATTLE_FEATURES' \
  --set 'extraEnv[2].value=aggregated-roletemplates=true' \
  \
  --set "extraEnv[1].value=rancher/rancher-agent:head" \
  \
  --wait
```

Not sure if I am missing something on the automation, but manually at least seems ok to me.

**Comment by yonasberhe23** [comment]
@mmartin24 thank you for confirming. I'll give it a quick test on the automation side

**Comment by yonasberhe23** [comment]
The test is still failing on CI and I was able to reproduce the issue locally on rancher v2.12-8024ff603044f337d9e2df5492a45893a1133295-head. @mmartin24 i'll DM my setup

Automation failure:

<img width="1083" alt="Image" src="https://github.com/user-attachments/assets/62e72911-3210-452b-9c19-8de1eecded7b" />

Local failure:

https://github.com/user-attachments/assets/9abbc310-a75b-482e-aef7-b035c4625035

**Comment by mmartin24** [comment]
> The test is still failing on CI and I was able to reproduce the issue locally on rancher v2.12-8024ff603044f337d9e2df5492a45893a1133295-head. [@mmartin24](https://github.com/mmartin24) i'll DM my setup
> 
> Automation failure:
> 
> <img alt="Image" width="1083" src="https://private-user-images.githubusercontent.com/127343932/452395086-62e72911-3210-452b-9c19-8de1eecded7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDk0NTM4NTMsIm5iZiI6MTc0OTQ1MzU1MywicGF0aCI6Ii8xMjczNDM5MzIvNDUyMzk1MDg2LTYyZTcyOTExLTMyMTAtNDUyYi05YzE5LThkZTFlZWNkZWQ3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDYwOVQwNzE5MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODhhN2VmZTk3NjNiMGIyM2RhZGI4M2U2ZmQ3ZjcxNzk4ZGJjMWE1YjllMGEyY2NlYmM5NjhhZDI5MDc5ZTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UQUqmFNfcRUoSghor7eFKQGubizr10lARWAtFBcvmBY">
> Local failure:
> 
>  Screen.Recording.2025-06-06.at.9.40.52.AM.mov

@yonasberhe23 , the set up sent seems no longer available. Can you pls re-share?. Also mind pls sending the specific command used to install rancher to ensure I have the same? Thanks.

**Comment by yonasberhe23** [comment]
@mmartin24 I was able to reproduce the issue without the aggregated-roletemplates=true parameter, so it may have nothing to do with that setting. The bundle does eventually become active, so this may point to some kind of performance degradation or delayed reconciliation rather than a configuration issue.

The attached video shows that the bundle is still not active after 7 minutes. (Note: the video does not show it becoming active, but it does transition to active after around 9 minutes.)

https://github.com/user-attachments/assets/8f7975ae-d739-498c-8857-09960fa61b6e



This is the command i used to install Rancher:
`docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  --privileged \
  rancher/rancher:v2.12-8024ff603044f337d9e2df5492a45893a1133295-head
`

**Comment by mmartin24** [comment]
Thanks @yonasberhe23 .
I see it only happens when deploying via docker.
I add  a describe on the bundle and I will check with the team. 


``` yaml
> k describe -n fleet-local bundles.fleet.cattle.io 
Name:         fleet-agent-local
Namespace:    fleet-local
Labels:       objectset.rio.cattle.io/hash=2c708c6974cf00d8ca0d5c0f1706ab63548b55d2
Annotations:  objectset.rio.cattle.io/applied:
                H4sIAAAAAAAA/4yTSW/bPBCG/0owZ8qR7cgLge/0JeihgFukyyXJYUSObdZcBHLkxjX03wtKTuIGTdubRHKW93lnjuCIUSMjyCOg94GRTfAp/4b6GylOxKNowkghs6WRCZdGg4S1Je...
              objectset.rio.cattle.io/id: fleet-manage-agent
              objectset.rio.cattle.io/owner-gvk: /v1, Kind=Namespace
              objectset.rio.cattle.io/owner-name: fleet-local
              objectset.rio.cattle.io/owner-namespace: 
API Version:  fleet.cattle.io/v1alpha1
Kind:         Bundle
Metadata:
  Creation Timestamp:  2025-06-10T09:48:11Z
  Finalizers:
    fleet.cattle.io/bundle-finalizer
  Generation:  1
  Owner References:
    API Version:           v1
    Block Owner Deletion:  false
    Controller:            false
    Kind:                  Namespace
    Name:                  fleet-local
    UID:                   fe3aa9ca-5355-4263-a3ac-92711d59ccd8
  Resource Version:        7583
  UID:                     aee625c2-9a4b-47a3-8a7c-aa688265b52a
Spec:
  Default Namespace:  cattle-fleet-local-system
  Helm:
    Take Ownership:  true
  Ignore:
  Resources:
    Content:  apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cattle-fleet-local-system-fleet-agent-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cattle-fleet-local-system-fleet-agent-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cattle-fleet-local-system-fleet-agent-role
subjects:
- kind: ServiceAccount
  name: fleet-agent
  namespace: cattle-fleet-local-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-agent
  namespace: cattle-fleet-local-system

---
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: default
  namespace: cattle-fleet-local-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-agent
  namespace: cattle-fleet-local-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-agent
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fleet-agent
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: fleet.cattle.io/agent
                operator: In
                values:
                - "true"
            weight: 1
      containers:
      - command:
        - fleetagent
        env:
        - name: BUNDLEDEPLOYMENT_RECONCILER_WORKERS
          value: "50"
        - name: DRIFT_RECONCILER_WORKERS
          value: "50"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AGENT_SCOPE
          value: cattle-fleet-local-system
        - name: CHECKIN_INTERVAL
          value: 15m0s
        - name: CATTLE_ELECTION_LEASE_DURATION
          value: 30s
        - name: CATTLE_ELECTION_RETRY_PERIOD
          value: 10s
        - name: CATTLE_ELECTION_RENEW_DEADLINE
          value: 25s
        image: rancher/fleet-agent:v0.13.0-alpha.3
        imagePullPolicy: IfNotPresent
        name: fleet-agent
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /.kube
          name: kube
        - mountPath: /tmp
          name: tmp
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: fleet-agent
      tolerations:
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        operator: Equal
        value: "true"
      - effect: NoSchedule
        key: cattle.io/os
        operator: Equal
        value: linux
      volumes:
      - emptyDir: {}
        name: kube
      - emptyDir: {}
        name: tmp

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-allow-all
  namespace: cattle-fleet-local-system
spec:
  egress:
  - {}
  ingress:
  - {}
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

    Name:  agent.yaml
  Targets:
    Cluster Name:  local
    Cluster Selector:
      Match Expressions:
        Key:       fleet.cattle.io/non-managed-agent
        Operator:  DoesNotExist
    Ignore:
Status:
  Conditions:
    Last Update Time:  2025-06-10T09:48:11Z
    Message:           WaitApplied(1) [Cluster fleet-local/local]
    Status:            False
    Type:              Ready
  Display:
    Ready Clusters:     0/1
    State:              WaitApplied
  Max New:              50
  Max Unavailable:      1
  Observed Generation:  1
  Partitions:
    Count:            1
    Max Unavailable:  1
    Name:             All
    Summary:
      Desired Ready:  1
      Non Ready Resources:
        Bundle State:  WaitApplied
        Name:          fleet-local/local
      Ready:           0
      Wait Applied:    1
    Unavailable:       1
  resourcesSha256Sum:  00e2868590836e23b55c653f1f5df8794c8f51c3cb1b987c931d4a76921212bd
  Summary:
    Desired Ready:  1
    Non Ready Resources:
      Bundle State:  WaitApplied
      Name:          fleet-local/local
    Wait Applied:    1
  Unavailable:       1
Events:              <none>

```
