### ISSUE TITLE
Unable to create PVC using class from dashboard in yaml view

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#1458]
**Description of the bug**
Unable to create pvc from dashboard in yaml view. UI shows error ```{ "type": "error", "links": {}, "code": "MethodNotAllowed", "message": "the server does not allow this method on the requested resource", "status": 405 }```

**Steps to reproduce**
1. Set up an HA with 3 nodes.
2. Go to the local cluster explorer.
3. Deploy longhorn app.
4. Create a pvc from yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-simple-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
```

**Result**
<img width="1044" alt="Screen Shot 2020-09-27 at 8 35 26 PM" src="https://user-images.githubusercontent.com/60111667/94388158-07a85700-0101-11eb-8215-c35be30fe263.png">

**Additional info**
Same pvc, when created with kubectl command, is created successfully. 

**Environment Info**
The dashboard version - ec04f78
The setup info - HA setup with k3s v1.1.3
