### ISSUE TITLE
Statefulset is not coming up healthy if 'Create PVC' option is used for attaching storage while creating it.

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#1459]
**Description of the bug**
Statefulset is not coming up healthy if 'Create PVC' option is used for attaching storage while creating it.

**Steps to reproduce**
1. Set up an HA with 3 nodes.
2. Go to the local cluster explorer.
3. Deploy longhorn app.
3. Create a statefulset.
4. Select 'Create Persistent volume claim' option.
<img width="1058" alt="Screen Shot 2020-09-27 at 10 46 07 PM" src="https://user-images.githubusercontent.com/60111667/94394906-5101a200-0113-11eb-832a-283a2424656c.png">
5. Use a longhorn as a storage class.

**Result**
Pod doesn't get created.
The claim name is empty in the statefulset yaml.
```
spec:
      containers:
      - image: ubuntu
        imagePullPolicy: Always
        name: wk-state-6
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pvc-new-3
        persistentVolumeClaim:
          claimName: ""
```

**Environment Info**
The dashboard version - ec04f78
The setup info - HA setup with k3s v1.1.3
