### ISSUE TITLE
Toggling to 'Use an existing persistent volume' option is not working on the 'Create Persistent volume' screen.

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#1460]
**Description of the bug**
Toggling to 'Use an existing persistent volume' option is not working on the 'Create Persistent volume' screen.

**Steps to reproduce**
1. Set up an HA with 3 nodes.
2. Go to the local cluster explorer.
3. Deploy longhorn app.
4. Create a stateful set.
5. Select the 'Create Persistent volume claim' option.
<img width="1058" alt="Screen Shot 2020-09-27 at 10 46 07 PM" src="https://user-images.githubusercontent.com/60111667/94394906-5101a200-0113-11eb-832a-283a2424656c.png">
6. Select 'Use an existing persistent volume' option.

**Result**
The volume persistent claim field doesn't get highlighted.
<img width="1056" alt="Screen Shot 2020-09-27 at 11 07 43 PM" src="https://user-images.githubusercontent.com/60111667/94396237-5c0a0180-0116-11eb-8de5-1b6e77fde4b0.png">

**Environment Info**
The dashboard version - ec04f78
The setup info - HA setup with k3s v1.1.3

**Comment by khushboo-rancher** [comment]
Verified with the latest dashboard - master-head ```ec04f78```, the PVC created by using existing PV stuck in ```pending``` state.

There are below issues on selecting 'Use an existing PV'
1. The capacity doesn't get disabled which is not required now. With capacity 0, the form doesn't get saved.
2. The 'Persistent field' displays all PVs whereas it should show only ```Avaialable``` PVs.
3. The PVC created on giving some random capacity and selecting an ```Available``` PV. PVC stuck in pending state as it has ```storageclass``` set to ```longhorn```. The ```storageclass``` should be set to "" (empty).
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2020-09-29T23:25:26Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: pvc-test-volume-deploy-3
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "2"
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pv-volume-test-3
```
