### ISSUE TITLE
[BUG] etcd snapshot on S3 - Incorrect Age

### ISSUE THREAD

**Issue by metalshanked** [rancher/dashboard#14632]
**Rancher Server Setup**
- Rancher version: 2.11.1
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.32
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**
When a cluster is recreated, the snapshots tab for the cluster lists the existing S3 snapshots. 
However, the "Age" column is misleading and does not reflect the "created at" for the snapshot.
It instead shows the age of the cluster creation 

**Screenshots**

![Image](https://github.com/user-attachments/assets/3997d39f-0606-477b-aeec-8b54b8f1f223)

**Comment by snasovich** [comment]
@metalshanked , thank you for your report.

After looking into it, UI is using value of `metadata.creationTimestamp` to calculate "Age" which is actual `etcdsnapshot.rke.cattle.io` CR creation time. Since changes in v2.11.0 we now also properly populate `snapshotFile.createdAt` field and that refers to the time snapshot was actually taken, e.g.
```yaml
apiVersion: rke.cattle.io/vl
kind: ETCDSnapshot
metadata:
  ...
  creationTimestamp: '2025-06-27T03:03:28Z'|
...
snapshotFile:
  createdAt: '2025-06-26T15:00:05Z'
...
```

Transferring this issue to https://github.com/rancher/dashboard

FYI @gaktive / @nwmac , would be great to have this improved in v2.11.x+ - potentially add a new column like "Snapshot Timestamp" and keep "Age" in as is to avoid any potential confusion stemming from change of behavior.
