### ISSUE TITLE
 Ability to override the Global Registry Settings for charts by changing the values.yaml

### ISSUE THREAD

**Issue by sangeethah** [rancher/dashboard#1554]
https://github.com/rancher/dashboard/pull/1551

- There's 4 fields, systemDefaultRegistry and values.global.cattle.{clusterId, clusterName, systemDefaultRegistry}.
- On load (showing the yaml) they are dropped from the YAML if their value is the same as we'd normally set them (so they're not always shown to everyone).  If you set the value to something else it should be shown.
- On save (writing back to the server for create or edit) any of the 4 that do not have a value already are set with our value.  If you set one yourself, that value is preserved.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `cb9e8a105c1f`**

**Scenario#1**
- Set Global default registry to `reg1` and cluster level to `reg2`
- While deploying CIS v2 app, set this in the values.yaml

```
cattle:
        clusterId: c-bq9ds
        clusterName: custom-2
        systemDefaultRegistry: reg2
```
- CIS v2 app is seen deployed using images from reg2

**Scenario#2**
- Do not set Global default registry and set cluster level to `reg2`
- While deploying CIS v2 app, set this in the values.yaml

```
cattle:
        clusterId: c-bq9ds
        clusterName: custom-2
        systemDefaultRegistry: reg2
```
- CIS v2 app is seen deployed using images from reg2
