### ISSUE TITLE
rancher-monitoring GUI form does not generate the right configuration for grafana storage persistence

### ISSUE THREAD

**Issue by cortopy** [rancher/dashboard#1802]
## PROBLEM

When configuring persistence storage for Grafana using the GUI form for `rancher-monitoring`, the YAML generated includes the following:

```yaml
persistence:
    accessModes:
      - ReadWriteOnce
    storageClassName: longhorn
    size: 100Gi
    subPath: null
    type: statefulset
```

However, that doesn't generate any persistence in the grafana chart. The default Deployment with no storage is provisioned instead.

## SOLUTION

This is because there is one option missing. The configuration should include the line `enabled: true`, like:

```yaml
persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    storageClassName: longhorn-replicas-1
    size: 1Gi
    subPath: null
    type: statefulset
```
