### ISSUE TITLE
Validation error when adding and removing environment variables during deployment creation

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#1808]
Validation error when adding and removing environment variables during deployment creation.

Tested in: `master` and `2.5.2-rc9`.

# Steps to reproduce
* Create a deployment as form
* Add an environment variable
* Add an environment variable from resource

![Bildschirmfoto 2020-11-10 um 14 53 51](https://user-images.githubusercontent.com/243056/98683406-49b1f300-2365-11eb-84f3-c91fdff9cd59.png)

* Remove both entries
* Create the deployment

# What happens

The UI displays a validation error for environments variables, even though non are present in the form.

![Bildschirmfoto 2020-11-10 um 14 58 32](https://user-images.githubusercontent.com/243056/98683366-3bfc6d80-2365-11eb-9a1a-6c3206285653.png)

```
Deployment.apps "test" is invalid: spec.template.spec.containers[0].env[0].name: Required value
```

When clicking on "Edit as YAML", there is an empty environment variable entry in the YAML, which is not present in the form.

```
...
    spec:
      containers:
        - name: test
          imagePullPolicy: Always
          image: nginx
          env:
            - name: ''
              value: ''
              _display:
                binary: false
                withBreaks: ''
                isLarge: false
                byteSize: 0
```
