### ISSUE TITLE
Missing weight field in pod form when configuring preferred affinities

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#1815]
The forms for configuring preferred affinities and anti-affinities is missing the `weight` field.

![Bildschirmfoto 2020-11-10 um 15 33 13](https://user-images.githubusercontent.com/243056/98687654-42d9af00-236a-11eb-8bf6-a35962ac5b0f.png)

> weight associated with matching the corresponding podAffinityTerm, in the range 1-100.

The UI seems to automatically set a `weight` of `1`:

```
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: pref
                      operator: In
                      values:
                        - val
                topologyKey: preftopkey
```
