### ISSUE TITLE
[CIS v2] Need UI to be able to add AlertRule to a ClusterScan

### ISSUE THREAD

**Issue by prachidamle** [rancher/dashboard#1828]
Alerting will be enabled as part of the CIS rancher-cis-benchmark chart.

Two types of alert are supported:
- Alert when scan completes
- Alert when scan has failures

**New fields added to the ClusterScan CR Spec:**
// AlertRule 
ScanAlertRule *ClusterScanAlertRule `json:"scanAlertRule,omitempty"`

type ClusterScanAlertRule struct {
	AlertOnComplete bool `json:"alertOnComplete,omitempty"`
	AlertOnFailure  bool `json:"alertOnFailure,omitempty"`
}

```
apiVersion: cis.cattle.io/v1
kind: ClusterScan
metadata:
  generateName: scan-
  generation: 1
  name: scan-r6tmb
spec:
  cronSchedule: '*/5 * * * *'
  scanAlertRule:
    alertOnComplete: true
    alertOnFailure: true
  scanProfileName: rke-profile-hardened
```

UI Options:
1) Create ClusterScan Form should provide options to add Alert options:
- checkboxes to choose alertOnComplete and/or alertOnFailure **[These will be off by default]**
- If user tries to select them, check if the alerting CRD is present, if not show a warning on UI to users indicating that alerts may not work.
- Need to show some informational tooltip to indicate alert-notifiers need to be setup separately.

@deniseschannon @vincent99 does this sound ok: "To receive alerts, please make sure Rancher Monitoring and Alerting app is installed and the Receivers and Routes have been configured to send out alerts. Further details can be found here https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.5/configuration/#alertmanager-config"

**Comment by prachidamle** [comment]
@mantis-toboggan-md Should this be moved back to Next-up to include the latest backend changes that we discussed on the feature channel?

- Alert options (AlertOnComplete and AlertOnFailure) will be available only for Scheduled scans
- So the ClusterScan CR is changed this way:
         ```
 clusterscan:            
            spec:
              scheduledScanConfig:
                cronSchedule:
                  nullable: true
                  type: string
                retentionCount:
                  type: integer
                scanAlertRule:
                  nullable: true
                  properties:
                    alertOnComplete:
                      type: boolean
                    alertOnFailure:
                      type: boolean
                  type: object
              type: object
```
- So on the UI, we need to show the Alert options to the user only when a "scheduling" scan is configured

- Also on Chart deployment form, following  are added for Alerts in Values.yaml - which will possibly go on to the deployment form:
alerts:
  ```
enabled: false
  severity: warning
  metricsPort: 8080
```
