### ISSUE TITLE
Pod command arguments with quotes are improperly broken up by space

### ISSUE THREAD

**Issue by ebauman** [rancher/dashboard#1832]
Rancher version: v2.5.2

Steps to reproduce:

1. Launch a Deployment using the Cluster Explorer
2. In the pod spec, override the command to `/bin/bash` and the arguments to `-c "sleep 3600"`
3. Launch the deployment
4. Observe the failure state of the pods.
5. Edit the deployment as YAML and observe the following:
```
...
    spec:
      containers:
      - args:
        - -c
        - '"sleep'
        - 3600"
```
