### ISSUE TITLE
Creating Ingress via Cluster Explorer's GUI fails

### ISSUE THREAD

**Issue by k-markov** [rancher/dashboard#1847]
The k8s API networking.k8s.io/v1 requires "pathType:" entry in "rules:", but there is no such field in the form and the ingress creation fails. The suggested YAML description also lacks such an entry. Also, according to the k8s docs, the "backend" should be described as:
```yaml
backend:
  service:
    name: 
    port:
      number: 
```
not like:
```yaml
backend:
  serviceName:
  servicePort:
```
