### ISSUE TITLE
[Logging v2] Add filter details to flows and clusterflows

### ISSUE THREAD

**Issue by nickgerace** [rancher/dashboard#1908]
The `logging-operator` uses [filters](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/) for both its [flows and clusterflows](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/crds/#flows-clusterflows). These can be added as a formal form, commented out YAML, etc.

## Concat
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/concat/
VARIABLE NAME | TYPE | REQUIRED | DEFAULT | DESCRIPTION
-- | -- | -- | -- | --
key | string | No | - | Specify field name in the record to parse. If you leave empty the Container Runtime default will be used.
separator | string | No | “\n” | The separator of lines.
n_lines | int | No | - | The number of lines. This is exclusive with multiline_start_regex.
multiline_start_regexp | string | No | - | The regexp to match beginning of multiline. This is exclusive with n_lines.
multiline_end_regexp | string | No | - | The regexp to match ending of multiline. This is exclusive with n_lines.
continuous_line_regexp | string | No | - | The regexp to match continuous lines. This is exclusive with n_lines.
stream_identity_key | string | No | - | The key to determine which stream an event belongs to.
flush_interval | int | No | - | The number of seconds after which the last received event log will be flushed. If specified 0, wait for next line forever.
timeout_label | string | No | - | The label name to handle events caused by timeout.
use_first_timestamp | bool | No | False | Use timestamp of first record when buffer is flushed.
partial_key | string | No | - | The field name that is the reference to concatenate records
partial_value | string | No | - | The value stored in the field specified by partial_key that represent partial log
keep_partial_key | bool | No | False | If true, keep partial_key in concatenated records
use_partial_metadata | string | No | - | Use partial metadata to concatenate multiple records
keep_partial_metadata | string | No | - | If true, keep partial metadata

## Dedot
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/dedot/
VARIABLE NAME | TYPE | REQUIRED | DEFAULT | DESCRIPTION
-- | -- | -- | -- | --
de_dot_nested | bool | No | false | Will cause the plugin to recurse through nested structures (hashes and arrays), and remove dots in those key-names too.
de_dot_separator | string | No | _ | Separator

## Exception Filter
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/detect_exceptions/
VARIABLE NAME | TYPE | REQUIRED | DEFAULT | DESCRIPTION
-- | -- | -- | -- | --
message | string | No | "” | The field which contains the raw message text in the input JSON data.
remove_tag_prefix | string | No | "” | The prefix to be removed from the input tag when outputting a record.
multiline_flush_interval | string | No | nil | The interval of flushing the buffer for multiline format.
languages | []string | No | [] | Programming languages for which to detect exceptions.
max_lines | int | No | 1000 | Maximum number of lines to flush (0 means no limit)
max_bytes | int | No | 0 | Maximum number of bytes to flush (0 means no limit)
stream | string | No | "” | Separate log streams by this field in the input JSON data.

## Geo IP
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/geoip/
VARIABLE NAME | TYPE | REQUIRED | DEFAULT | DESCRIPTION
-- | -- | -- | -- | --
geoip_lookup_keys | string | No | host | Specify one or more geoip lookup field which has ip address
geoip_database | string | No | - | Specify optional geoip database (using bundled GeoLiteCity databse by default)
geoip_2_database | string | No | - | Specify optional geoip2 database (using bundled GeoLite2-City.mmdb by default)
backend_library | string | No | - | Specify backend library (geoip2_c, geoip, geoip2_compat)
skip_adding_null_record | bool | No | true | To avoid get stacktrace error with [null, null] array for elasticsearch.
records | [][Record](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/geoip/) | No | - | Records are represented as maps: key: value

## Grep
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/grep/
VARIABLE NAME | TYPE | REQUIRED | DEFAULT | DESCRIPTION
-- | -- | -- | -- | --
regexp | [][RegexpSection](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/grep/) | No | - | Regexp Directive
exclude | [][ExcludeSection](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/grep/) | No | - | Exclude Directive
or | [][OrSection](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/grep/) | No | - | Or Directive
and | [][AndSection](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/grep/) | No | - | And Directive

## Parser
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/parser/
VARIABLE NAME | TYPE | REQUIRED | DEFAULT | DESCRIPTION
-- | -- | -- | -- | --
key_name | string | No | - | Specify field name in the record to parse. If you leave empty the Container Runtime default will be used.
reserve_time | bool | No | - | Keep original event time in parsed result.
reserve_data | bool | No | - | Keep original key-value pair in parsed result.
remove_key_name_field | bool | No | - | Remove key_name field when parsing is succeeded
replace_invalid_sequence | bool | No | - | If true, invalid string is replaced with safe characters and re-parse it.
inject_key_prefix | string | No | - | Store parsed values with specified key name prefix.
hash_value_field | string | No | - | Store parsed values as a hash value in a field.
emit_invalid_record_to_error | bool | No | - | Emit invalid record to @ERROR label. Invalid cases are: key not exist, format is not matched, unexpected error
parse | [ParseSection](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/parser/) | No | - | Parse Section
parsers | [][ParseSection](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/parser/) | No | - | Deprecated, use parse instead

## Prometheus
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/prometheus/
VARIABLE NAME | TYPE | REQUIRED | DEFAULT | DESCRIPTION
-- | -- | -- | -- | --
metrics | [][MetricSection](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/prometheus/) | No | - | Metrics Section
labels | Label | No | - | -

## Record Modifier
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/record_modifier/
VARIABLE NAME | TYPE | REQUIRED | DEFAULT | DESCRIPTION
-- | -- | -- | -- | --
prepare_value | string | No | - | Prepare values for filtering in configure phase. Prepared values can be used in . You can write any ruby code.
char_encoding | string | No | - | Fluentd including some plugins treats logs as a BINARY by default to forward. To overide that, use a target encoding or a from:to encoding here.
remove_keys | string | No | - | A comma-delimited list of keys to delete
whitelist_keys | string | No | - | This is exclusive with remove_keys
replaces | [][Replace](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/record_modifier/) | No | - | Replace specific value for keys
records | [][Record](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/record_modifier/) | No | - | Add records docs at: https://github.com/repeatedly/fluent-plugin-record-modifierRecords are represented as maps: key: value

## Record Transformer
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/record_transformer/
VARIABLE NAME | TYPE | REQUIRED | DEFAULT | DESCRIPTION
-- | -- | -- | -- | --
remove_keys | string | No | - | A comma-delimited list of keys to delete
keep_keys | string | No | - | A comma-delimited list of keys to keep.
renew_record | bool | No | false | Create new Hash to transform incoming data
renew_time_key | string | No | - | Specify field name of the record to overwrite the time of events. Its value must be unix time.
enable_ruby | bool | No | false | When set to true, the full Ruby syntax is enabled in the ${…} expression.
auto_typecast | bool | No | true | Use original value type.
records | [][Record](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/record_transformer/) | No | - | Add records docs at: https://docs.fluentd.org/filter/record_transformerRecords are represented as maps: key: value

## StdOut
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/stdout/
VARIABLE NAME | TYPE | REQUIRED | DEFAULT | DESCRIPTION
-- | -- | -- | -- | --
output_type | string | No | - | This is the option of stdout format.

## SumoLogic
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/sumologic/
VARIABLE NAME | TYPE | REQUIRED | DEFAULT | DESCRIPTION
-- | -- | -- | -- | --
source_category | string | No | “%{namespace}/%{pod_name}” | Source Category
source_category_replace_dash | string | No | “/” | Source Category Replace Dash
source_category_prefix | string | No | kubernetes/ | Source Category Prefix
source_name | string | No | “%{namespace}.%{pod}.%{container}” | Source Name
log_format | string | No | json | Log Format
source_host | string | No | "” | Source Host
exclude_container_regex | string | No | "” | Exclude Container Regex
exclude_facility_regex | string | No | "” | Exclude Facility Regex
exclude_host_regex | string | No | "” | Exclude Host Regex
exclude_namespace_regex | string | No | "” | Exclude Namespace Regex
exclude_pod_regex | string | No | "” | Exclude Pod Regex
exclude_priority_regex | string | No | "” | Exclude Priority Regex
exclude_unit_regex | string | No | "” | Exclude Unit Regex
tracing_format | bool | No | false | Tracing Format
tracing_namespace | string | No | “namespace” | Tracing Namespace
tracing_pod | string | No | “pod” | Tracing Pod
tracing_pod_id | string | No | “pod_id” | Tracing Pod ID
tracing_container_name | string | No | “container_name” | Tracing Container Name
tracing_host | string | No | “hostname” | Tracing Host
tracing_label_prefix | string | No | “pod_label_” | Tracing Label Prefix
tracing_annotation_prefix | string | No | “pod_annotation_” | Tracing Annotation Prefix
source_host_key_name | string | No | “_sourceHost” | Source HostKey Name
source_category_key_name | string | No | “_sourceCategory” | Source CategoryKey Name
source_name_key_name | string | No | “_sourceName” | Source NameKey Name
collector_key_name | string | No | “_collector” | CollectorKey Name
collector_value | string | No | “undefined” | Collector Value

## Tag Normaliser
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/tagnormaliser/
VARIABLE NAME | TYPE | REQUIRED | DEFAULT | DESCRIPTION
-- | -- | -- | -- | --
format | string | No | ${namespace_name}.${pod_name}.${container_name} | Re-Tag log messages info at github

## Throttle
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/throttle/
VARIABLE NAME | TYPE | REQUIRED | DEFAULT | DESCRIPTION
-- | -- | -- | -- | --
group_key | string | No | kubernetes.container_name | Used to group logs. Groups are rate limited independently
group_bucket_period_s | int | No | 60 | This is the period of of time over which group_bucket_limit applies
group_bucket_limit | int | No | 6000 | Maximum number logs allowed per groups over the period of group_bucket_period_s
group_drop_logs | bool | No | true | When a group reaches its limit, logs will be dropped from further processing if this value is true
group_reset_rate_s | int | No | group_bucket_limit/group_bucket_period_s | After a group has exceeded its bucket limit, logs are dropped until the rate per second falls below or equal to group_reset_rate_s.
group_warning_delay_s | int | No | 10 seconds | When a group reaches its limit and as long as it is not reset, a warning message with the current log rate of the group is emitted repeatedly. This is the delay between every repetition.

**Comment by vincent99** [comment]
To be clear I was just talking about populating showing the possible fields under each filter as commented out yaml keys (instead of just the top level as is shown now), not turning all of these into first-class forms...

**Comment by nickgerace** [comment]
@vincent99 Is there is a way I can format this issue to help you do that? Perhaps remove some fluff?

**Comment by vincent99** [comment]
No the data is fine, we can pull the keys out of there. Just trying to clarify that the result should be better YAML than what's shown there now, not forms for all this (at least for now).

**Comment by nickgerace** [comment]
New title and description reflects the goal for better YAML.

**Comment by deniseschannon** [comment]
@codyrancher Can you describe how this was implemented?

**Comment by codyrancher** [comment]
@deniseschannon this wasn't implemented. I think this is the first time I'm seeing it.

**Comment by vincent99** [comment]
@codyrancher You added the filter types so that the full structure would show up in the YAML.  https://github.com/rancher/dashboard/commit/68310a485ac0dcdc3aab624fda3e33d6e87175a6

**Comment by codyrancher** [comment]
@vincent99 you're right. Sorry. I completely spaced.

**Comment by izaac** [comment]
Rancher version `v2.5.4-rc5`
Rancher version `master-head (12/16/2020)` _495f7a1_

All the YAML keys/objects from the referenced docs are included the create Flows/ClusterFlow UI forms in the Filter UI component as a commented YAML.
I created and edited a Flow and a ClusterFlow using the `tag_normaliser` filter from this filter UI component to check this was working. The logs were flowing to the configured Output/ClusterOutput.


This is the preview of the sample YAML shown in the UI where it's shown as commented.
```yaml
- concat:
   key: string
   separator: string
   n_lines: int
   multiline_start_regexp: string
   multiline_end_regexp: string
   continuous_line_regexp: string
   stream_identity_key: string
   flush_interval: int
   timeout_label: string
   use_first_timestamp: boolean
   partial_key: string
   partial_value: string
   keep_partial_key: boolean
   use_partial_metadata: string
   keep_partial_metadata: string
  dedot:
    de_dot_nested: boolean
    de_dot_separator: string
  detectExceptions:
    message: string
    remove_tag_prefix: string
    multiline_flush_interval: string
    languages:
      - string
    max_lines: int
    max_bytes: int
    stream: string
  geoip:
    geoip_lookup_keys: string
    geoip_database: string
    geoip_2_database: string
    backend_library: string
    skip_adding_null_record: boolean
    records:
      - key: value
  grep:
    regexp:
      - key: string
        pattern: string
    exclude:
      - key: string
        pattern: string
    or:
      - regexp:
          - key: string
            pattern: string
        exclude:
          - key: string
            pattern: string
    and:
      - regexp:
          - key: string
            pattern: string
        exclude:
          - key: string
            pattern: string
  parser:
    key_name: string
    reserve_time: boolean
    reserve_data: boolean
    remove_key_name_field: boolean
    replace_invalid_sequence: boolean
    inject_key_prefix: string
    hash_value_field: string
    emit_invalid_record_to_error: boolean
    parse: ParseSection
    parsers:
      - type: string
        expression: string
        time_key: string
        null_value_pattern: string
        null_empty_string: boolean
        estimate_current_event: boolean
        keep_time_key: boolean
        types: string
        time_format: string
        time_type: string
        local_time: boolean
        utc: boolean
        timezone: string
        format: string
        format_firstline: string
        delimiter: string
        delimiter_pattern: string
        label_delimiter: string
        multiline: arrray[string]
        patterns:
          - type: string
            expression: string
            time_key: string
            null_value_pattern: string
            null_empty_string: boolean
            estimate_current_event: boolean
            keep_time_key: boolean
            types: string
            time_format: string
            time_type: string
            local_time: boolean
            utc: boolean
            timezone: string
            format: string
        tracing_annotation_prefix: string
        source_host_key_name: string
        source_category_key_name: string
        source_name_key_name: string
        collector_key_name: string
        collector_value: string
  prometheus:
    metrics:
      - name: string
        type: string
        desc: string
        key: string
        buckets: string
        labels:
          key: value
    labels: Label
  record_modifier:
    prepare_value: string
    char_encoding: string
    remove_keys: string
    whitelist_keys: string
    replaces:
      - key: string
        expression: string
        replace: string
    records:
      - key: value
  record_transformer:
    remove_keys: string
    keep_keys: string
    renew_record: boolean
    renew_time_key: string
    enable_ruby: boolean
    auto_typecast: boolean
    records:
      - key: value
  stdout:
    output_type: string
  sumologic:
    source_category: string
    source_category_replace_dash: string
    source_category_prefix: string
    source_name: string
    log_format: string
    source_host: string
    exclude_container_regex: string
    exclude_facility_regex: string
    exclude_host_regex: string
    exclude_namespace_regex: string
    exclude_pod_regex: string
    exclude_priority_regex: string
    exclude_unit_regex: string
    tracing_format: boolean
    tracing_namespace: string
    tracing_pod: string
    tracing_pod_id: string
    tracing_container_name: string
    tracing_host: string
    tracing_label_prefix: string
    tracing_annotation_prefix: string
    source_host_key_name: string
    source_category_key_name: string
    source_name_key_name: string
    collector_key_name: string
    collector_value: string
  tag_normaliser:
    format: string
  throttle:
    group_key: string
    group_bucket_period_s: int
    group_bucket_limit: int
    group_drop_logs: boolean
    group_reset_rate_s: int
    group_warning_delay_s: int
    exclude_container_regex: string
    exclude_facility_regex: string
    exclude_host_regex: string
    exclude_namespace_regex: string
    exclude_pod_regex: string
    exclude_priority_regex: string
    exclude_unit_regex: string
    tracing_format: boolean
    tracing_namespace: string
    tracing_pod: string
    tracing_pod_id: string
    tracing_container_name: string
    tracing_host: string
    tracing_label_prefix: string
    tracing_annotation_prefix: string
    source_host_key_name: string
    source_category_key_name: string
    source_name_key_name: string
    collector_key_name: string
    collector_value: string
```
