### ISSUE TITLE
Gatekeeper Enforcement Action always show deny ? 

### ISSUE THREAD

**Issue by snahelou** [rancher/dashboard#1925]
Hello 

I'm not frontend developer but it seems that the Gatekeeper integration show the wrong value for Enforcement Action: 

![image](https://user-images.githubusercontent.com/528345/100441723-38781e80-30a7-11eb-89c8-82d288174431.png)

![image](https://user-images.githubusercontent.com/528345/100441884-6eb59e00-30a7-11eb-9928-b753800b1a68.png)

Source location: https://github.com/rancher/dashboard/blob/0f4d57f07b9d41391c13eabd0c21d24c1dcfd1b6/edit/constraints.gatekeeper.sh.constraint/index.vue#L265 

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a policy with enforcement to dryrun, and ensure that the UI show the right value. 

```
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: Deprecation
metadata:
  name: ensure-no-deprecation
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: ["*"]
        kinds: ["*"]
```

**Result:**
The UI must show dryrun. 
**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.2
- Installation option (single install/HA): Single install K3S
