### ISSUE TITLE
Cluster member with CIS admin role is NOT able to list clusterscan profiles while creating a scan CR

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2021]
**On 2.5-head - commit- `395b4fe77`**

- As an admin deploy CIS v2, create a scan CR
- Create a user - `user-1` with cis-admin roles using

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterrolebinding-new
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cis-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: u-pglzp
```
- Login as user-1 --> Dashboard --> CIS benchmarks
- Create Scan CR
- Cluster member with CIS admin role is NOT able to list clusterscan profiles
<img width="1642" alt="Screen Shot 2020-12-08 at 5 01 10 AM" src="https://user-images.githubusercontent.com/26032343/101489709-2d7a8500-3916-11eb-92a3-dd2a2879abad.png">

**Comment by mantis-toboggan-md** [comment]
I updated this page so the can create scans, but pre-populating the profile dropdown doesn't work because the cis-admin role doesn't have permission to see the default-clusterscanprofiles configmap.

**Comment by sowmyav27** [comment]
@prachidamle should users with cis-admin roles have access to default-clusterscanprofiles configmaps ?

**Comment by prachidamle** [comment]
yes @sowmyav27 cis-admin should have access to default-clusterscanprofiles configmaps

**Comment by sowmyav27** [comment]
Waiting for [this](https://github.com/rancher/cis-operator/issues/71) issue to be fixed

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `e2295c6 ` using cis v2 app v1.0.3**

```
cisoperator:
    repository: rancher/cis-operator
    tag: v1.0.3-rc4
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.2-rc4
```

- As an admin deploy CIS v2, create a scan CR
- Create a user - user-1 with cis-admin roles using add the user as a cluster member of the cluster
- Login as user-1 --> Dashboard --> CIS benchmarks
- Create Scan CR
- Cluster member with CIS admin role is able to list clusterscan profiles and create scan CRs
