### ISSUE TITLE
rke-cis-1.6-permissive scan profile available while creating a scan CR

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2079]
**On 2.5-head - commit id: `baf4867c`**

- Deploy a 1.15.12-rancher2-7 cluster (k8s through cluster.yml)
- Install CIS v2 on the cluster.
- Create scan
- Default rke-cis-1.6-permissive scan profile available

<img width="450" alt="Screen Shot 2020-12-14 at 1 15 07 PM" src="https://user-images.githubusercontent.com/26032343/102136589-6e8b0180-3e0e-11eb-9fb2-d371641c6bf9.png">

- Deploy scan
- The scan errors out with error `Error validating ClusterScanProfile rke-profile-permissive-1.6, error: Kubernetes version mismatch, ClusterScanProfile rke-profile-permissive-1.6 is not valid for this cluster's K8s version v1.15.12`

**Expected:**
Only applicable profiles for k8s version should be available while deploying scan CRs.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `e2295c6 ` using cis v2 app v1.0.3**

```
cisoperator:
    repository: rancher/cis-operator
    tag: v1.0.3-rc4
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.2-rc4
```

- Deploy a 1.15.12-rancher2-7 cluster (k8s through cluster.yml)
- Install CIS v2 on the cluster.
- Create scan
- Default rke-cis-1.6-permissive scan profile is NOT available
<img width="812" alt="Screen Shot 2020-12-16 at 7 16 07 AM" src="https://user-images.githubusercontent.com/26032343/102367589-cc365f80-3f6e-11eb-8cad-5434c58be49f.png">
