### ISSUE TITLE
No default profile available when k8s 1.15

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2092]
**On 2.5-head - commit id: `e2295c6 ` using cis v2 app v1.0.3**

```
cisoperator:
    repository: rancher/cis-operator
    tag: v1.0.3-rc4
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.2-rc4
```
- Deploy a 1.15.12-rancher2-7 cluster (through cluster.yml) as a standard user.
- deploy CIS v2
- create scan
- No default profile is selected in the dropdown.

<img width="1162" alt="Screen Shot 2020-12-16 at 7 16 03 AM" src="https://user-images.githubusercontent.com/26032343/102367784-0142b200-3f6f-11eb-9e8e-6f5a019d1117.png">

**Comment by mantis-toboggan-md** [comment]
Two ways this dropdown ends up empty: 
1. the current user doesn't have permission to view the default profile configmap(e.g. a user with the cis-admin role)
2. The profile specified in the above configmap isn't valid for this cluster (wrong kubernetes version)

This PR rancher/dashboard#2109 addresses #2 by making the dropdown fallback to cis-1.5 or cis-1.6 profiles. #1 can't be addressed on the UI side.

**Comment by sowmyav27** [comment]
Logged issue - For #1 - https://github.com/rancher/cis-operator/issues/83

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `bb69b03 `**

```
cisoperator:
    repository: rancher/cis-operator
    tag: v1.0.3-rc5
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.2-rc5
```

- Deploy CIS v2 on a cluster. 
- Add a user `user1` with cis-admin role and as `cluster-member` of the cluster
- Login as `user1`
- Create a scan CR
- User with cis-admin role has no scan profile listed as default in dropdown while creating a scan

This doesn't work. Reopening the issue.

**Comment by prachidamle** [comment]
@mantis-toboggan-md The user with `cis-admin` role is able to get the `default-clusterscanprofiles` configmap in `cis-operator-system` namespace:
<img width="844" alt="Screen Shot 2020-12-21 at 12 39 04 PM" src="https://user-images.githubusercontent.com/1470602/102820179-adc6ce80-4389-11eb-9dbb-0246559825b8.png">

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `48254f944 ` and ui-dashbaord-index pointing to: `releases.rancher.com/dashboard/release-2.5.4`**

```
cisoperator:
    repository: rancher/cis-operator
    tag: v1.0.3-rc5
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.2-rc5
```

- Deploy CIS v2 on a cluster. 
- Add a user `user1` with cis-admin role and as `cluster-member` of the cluster
- Login as `user1`
- Create a scan CR
- User with cis-admin role does have a default value in the dropdown
