### ISSUE TITLE
Download yaml for service does not give valid k8s manifest

### ISSUE THREAD

**Issue by rancher-max** [rancher/dashboard#220]
Other areas (config, secret, pod, etc.) give the k8s manifest, but if I select Download YAML on a service, it gives only the spec plus links. Example:

```
app: domaintest
image: ibuildthecloud/demo:v3
imagePullPolicy: Always
links:
  remove: https://dashboard-rio-system.uo4yvo.on-rio.io/v1/rio.cattle.io.v1.services/default/domaintest-7xc5f
  rioupdate: https://dashboard-rio-system.uo4yvo.on-rio.io/v1/rio.cattle.io.v1.services/default/domaintest-7xc5f?riofile
  rioview: https://dashboard-rio-system.uo4yvo.on-rio.io/v1/rio.cattle.io.v1.services/default/domaintest-7xc5f?riofile
  self: https://dashboard-rio-system.uo4yvo.on-rio.io/v1/rio.cattle.io.v1.services/default/domaintest-7xc5f
  update: https://dashboard-rio-system.uo4yvo.on-rio.io/v1/rio.cattle.io.v1.services/default/domaintest-7xc5f
ports:
- "80"
rollout:
  pause: false
version: v0
weight: 10000
```
