### ISSUE TITLE
new auto-created NodePort services in 2.5.5 are not clickable

### ISSUE THREAD

**Issue by oskapt** [rancher/dashboard#2303]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

deploy a workload with a port exposed and have rancher create a nodeport service

**Result:**

the URL becomes something in the form of `https://rancher-training.cl.monach.us/[object Object]`

<img width="364" alt="image" src="https://user-images.githubusercontent.com/171292/106952696-31f1cd00-6710-11eb-86c3-61e3e84172a3.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.5
- Installation option (single install/HA): single / into k3s

**Comment by mantis-toboggan-md** [comment]
This should be fixed by this PR (merged): https://github.com/rancher/dashboard/pull/2293

**Comment by brendarearden** [comment]
Steps to recreate: 
1. Deployed single install rancher/rancher:v2.5.5
2. In the cluster explorer create an example deployment with exposed port (shown below)
3. Then create the a node port (shown below)
4. On service list page, click on the link in the Target column for the service
![Screen Shot 2021-02-22 at 2 42 34 PM](https://user-images.githubusercontent.com/19455540/108777025-6cd16e80-7520-11eb-9d24-32f96da174f7.png)
5. See url is:
![Screen Shot 2021-02-22 at 3 13 36 PM](https://user-images.githubusercontent.com/19455540/108777104-8a063d00-7520-11eb-9165-395cdde15a73.png)

Steps to Test:
1. Deployed single install rancher/rancher:v2.5.6-rc5
2. In the cluster explorer create an example deployment with exposed port (shown below)
3. Then create the a node port (shown below)
4. On the service list page, in the Target column, there is no clickable link taking you to the incorrect url:
![Screen Shot 2021-02-22 at 3 18 13 PM](https://user-images.githubusercontent.com/19455540/108777539-30524280-7521-11eb-964e-81f428120035.png)

===Example Yamls====
Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-50000
  namespace: default
spec:
  selector:
    matchLabels:
      app: metrics
      department: engineering
  replicas: 3
  template:
    metadata:
      labels:
        app: metrics
        department: engineering
    spec:
      containers:
      - name: hello
        image: "gcr.io/google-samples/hello-app:2.0"
        env:
        - name: "PORT"
          value: "50000"
```
Service:
```
apiVersion: v1
kind: Service
metadata:
  name: my-np-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: metrics
    department: engineering
  ports:
  - protocol: TCP
    port: 80
    targetPort: 50000
```
