### ISSUE TITLE
[Monitoring V2] Scope down permissions to view Monitoring Pane + Magic Links

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#2408]
Currently, the following permissions seem to be necessary to view the UI for Alertmanager, Prometheus, Grafana, etc. (example below is just Alertmanager):

```yaml
rules:
# Level 1: Ability to view the Alertmanager UI if you copy-paste a magic link sent by another user or alert
# This will be packaged in by default in the Monitoring chart and aggregated to all k8s users with view permissions
- apiGroups:
  - ""
  resourceNames:
  - http:rancher-monitoring-alertmanager:9093
  - https:rancher-monitoring-alertmanager:9093
  resources:
  - services/proxy
  verbs:
  - get
# Level 2: Ability to view the Monitoring Pane on Cluster Explorer
# Required due to https://github.com/rancher/dashboard/blob/6fa9190936449f8ab64be45a2eafd1bbbdd33dac/config/product/monitoring.js#L35, which should be removed now
- apiGroups:
  - monitoring.coreos.com
  resources:
  - podmonitors
  verbs:
  - get
# Level 3: Ability to click on buttons on Monitoring Pane to take you into Alertmanager / Grafana / Prometheus UIs
# Currently not possible due to the way we require the ability to parse through all the workload types to check if
# the deployments are up. This should be scoped down to a single get call
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  - replicasets
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
```

We should only require Level 1 permissions to be able to have a non-Project Member view the Monitoring-related UIs.
