### ISSUE TITLE
[Monitoring V2] Remove requirement to get all workload types to see Monitoring links

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#2470]
As described in Level 3 in https://github.com/rancher/dashboard/issues/2408, currently the following code requires users who want to view Magic Links from seeing anything except `Resource Unavailable` unless they have permissions to get all Workload types (e.g. ReplicationControllers, Deployments, DaemonSets, StatefulSets, ReplicaSets, Jobs, CronJobs):

https://github.com/rancher/dashboard/blob/90bf41dce335551da0c94e382c4915990f43d56e/pages/c/_cluster/monitoring/index.vue#L156-L169

This seems to happen because the above code throws a 404 on not being able to get or list any of these resources, which causes the following code that renders magic links to never be run:

https://github.com/rancher/dashboard/blob/90bf41dce335551da0c94e382c4915990f43d56e/pages/c/_cluster/monitoring/index.vue#L173-L205

The logic for rendering the Monitoring Pane needs to be modified such that even a Cluster Member with only the following permissions should be able to hover over the magic link and see if the resource is available:
```yaml
- apiGroups:
  - ""
  resources:
  - endpoints
 resourceNames:
  - rancher-monitoring-prometheus
  - rancher-monitoring-grafana
  - rancher-monitoring-alertmanager
  verbs:
  - get
```

Note: Even though they can see and click on the button, on click they should not be able to load any of the UIs unless they are bound to the roles introduced in https://github.com/rancher/charts/pull/1008.
