### ISSUE TITLE
Import YAML creates resources in local cluster instead of downstream cluster

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#2585]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Bring up a `v2.5.7` Rancher.
Create a downstream cluster.
From downstream cluster, navigate to cluster manager.
Import YAML
![Screen Shot 2021-03-30 at 1 06 13 PM](https://user-images.githubusercontent.com/57409052/113049645-bb45de80-9158-11eb-906e-48d796ed6d40.png)
I used the following YAML to create a deployment.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeployment
  labels:
    app: testworkload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
    spec:
      containers:
        - name: mysite
          image: sangeetha/mytestcontainer
          ports:
            - containerPort: 80
```
Navigate to `Deployments` in Cluster Manager

**Result:**
The deployment is not found. The resource is created in the local cluster instead of the downstream cluster.

**Other details that may be helpful:**
Relevant fix: https://github.com/rancher/rancher/pull/31836

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.5.7` This is also seen in Rancher `v2.5.6`
- Installation option (single install/HA): Single install
