### ISSUE TITLE
Expose `helmSecretName` for GitRepo in Fleet/Continuous Delivery UI

### ISSUE THREAD

**Issue by bmdepesa** [rancher/dashboard#2706]
rancher/rancher:v2.5.8-rc3

https://github.com/rancher/fleet/issues/120

If a helm repo requiring authentication or a custom CA is used in Fleet, `helmSecretName` must be set in the GitRepo:
```
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
  namespace: fleet-default
spec:
  branch: helmtest
  helmSecretName: helm-test
  repo: https://github.com/repo/fleet-examples
  paths:
  - single-cluster/helm
  targets:
    - clusterSelector: {}
```

Currently we can edit the GitRepo as yaml to add it manually, but it would be better if it could be exposed in the GitRepo creation/edit UI.
