### ISSUE TITLE
Deployment fields are ignored

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#2804]
**To reproduce:**

Create new deployment in dashboard UI
```
image: busybox
command entrypoint: /bin/sh
command: -c "sleep 60"
stdin: yes
tty: check
```

**Current result:**
Deployment is stack on Crashloopbackoff and deployment yaml does not contain command/args/stdin/tty section.

Tested on: 2.5.8-rc8

ember UI (works as expected):
```
      containers:
      - args:
        - -c
        - sleep 60
        command:
        - /bin/sh
        image: busybox
        imagePullPolicy: Always
        name: v1deploy
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
```

dashboard (fields ignored):
```
      containers:
      - image: busybox
        imagePullPolicy: Always
        name: container-0
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
```

browser payload:
```json
spec: {replicas: 1, template: {spec: {restartPolicy: "Always",…},…},…}
{
  "replicas": 1,
  "template": {
    "spec": {
      "restartPolicy": "Always",
      "containers": [
        {
          "imagePullPolicy": "Always",
          "name": "container-0",
          "_active": true,
          "volumeMounts": [],
          "image": "busybox"
        }
      ],
      "imagePullSecrets": [],
      "volumes": [],
      "affinity": {}
    },
    "metadata": {
      "labels": {
        "workload.user.cattle.io/workloadselector": "apps.deployment-default-mydeploy"
      }
    }
  },
  "selector": {
    "matchLabels": {
      "workload.user.cattle.io/workloadselector": "apps.deployment-default-mydeploy"
    }
  }
}
```
