### ISSUE TITLE
Cluster Provisioning v2: Advanced - Private Registry

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2970]
The issue is for testing the fields for RKE2 that were added a few months ago. There is no dedicated PR. Test private registries for RKE2 cluster to be used when deploying RKE2:

<img width="607" alt="Screen Shot 2021-08-04 at 12 19 14 PM" src="https://user-images.githubusercontent.com/11410997/128241849-5b74f22c-8cf4-47c3-a862-b5e4d0ae7afc.png">

Here is the comment from the duplicate (but backend only) issue that was originally tracking this: 

Unauthenticated (without username/password)
Authenticated (with username/password)
 - ~Using Amazon ECR (credential helper is typically built into docker so need to specifically test this use case)~
> Note: Amazon ECR Is still blocked from testing, and a new issue has been created to track it in rancher/rancher for when it's supported in RKE2/k3s. rancher/rancher#33920
 - Using Quay.io

https://rancher.com/docs/k3s/latest/en/installation/private-registry/

```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
    rkeConfig:
 
#    registries:
#      configs:
#        authConfigSecretName: string
#          insecureSkipVerify: boolean
#          tlsSecretName: string
#      mirrors:
#        endpoints:
#            - string
#          rewrites:
#            key: string
```

**Comment by deniseschannon** [comment]
Note: Amazon ECR Is still blocked from testing, and a new issue has been created to track it in rancher/rancher for when it's supported in RKE2/k3s. https://github.com/rancher/rancher/issues/33920

**Comment by davidnuzik** [comment]
@deniseschannon could I at least get a description of what testing requirements are roughly so I have something to work with? The issue body is empty. cc: @sowmyav27 

Additionally, is there a PR for this? Should have at least one linked unless the ask is just to test some existing functionality (I'm guessing in just RKE2).

**Comment by deniseschannon** [comment]
@davidnuzik The issue is testing the fields for RKE2 that were added months ago, which is why there is no dedicated PR. basically how to configure private registries for RKE2 cluster to be used when deploying RKE2:

<img width="607" alt="Screen Shot 2021-08-04 at 12 19 14 PM" src="https://user-images.githubusercontent.com/11410997/128241849-5b74f22c-8cf4-47c3-a862-b5e4d0ae7afc.png">


Here is the comment from the duplicate (but backend only) issue that was originally tracking it: 

Unauthenticated (without username/password)
Authenticated (with username/password)
 - Using Amazon ECR (credential helper is typically built into docker so need to specifically test this use case)
 - Using Quay.io

https://rancher.com/docs/k3s/latest/en/installation/private-registry/

```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
    rkeConfig:
 
#    registries:
#      configs:
#        authConfigSecretName: string
#          insecureSkipVerify: boolean
#          tlsSecretName: string
#      mirrors:
#        endpoints:
#            - string
#          rewrites:
#            key: string
```
