### ISSUE TITLE
Fix chart questions enum and default values

### ISSUE THREAD

**Issue by PennyScissors** [rancher/dashboard#3188]
Related issue: https://github.com/rancher/rancher/issues/32604

Currently blocking part of [this](https://github.com/rancher/charts/pull/1220) PR as the user won't be able to select the appropriate cluster type from the dropdown in order to configure the chart with the correct node selector label.

Problem:
1. The UI is not using the value of enum typed fields in a chart's questions file to override the corresponding value set in the chart's values file.
2. Questions with a default value (including enums, but not limited to) are not being set as default in the UI.

Example (Rancher v2.5.8): The question's file has "rke" as default clusterType value, and "default-host" as default vCenter.host, but the values.yaml has an empty string as default values for both. The UI doesn't set "rke" as the default, and regardless of which one you select, the chart will be deployed with `clusterType: ""`. As for the default vCenter.host, the UI doesn't set it to "default-host" so the chart is deployed with `vCenter.host: ""` as well.

Chart questions
```
questions:
  - variable: clusterType
    label: Cluster Type
    description: Select the type of the cluster where vSphere CPI will be deployed
    type: enum
    default: "rke"
    options:
      - "rke"
      - "rke2"
      - "other"
    group: Configuration

  - variable: vCenter.host
    label: vCenter Host
    description: IP address or FQDN of the vCenter
    default: "default-host"
    type: string
    required: true
    group: Configuration
```

Chart default values in values.yaml
```
clusterType: ""
vCenter:
  host: ""
```

Default values displayed for chart:
![image](https://user-images.githubusercontent.com/8951271/120708567-93cd0400-c470-11eb-982f-c1aeb40d7b50.png)

Select cluster type "rke"
![image](https://user-images.githubusercontent.com/8951271/120708749-d2fb5500-c470-11eb-89be-b6b4e559c31a.png)

default values ("rke" and "default-host"), not used in the deployment:
![image](https://user-images.githubusercontent.com/8951271/120708930-0dfd8880-c471-11eb-9ae5-387758129b37.png)
