### ISSUE TITLE
Constraint page is blank when one of the constraint is created without annotation.

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#383]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster, navigate to dashboard, enable OPA gatekeeper.
2. Create multiple constraints. Now create a  constraint without annotation using yaml.

**Result:**
Constraint page is blank and doesn't show any existing constraint too.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-2463-head- e651c7a81
- Installation option (single install/HA): Single

**Comment by khushboo-rancher** [comment]
Tested in latest dashboard UI, constraint created without annotation are visible on UI but after refreshing the page (https://github.com/rancher/dashboard/issues/371)

Steps:
1. Create a constraint with following yaml.
```
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedRepos
metadata:
  name: prod-repo-is-openpolicyagent
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "production"
  parameters:
    repos:
      - "only-this-repo"
```
2. Refresh the page, constraint is visible on UI.
