### ISSUE TITLE
[Logging] Cloudwatch output UI does not capture all required arguments

### ISSUE THREAD

**Issue by ebauman** [rancher/dashboard#3988]
When creating a [Cluster]Output for Cloudwatch, Rancher does not currently expose all the form options to minimally make the output functional. 

Missing are two string inputs, `log_group_name` and `log_stream_name`. Without these (minimum `log_group_name`, but while we're at it, let's add `log_stream_name`), the output does not function.

**Comment by ebauman** [comment]
<img width="1193" alt="Screen Shot 2021-08-24 at 8 28 11 AM" src="https://user-images.githubusercontent.com/5565738/130625268-e4d805e1-4c4e-43f0-9821-ef015eec6311.png">

Output form as it exists today. Would need to add two string fields, "Log Group Name" and "Log Stream Name"

**Comment by nwmac** [comment]
We should add a Configuration section below Access with two text fields - Log Group Name and Log Stream Name.

These should be wired to the cloudwatch config log_group_name and log_stream_name.

You can use edit as yaml to see where in the object structure these need to go.

We should verify that when entered, these values get wired in correctly (check with edit as yaml).

**Comment by catherineluse** [comment]
@nwmac Would a ticket need to be opened on the backend to make `log_group_name` a required field?

**Comment by izaac** [comment]
Rancher version `v2.6-head (09/22/2021)` _223ec88_

On this build I see the new fields added to the UI. If I edit them I ended up with the following fields filled in the YAML:

```yaml
  cloudwatch:
    aws_key_id:
      valueFrom:
        secretKeyRef:
          key: key
          name: izaackey
    aws_sec_key:
      valueFrom:
        secretKeyRef:
          key: secret
          name: izaacsecret
    log_group_name: rancher-izaac
    log_stream_name: rancher-izaac-stream
    region: us-east-2
```

Generated fluentbit.conf

```conf
<label @2da173fa9306e44bbc7e1f0f6f1b6d45>
  <match **>
    @type cloudwatch_logs
    @id clusterflow:cattle-logging-system:test1:clusteroutput:cattle-logging-system:test1
    aws_key_id <REDACTED>
    aws_sec_key <REDACTED>
    log_group_name rancher-izaac
    log_stream_name rancher-izaac-stream
    region us-east-2
    <buffer tag,time>
      @type file
      chunk_limit_size 8MB
      path /buffers/clusterflow:cattle-logging-system:test1:clusteroutput:cattle-logging-system:test1.*.buffer
      retry_forever true
      timekey 10m
      timekey_wait 10m
    </buffer>
  </match>
</label>
```


## `v2.6.0` UI
![Screen Shot 2021-09-22 at 1 30 55 PM](https://user-images.githubusercontent.com/27659/134417368-a9931fe9-a716-41d5-9ba6-49b1c2c62136.png)

## `v2.6-head` UI
![Screen Shot 2021-09-22 at 1 30 42 PM](https://user-images.githubusercontent.com/27659/134417371-b1cca27c-f732-4961-8c14-47f3af5ff14d.png)


Checked both ClusterOutput and Output.
