### ISSUE TITLE
"Kubernetes Version" dropdown to show the latest RKE2/k3s versions within each minor release line only

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#4127]
UI uses endpoints `{base-url}/v1-rke2-release/releases` and `{base-url}/v1-k3s-release/releases` to show versions available for selection in dropdown when picking version for cluster to provision with or upgrade to and displays any results that have `serverArgs` field defined.
![image](https://user-images.githubusercontent.com/85187633/132586009-614c5194-830e-4fb2-a19e-060684e81cc2.png)

As more versions are added to KDM, the list will grow. The ask is to only show the most recent version in a given minor release line, i.e. there should only be one choice from v1.21.x, v1.22.x etc. If there are multiple latest versions that differ by metadata only, the version with the highest metadata value should be chosen (lexicographic order). For example, if `v1.21.4+rke2r1`, `v1.22.0+rke2r1`, `v1.22.1+rke2r1`, `v1.22.1+rke2r2` are returned by backend (with `serverArgs` set), only `v1.21.4+rke2r1` and `v1.22.1+rke2r2` should be available. Note that technically metadata should not be used for semver sorting (https://semver.org/#spec-item-10), it's acceptable based on how RKE2 and k3s releases are versioned.

Note that pre-release versions should not be filtered out as they should not be added to KDM release branches and only to dev branches used for development/testing.

Also, when editing the cluster, the version the cluster is on should also be available, even if it's not the latest within the minor releases line.

**Comment by gaktive** [comment]
We have a similar but opposite request here: https://github.com/rancher/rancher/issues/25833

@deniseschannon does PM have a direction for us to go here?

**Comment by deniseschannon** [comment]
For now, let's limit to the single latest and PM will prioritize/put in a RFE if we want to figure out how to control/use old versions. 

A workaround to limit to older versions is to use your own data.json file for KDM and that would limit what you see in the k8s dropdown.

**Comment by gaktive** [comment]
@codyrancher can you look over the review?

**Comment by davidnuzik** [comment]
@deniseschannon @gaktive shouldn't this just be handled in KDM? Why are we programmatically overriding what is defined in KDM here?

**Comment by davidnuzik** [comment]
And sorry is this right? We show pre-releases always? Sorry -- am I confused here and/or missing something?
https://github.com/rancher/dashboard/pull/4154/files#diff-86509b810be85b5c3937cd85d401fc6416f8a0a0720cf51109404c1e9cad82d9R340

**Comment by deniseschannon** [comment]
@davidnuzik With the changes of what is being added in the channels.yaml in KDM where it will now have multiple versions of k8s for each minor release, we need to limit it. It's changing from how we used to handle KDM and RKE2/k3s where we only had 1 per version because of the support/introduction of what's been added for provisioning RKE2/k3s. Each version will need to be available as KDM drives what options and charts are associated per specific released version. 

It should always show the latest version in KDM regardless if it's a pre-release as we would have to update KDM to have the official released versions before bringing KDM from dev to release.

**Comment by snasovich** [comment]
@davidnuzik @deniseschannon , Dave is right about always showing pre-release, here is how I've put it in description with rationale of making it easier to test upgrades. Is it a bad idea?
> Note that pre-release versions should not be filtered out as they should not be added to KDM release branches and only to dev branches used for development/testing.

**Comment by deniseschannon** [comment]
There is no option to not show it as this is the only way to test changes with RKE2 integration for provisioning RKE2 clusters.

**Comment by davidnuzik** [comment]
I think I mistakenly applied qa blocked label, removing this and moving to working.

**Comment by davidnuzik** [comment]
**My checks PASSED**

About this change: As described in the issue, with this change if we have multiple major.minor.patch entries (e.g. various releases with revved semver metadata like +rke2r1, +rke2r2, etc) defined in KDM only the latest major.minor.patch+latest_metadata will show for k3s and rke2. An exception is made if the entry is a pre-release (like an RC) which makes sense, if we have one or more RC entries for QA in KDM, then they should ALL be shown. So, this only affects non-prereleases. This is fine by the way because we never publish pre-releases in an actual KDM release (non-dev branches).

I don't see why we would ever have multiple major.minor.patch in the same min/max spec in a KDM release branch, but perhaps there are edge use cases where we might need this in the future. If we did have such an edge use case then this change would indeed handle this so only the latest +metadata is shown with two major.minor.patch versions.

I had to make a custom KDM to test this properly (see steps below). As you review, take note that I specify serverArgs even for older versions - this isn't supported but it doesn't matter -- the point is that the Rancher UI will only pull these in if serverArgs are specified and show them in the drop down. With the change, we should only see the latest major.minor.patch+latest_metadata - so this funky custom KDM I made is used to prove this change works as expected. This KDM also goes a bit overboard but I wanted to test everything correctly and carefully here. Some release version entries aren't technically needed in my custom KDM. Also, some of these releases may not exist -- again does not matter this is just so we can check the logic in the UI and ensure the Kubernetes Version dropdown on the cluster creation page shows only what is filtered per the code.
 
**Reproduction Steps:**

Not required. Is a new enhancement.

-----
 
**Validation Environment:**

Rancher version: v2.6-head `a9e61c5` pulled at 9/24/21 ~2:20pm
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: rke2 and k3s
Downstream K8s version: various entries tested both release and pre-release (various KDM entries in my custom kdm)
 
**Validation steps:**

1a. Create a custom KDM (data.json) for testing this change. I forked KDM and created a branch that has the file I need to fit my needs to test this.
<details>
  <summary>My channels.yaml (K3S) looks like this (click to expand!)</summary>

```
releases:
  - version: v1.18.20+k3s1
    minChannelServerVersion: v2.6.0-alpha1
    maxChannelServerVersion: v2.6.99
    serverArgs: &serverArgs-v1
(I truncated any args here in this codeblock so this doesn't take so many lines here)
  - version: v1.18.20-rc1+k3s1
    minChannelServerVersion: v2.6.0-alpha1
    maxChannelServerVersion: v2.6.99
    serverArgs: &serverArgs-v1
(I truncated any args here in this codeblock so this doesn't take so many lines here)
  - version: v1.19.14+k3s1
    minChannelServerVersion: v2.6.0-alpha1
    maxChannelServerVersion: v2.6.99
    serverArgs: &serverArgs-v1
(I truncated any args here in this codeblock so this doesn't take so many lines here)
  - version: v1.19.14-rc1+k3s1
    minChannelServerVersion: v2.6.0-alpha1
    maxChannelServerVersion: v2.6.99
    serverArgs: &serverArgs-v1
(I truncated any args here in this codeblock so this doesn't take so many lines here)
  - version: v1.20.10+k3s1
    minChannelServerVersion: v2.6.0-alpha1
    maxChannelServerVersion: v2.6.99
    serverArgs: &serverArgs-v1
(I truncated any args here in this codeblock so this doesn't take so many lines here)
  - version: v1.20.10-rc1+k3s1
    minChannelServerVersion: v2.6.0-alpha1
    maxChannelServerVersion: v2.6.99
    serverArgs: &serverArgs-v1
(I truncated any args here in this codeblock so this doesn't take so many lines here)
  - version: v1.21.4+k3s1
    minChannelServerVersion: v2.6.0-alpha1
    maxChannelServerVersion: v2.6.99
    serverArgs: &serverArgs-v1
(I truncated any args here in this codeblock so this doesn't take so many lines here)
  - version: v1.21.4+k3s2
    minChannelServerVersion: v2.6.0-alpha1
    maxChannelServerVersion: v2.6.99
    serverArgs: &serverArgs-v1
(I truncated any args here in this codeblock so this doesn't take so many lines here)
  - version: v1.21.4-rc1+k3s1
    minChannelServerVersion: v2.6.0-alpha1
    maxChannelServerVersion: v2.6.99
    serverArgs: &serverArgs-v1
(I truncated any args here in this codeblock so this doesn't take so many lines here)
  - version: v1.21.4-rc1+k3s2
    minChannelServerVersion: v2.6.0-alpha1
    maxChannelServerVersion: v2.6.99
    serverArgs: &serverArgs-v1
(I truncated any args here in this codeblock so this doesn't take so many lines here)
```

</details>

<details>
  <summary>My channels-rke2.yaml (RKE2) looks like this (click to expand!)</summary>

```
releases:
  - version: v1.19.14+rke2r1
    minChannelServerVersion: v2.6.0-alpha1
    maxChannelServerVersion: v2.6.99
    serverArgs: &serverArgs-v1
(I truncated any args here in this codeblock so this doesn't take so many lines here)
  - version: v1.19.14-rc1+rke2r1
    minChannelServerVersion: v2.6.0-alpha1
    maxChannelServerVersion: v2.6.99
    serverArgs: &serverArgs-v1
(I truncated any args here in this codeblock so this doesn't take so many lines here)
  - version: v1.20.10+rke2r1
    minChannelServerVersion: v2.6.0-alpha1
    maxChannelServerVersion: v2.6.99
    serverArgs: &serverArgs-v1
(I truncated any args here in this codeblock so this doesn't take so many lines here)
  - version: v1.20.10-rc1+rke2r1
    minChannelServerVersion: v2.6.0-alpha1
    maxChannelServerVersion: v2.6.99
    serverArgs: &serverArgs-v1
(I truncated any args here in this codeblock so this doesn't take so many lines here)
  - version: v1.21.4+rke2r1
    minChannelServerVersion: v2.6.0-alpha1
    maxChannelServerVersion: v2.6.99
    serverArgs: &serverArgs-v1
(I truncated any args here in this codeblock so this doesn't take so many lines here)
  - version: v1.21.4+rke2r2
    minChannelServerVersion: v2.6.0-alpha1
    maxChannelServerVersion: v2.6.99
    serverArgs: &serverArgs-v1
(I truncated any args here in this codeblock so this doesn't take so many lines here)
  - version: v1.21.4-rc1+rke2r2
    minChannelServerVersion: v2.6.0-alpha1
    maxChannelServerVersion: v2.6.99
    serverArgs: &serverArgs-v2
(I truncated any args here in this codeblock so this doesn't take so many lines here)
  - version: v1.21.4-rc1+rke2r3
    minChannelServerVersion: v2.6.0-alpha1
    maxChannelServerVersion: v2.6.99
    serverArgs: &serverArgs-v2
(I truncated any args here in this codeblock so this doesn't take so many lines here)
  - version: v1.21.4-rc1+rke2r4
    minChannelServerVersion: v2.6.0-alpha1
    maxChannelServerVersion: v2.6.99
    serverArgs: &serverArgs-v2
(I truncated any args here in this codeblock so this doesn't take so many lines here)
```

</details>

All of the above has multiple major.minor versions but some also have multiple +metadata entries to test this issue.

1b. `go generate` then commit and push these changes up to my branch link here: https://github.com/davidnuzik/kontainer-driver-metadata/tree/4127-custom-kdm (note this may get deleted later at some point)

2. Launch rancher, Go to Global Settings > Advanced Settings and modify the `rke-metadata-config` entry so we can instead point to my custom KDM ([data.json](https://raw.githubusercontent.com/davidnuzik/kontainer-driver-metadata/4127-custom-kdm/data/data.json)). Change the internal to every 2 minutes so it updates quickly for me. Save.
![image](https://user-images.githubusercontent.com/45179589/134742351-221ffbe4-30a8-4782-aa91-503637145b80.png)

3. Attempt to create an RKE2/K3S cluster with a node driver. Confirm I only see the latest major.minor.patch entry under the Kubernetes Version dropdown EXCEPT for pre-releases, as expected. For example, we only show one v1.21.4+rke2XY entry even though KDM lists two and we only show one v1.21.4+k3sX entry as well (latest for both)
![image](https://user-images.githubusercontent.com/45179589/134747083-f1541448-b113-4572-a8a6-d6038a9e4843.png)
![image](https://user-images.githubusercontent.com/45179589/134747105-3a40d3dc-1ea1-40eb-93d7-5621297254b4.png)

4. Compare this to v2.6.0 (where this change does not exist). I spun up a 2.6.0 instance and just modified the `rke-metadata-config` to point to my custom KDM. Notice that as expected it shows any/all entries and does not filter for latest +metadata.

![image](https://user-images.githubusercontent.com/45179589/134747775-82401294-f43f-4616-89eb-b3887d13a614.png)
![image](https://user-images.githubusercontent.com/45179589/134747789-b6fa3a59-88a1-407d-86d5-efab9d0c8e49.png)
( ^ Note that screenshot is truncated doesn't show rest of entries for k3s, but you get the point, we used to show both released +metadata versions prior to this change).
