### ISSUE TITLE
Duplicate key in Edit as YAML

### ISSUE THREAD

**Issue by ryansann** [rancher/dashboard#4136]
**Setup**
- Rancher version: v2.6.0 / 2.6-head
- Browser type & version: Chrome 93.0

**Describe the bug**
When editing as YAML from a eeployment config, the UI adds a duplicate key in the YAML

**To Reproduce**
1. Create a simple deployment
2. Navigate to the deployment and select `Edit Config`
3. Once inside the form based editor, choose `Edit as YAML` at the bottom of the form
4. Note that saving will not work until duplicate key is removed

**Result**
Duplicate key is created as seen here:
```yaml
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
```
`type` occurs twice in the same object

**Expected Result**
Should be given valid YAML when switching from edit config to edit as yaml
