### ISSUE TITLE
Download as yaml option for OPA Gatekeeper doesn't work

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#451]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster, navigate to dashboard, enable gatekeeper.
2. Click download yaml from OPA Gatekeeper page.

**Result:**
No file gets downloaded.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4-2634-head- da170610a
- Installation option (single install/HA): Single

**Comment by codyrancher** [comment]
Reassigning to @westlywright as I only worked on the Violations section of this page.

**Comment by khushboo-rancher** [comment]
Verified on master branch of the UI on a 2.4 setup.

Download as yaml option is working. On clicking it it downloads the below yaml file.
```
---
replicas: 1
auditInterval: 300
constraintViolationsLimit: 20
auditFromCache: false
image:
  repository: rancher/opa-gatekeeper
  tag: v3.1.0-beta.7
  pullPolicy: IfNotPresent
nodeSelector: {"beta.kubernetes.io/os": "linux"}
tolerations: []
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
global:
  systemDefaultRegistry: ""
  kubectl:
    repository: rancher/istio-kubectl
    tag: 1.4.6
```
