### ISSUE TITLE
Unavailable node is seen Active in Cluster Management --> Machine Pools page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#4608]
**On 2.6-head commit id: `e322f8f`**

- Deploy an RKE1 cluster
- Power down one of the nodes in the cluster
- the Node in Cluster explorer --> nodes page shows Unavailable
- Machine pool is seen Active.
- Click on the node --> Node is seen Unavailable

**Expected**
Machine pool should not be in Active state

**Comment by snasovich** [comment]
This seems to be a backend issue as `Node` from `management.cattle.io/v3` has conditions that suggest the node is active, e.g.:
```yaml
  conditions:
  - lastUpdateTime: "2021-11-22T17:06:02Z"
    status: "True"
    type: Initialized
  - lastUpdateTime: "2021-11-22T17:08:47Z"
    status: "True"
    type: Provisioned
  - lastUpdateTime: "2021-11-22T17:08:47Z"
    status: "True"
    type: Saved
  - lastUpdateTime: "2021-11-22T17:15:14Z"
    message: registered with kubernetes
    status: "True"
    type: Registered
```

At the same time `Node` from `v1` indicates `Ready` as `Unknown`.
```yaml
  conditions:
  - lastHeartbeatTime: "2021-11-22T17:15:33Z"
    lastTransitionTime: "2021-11-22T17:15:33Z"
    message: Flannel is running on this node
    reason: FlannelIsUp
    status: "False"
    type: NetworkUnavailable
  - lastHeartbeatTime: "2021-11-22T17:15:45Z"
    lastTransitionTime: "2021-11-22T17:17:27Z"
    message: Kubelet stopped posting node status.
    reason: NodeStatusUnknown
    status: Unknown
    type: MemoryPressure
  - lastHeartbeatTime: "2021-11-22T17:15:45Z"
    lastTransitionTime: "2021-11-22T17:17:27Z"
    message: Kubelet stopped posting node status.
    reason: NodeStatusUnknown
    status: Unknown
    type: DiskPressure
  - lastHeartbeatTime: "2021-11-22T17:15:45Z"
    lastTransitionTime: "2021-11-22T17:17:27Z"
    message: Kubelet stopped posting node status.
    reason: NodeStatusUnknown
    status: Unknown
    type: PIDPressure
  - lastHeartbeatTime: "2021-11-22T17:15:45Z"
    lastTransitionTime: "2021-11-22T17:17:27Z"
    message: Kubelet stopped posting node status.
    reason: NodeStatusUnknown
    status: Unknown
    type: Ready
```

Looking into it a bit more and will transfer to rancher/rancher if it's indeed a backend issue.
