### ISSUE TITLE
Deployment securityContext part is missing on creation

### ISSUE THREAD

**Issue by sebastien-helbert** [rancher/dashboard#4815]
**Setup**
- Rancher version: 2.6.2
- Browser type & version: Google Chrome

**Describe the bug**
securityContext section is missing when created from new UI which prevents pods from starting when Pod Security Policy Support is enabled.

**To Reproduce**
Create a new workload of type Deployment from UI

**Result**

**Expected Result**

Add this section in yaml file like the old UI does :
```
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
```

It may be somewhat related to https://github.com/rancher/dashboard/issues/4238
