### ISSUE TITLE
Add shortcut to relevant Ingress(es) and Service(s) from the workload detail page

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4845]
Issue description:

The endpoint column in the workload overview links to the ingress-nginx service ip of the correlated controller or to one of the kubernetes nodes ip not the actual ingress URL in the hyperlink text.

Business impact:
Makes the UI a less reliable tool for their end-users and they have to jump through more hoops outside Rancher to get the same work done.

Troubleshooting steps:
Click endpoints on deployments in UI

Repro steps:

- Create deployment with ingress/endpoints
- Click the endpoint

Actual behavior:
Links to IP of the node or controller

Expected behavior:
Link to the actual mentioned endpoint

**Comment by catherineluse** [comment]
I believe this is the expected behavior because in Kubernetes, workloads aren't supposed to have any knowledge of DNS. There is an intentional decoupling of workloads, services and ingress because there's not necessarily a one-to-one correlation of endpoints to workloads in Kubernetes. The "endpoint" they see on the list of deployments is taken from the Pod spec and it should not have any reference to how you can access that workload from the outside world. For example in the below screenshot, the Longhorn UI is running on simply "80/HTTP" and that's correct.
![Screen Shot 2022-01-21 at 2 41 49 PM](https://user-images.githubusercontent.com/20599230/150604899-3fa787e2-60da-4f91-ae89-919f7da53b8a.png)

Then if you have an ingress pointing to a service that points to the Longhorn UI (for example, example.com/longhorn), you do get a working URL. That's also correct:
![Screen Shot 2022-01-21 at 2 47 23 PM](https://user-images.githubusercontent.com/20599230/150605575-9405219b-2f26-4f4f-8b02-43fa1d399ddc.png)

What they are requesting is reasonable, but I would say that you should get information through the Related Resources tab. If anything, you should be able to:

1. Go to the Deployments list and click a Deployment name
2. Click the Related Resources tab. It might be useful if that tab listed Services that direct traffic to this Deployment through selectors. Currently that's not how it works - it only lists items that refers to this Deployment by name.
3. Hypothetically, if the Service was listed, you could click that. Then click the Related Resources of the Service and click related Ingresses. But again, Ingresses aren't going to be in the Related Resources tab because Ingresses refer to Services based on selectors instead of by name.
4. Then you could click the ingress you want and get to the endpoint from there.

I would say that for the person who opened this ticket, they would be better off going to the Ingresses list and accessing their endpoints from there. Then if we really to be able to work backward to endpoints from workloads, we could open a separate ticket for enhancing the Related Resources tab to also show items that are related based on selectors, but that would be more complicated.

**Comment by gaktive** [comment]
Internal reference: SURE-3675. I'll provide this feedback and see what comes back.

**Comment by catherineluse** [comment]
Vince said this issue is an enhancement rather than a bug so I have opened a separate issue describing the enhancement https://github.com/rancher/dashboard/issues/4974

**Comment by catherineluse** [comment]
One option would be to make the displayed endpoint for a workload configurable as suggested here https://github.com/rancher/dashboard/issues/4707

**Comment by catherineluse** [comment]
Related or possibly duplicate issue https://github.com/rancher/dashboard/issues/4190

**Comment by catherineluse** [comment]
Neil removed the endpoint links in lists where there are a large number of workloads because it is expensive to get the endpoints for each workload. Today we discussed that the endpoints column is also misleading because users who are coming from an older version of Rancher expect the endpoint to be for an ingress, whereas in Rancher v2.6.x it's taken from the Pod spec. Any single endpoint could communicate an oversimplification of any Service(s) and/or Ingresses that are already set up. So we discussed that it would be better to put this information in the workload detail page where we can do it more justice.

**Comment by catherineluse** [comment]
# QA Template


## What was fixed, or what changes have occurred

In the workload detail page (this page is reused for Deployments, StatefulSets and ReplicaSets), the Services tab now lists all the Services that select Pods in the workload, while the Ingresses tab lists any Ingresses that would direct traffic to one of those Services.
 
## Areas or cases that should be tested

To test this PR, this is what I did. I tested it on a downstream RKE2 cluster on EC2 with the Amazon cloud provider enabled.

1. Created this example Deployment, taken from the upstream Kubernetes docs.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-example
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-world
        ports:
        - containerPort: 8080
```

2. Created a service exposing the Deployment. My Service YAML ended up looking like this:

```yaml
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.19.26
  clusterIPs:
  - 10.43.19.26
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31327
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: load-balancer-example
```
 
3. Created a basic Ingress with YAML like this:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["35.165.65.47"],"port":80,"protocol":"HTTP","serviceName":"default:my-service","ingressName":"default:test-ingress","hostname":"example.com","path":"/foo","allNodes":false}]'
  creationTimestamp: "2022-07-10T14:16:21Z"
  generation: 1
  name: test-ingress
  namespace: default
  resourceVersion: "199858"
  uid: 317155df-eef4-48cb-991a-b3ac0467bd53
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          service:
            name: my-service
            port:
              number: 8080
        path: /foo
        pathType: Prefix
```

4. In Cluster Explorer, went to the detail page for the `hello-world` Deployment.
5. Went to the **Services** tab and confirmed that the newly created Service is listed:
<img width="1100" alt="Screen Shot 2022-07-10 at 11 08 33 AM" src="https://user-images.githubusercontent.com/20599230/178157500-a7e1a060-a54a-4856-ac32-238905f98997.png">
6. Went to the **Ingresses** tab and confirmed that the newly created Ingress is listed:
<img width="1154" alt="Screen Shot 2022-07-10 at 11 08 26 AM" src="https://user-images.githubusercontent.com/20599230/178157529-10ba5552-5951-423d-8911-4d028686c5e6.png">
7. Confirmed that if the user does not have permission to see Services or Ingresses, it explains that it is empty due to lack of permissions:
<img width="1078" alt="Screen Shot 2022-07-10 at 11 08 04 AM" src="https://user-images.githubusercontent.com/20599230/178157563-997ccc1b-3d0e-485e-89e7-3e83f061913e.png">
<img width="1075" alt="Screen Shot 2022-07-10 at 11 07 30 AM" src="https://user-images.githubusercontent.com/20599230/178157565-e389a0f6-de63-4e73-8880-20281c459d4b.png">
8. Confirmed that if you do have permission but the list is genuinely empty, it explains that no resources were found:
<img width="1056" alt="Screen Shot 2022-07-10 at 10 36 47 AM" src="https://user-images.githubusercontent.com/20599230/178157589-370c8d3e-c6a5-46a7-8687-3831a1f94a09.png">
<img width="1097" alt="Screen Shot 2022-07-10 at 10 37 25 AM" src="https://user-images.githubusercontent.com/20599230/178157593-18b07697-be60-4511-b20f-fd523598f71c.png">

## What areas could experience regressions?
The changes were limited to tabs on this detail page. I expect the other tabs to work the same as they did before.
