### ISSUE TITLE
Error not displayed on the UI

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#5210]
**On 2.6-head commit id: `8c785a`**

- deploy a workload
- edit as Yaml
- add this entry under matchLabel `one:two`

```
selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-wk-2
      one: two
```
- Error seen on UI:
<img width="870" alt="Screen Shot 2022-02-24 at 2 18 58 PM" src="https://user-images.githubusercontent.com/26032343/155617234-09256d6d-741f-44d9-a939-f485062231e0.png">

- Error in Network tab: `{"type":"error","links":{},"code":"Invalid","message":"Deployment.apps \"wk-2\" is invalid: [spec.template.metadata.labels: Invalid value: map[string]string{\"workload.user.cattle.io/workloadselector\":\"apps.deployment-default-wk-2\"}: `selector` does not match template `labels`, spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{\"one\":\"two\", \"workload.user.cattle.io/workloadselector\":\"apps.deployment-default-wk-2\"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable]","status":422,"type":"error"}`

Expected:
Error seen in the Network tab --> API error, should be displayed on UI.
