### ISSUE TITLE
Duplicate Machine Pool Names are not caught when saving a v2prov cluster 

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/dashboard#5211]
**Setup**
- Rancher version: v2.6-head

While reviewing a Rancher [PR](https://github.com/rancher/rancher/pull/36614#discussion_r814420338) and testing functionality changes for the PR, we found a bug. The rancher backend doesn't allow duplicate machine pool names but the UI let's an end-user save a cluster config that contains duplicate machine pool names and then the cluster immediately goes into an error state.

The user should not be able to save the cluster config when it will immediately cause their cluster to enter an error state. The backend checks for the duplicate names and the UI needs to do the same. The machine pool isn't shown in the UI after saving but the configuration is present in both the form and yaml config options.

<img width="469" alt="image" src="https://user-images.githubusercontent.com/55704795/155641060-67fb2c0b-fcc6-4394-9726-6d690dd3a651.png">

<img width="521" alt="image" src="https://user-images.githubusercontent.com/55704795/155641135-2b7abb9a-8f77-4061-8421-54664ed67fff.png">

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/55704795/155641289-99702193-d3d5-4f49-9492-b269d14bba38.png">

```yml
    machinePools:
    - controlPlaneRole: true
      etcdRole: true
      machineConfigRef:
        kind: VmwarevsphereConfig
        name: nc-ross46-rke2-linux-4kmwq
      machineOS: linux
      name: rke2-linux
      quantity: 3
      unhealthyNodeTimeout: 0s
      workerRole: true
    - controlPlaneRole: false
      etcdRole: false
      labels: {}
      machineConfigRef:
        kind: VmwarevsphereConfig
        name: nc-ross46-rke2win-x9jlq
      machineOS: windows
      name: rke2win
      quantity: 1
      unhealthyNodeTimeout: 0m
      workerRole: true
    - controlPlaneRole: false
      etcdRole: false
      labels: {}
      machineConfigRef:
        kind: VmwarevsphereConfig
        name: nc-ross46-rke2-linux-drs7h
      name: rke2-linux
      quantity: 1
      unhealthyNodeTimeout: 0m
      workerRole: true
```
