### ISSUE TITLE
Config map view inconsistent for binary data

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5311]
Internal Ref: SURE-4099

For a config map with binary data, we correctly show the `data` and `binaryData` on the overview for the configmap.

For the config view, however, we may show some text values as binary is they contain UTF8 characters, even though they are valid strings to display as text.

The binary data length is also inconsistent between the two views

e.g. for this config map:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-test
  namespace: default
binaryData:
  test: VEVTVEVTVFRFU1Q=
data:
  blah: awdwad
  text: RÄNCHER
```

![image](https://user-images.githubusercontent.com/1955897/157077323-6ee6ba44-760a-4cb1-876d-53c088fe10c6.png)

Note: Size says 16 bytes which is the base64 encoded size, not the actual data size and `text` is displayed corrected here

![image](https://user-images.githubusercontent.com/1955897/157077271-2a41d673-9725-48fc-90a0-f4f982e0fb72.png)

`text` is not displayed, but the binary value `test` is. The length is correct
