### ISSUE TITLE
RKE1 Node Template cloud-config field has no set width and does not auto-wrap text input

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/dashboard#5414]
**Setup**
- Rancher version:

```console
Component | Version
Rancher | v2.6-d604b7e02ec8dfcb6c439ca8ed5500e1d1735717-head
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher80
```
- Browser type & version: Firefox 97.0.2 (64-bit)on MacOS Monterey

**Describe the bug**
The cloud-config field in RKE1 Node templates does not wrap text that is pasted in. This is an issue when an end-user (myself in this scenario) pastes in a lengthy (10k characters) base64 encoded bash script that's part of the cloud-config.

This is a regression in how the UI handles RKE1 node templates and leaves the end-user with a non-functional UI.

**To Reproduce**
- create node template
- paste in 10k characters on the `INSERT_10000_MANIACS_HERE` line below (which results in a valid cloud-config)

```yml
#cloud-config
write_files:
- encoding: b64
  content: |
    INSERT_10000_MANIACS_HERE
  owner: root:root
  path: /root/set-certs.sh
  permissions: '0755'
runcmd:
  - sh /root/set-certs.sh
```

**Result**

The cloud-config field does not wrap the 10k characters.

**Expected Result**
The UI should automatically wrap lines that are longer than the field's width.

**Screenshots**

I have a screen recording located in SUSE Confluence [here](https://confluence.suse.com/x/ZIIdOQ)

**Additional context**

This same functionality (using a 10k character-long single line in the cloud-config field) works as expected in v2 provisioning. It appears isolated to RKE1 node templates.
