### ISSUE TITLE
[Monitoring V2 UI, RKE2] ingressNginx.enabled is set instead of rke2IngressNginx.enabled

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#5490]
**Setup**
- Rancher version: 2.6-head (b7c9b89)
- Browser type & version: Brave [Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (x86_64)](https://brave.com/latest/)

**Describe the bug**

The wrong setting is enabled by default on the UI for an RKE2 cluster with Windows nodes. Not sure if this also impacts an RKE2 cluster without Windows nodes, but in both cases `rke2IngressNginx.enabled` should be set, not `ingressNginx.enabled`.

**To Reproduce**

- Spin up a Rancher 2.6-head and have a downstream RKE2 cluster with the latest version (I'm using `v1.22.7+rke2r2`)
- Go to Apps & Marketplace
- Go to Monitoring (from dev-v2.6)

**Result**

`ingressNginx.enabled` is auto-detected and set.

**Expected Result**

`rke2IngressNginx.enabled` should be auto-detected and set.

**Screenshots**

![Screen Shot 2022-03-23 at 3 42 06 PM](https://user-images.githubusercontent.com/13127443/159808161-9676b75f-5369-4e60-8b5e-d7ade4265edb.png)

**Additional context**

**Detailed Description**

**Context**

Related Issue: https://github.com/rancher/rancher/issues/35595

**Comment by aiyengar2** [comment]
This is also overridden on a Edit / Upgrade but **not** shown in the Compare Changes view...

**Comment by PennyScissors** [comment]
Validated in v2.6-head (6f9c19d), RKE2 1.22.7+rke2r2

PASS - Values after installing/upgrading monitoring in a cluster with Linux nodes only:
```yaml
global:
  cattle:
    window:
      enabled: false

rke2ControllerManager:
  enabled: true
rke2Etcd:
  enabled: true
rke2IngressNginx: 
  enabled: true
rke2Proxy:
  enabled: true
rke2Scheduler:
  enabled: true

rkeControllerManager:
  enabled: false
rkeEtcd:
  enabled: false
rkeIngressNginx:
  enabled: false
rkeProxy:
  enabled: false
rkeScheduler:
  enabled: false

ingressNginx:
  enabled: false
```

PASS - Values after installing/upgrading monitoring in a cluster with Linux and Windows nodes:
```yaml
global:
  cattle:
    window:
      enabled: true

rke2ControllerManager:
  enabled: true
rke2Etcd:
  enabled: true
rke2IngressNginx: 
  enabled: true
rke2Proxy:
  enabled: true
rke2Scheduler:
  enabled: true

rkeControllerManager:
  enabled: false
rkeEtcd:
  enabled: false
rkeIngressNginx:
  enabled: false
rkeProxy:
  enabled: false
rkeScheduler:
  enabled: false

ingressNginx:
  enabled: false
```
