### ISSUE TITLE
[Monitoring V2 UI, RKE2] global.cattle.windows.enabled not set for Monitoring in an RKE2 cluster with Windows nodes automatically

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#5491]
**Setup**
- Rancher version: 2.6-head (b7c9b89)
- Browser type & version: Brave [Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (x86_64)](https://brave.com/latest/)

**Describe the bug**

An RKE2 cluster with Windows nodes should set `global.cattle.windows.enabled` to true, currently that's not being set when it is detected at least 1 node exists with Windows OS.

**To Reproduce**

- Spin up a Rancher 2.6-head and have a downstream RKE2 cluster with the latest version (I'm using `v1.22.7+rke2r2`)
- Go to Apps & Marketplace
- Go to Monitoring (from dev-v2.6)

**Result**

nothing is set for Windows.

**Expected Result**

`global.cattle.windows.enabled` should be auto-detected and set.

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

Related Issue: https://github.com/rancher/rancher/issues/35595

**Comment by aiyengar2** [comment]
This is also overridden on a Edit / Upgrade but **not** shown in the Compare Changes view... that should not be the case.

**Comment by PennyScissors** [comment]
Validated in v2.6-head (6f9c19d), RKE2 1.22.7+rke2r2

**PASS** - Values set by UI regarding RKE2 specific resourced are shown in the compare view.

**PASS** - Values for RKE2 specific resources set by UI after installing/upgrading monitoring in a RKE2 cluster with Linux nodes only:
```yaml
global:
  cattle:
    window:
      enabled: false

rke2ControllerManager:
  enabled: true
rke2Etcd:
  enabled: true
rke2IngressNginx: 
  enabled: true
rke2Proxy:
  enabled: true
rke2Scheduler:
  enabled: true

rkeControllerManager:
  enabled: false
rkeEtcd:
  enabled: false
rkeIngressNginx:
  enabled: false
rkeProxy:
  enabled: false
rkeScheduler:
  enabled: false

ingressNginx:
  enabled: false
```

**PASS** - Values for RKE2 specific resources set by UI after installing/upgrading monitoring in a RKE2 cluster with Linux and Windows nodes:
```yaml
global:
  cattle:
    window:
      enabled: true

rke2ControllerManager:
  enabled: true
rke2Etcd:
  enabled: true
rke2IngressNginx: 
  enabled: true
rke2Proxy:
  enabled: true
rke2Scheduler:
  enabled: true

rkeControllerManager:
  enabled: false
rkeEtcd:
  enabled: false
rkeIngressNginx:
  enabled: false
rkeProxy:
  enabled: false
rkeScheduler:
  enabled: false

ingressNginx:
  enabled: false
```
