### ISSUE TITLE
Update NeuVector link

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5556]
The hardcoded NeuVector button link needs to use the `cattle-neuvector-system` namespace.

**Comment by catherineluse** [comment]
Caleb also requested that to check if NeuVector is installed, we should look for the unique helm chart info instead of looking for all CRDs that have neuvector.com in the name.

> If you could look up the helm install that would work. Or the cattle-neuvector-namespace.

**Comment by David-VTUK** [comment]
Unless we mandate that NV is installed into a specific namespace we shouldn't hard code a namespace in the proxy link.

For example, I've installed the closed-source Neuvector application via helm, and placed it into a namespace called `neuvector`. 

The UI integration appears:

![image](https://user-images.githubusercontent.com/5892615/161544221-6da94d30-dccd-42c0-946f-2f22ea4cdba9.png)

Clicking it results in:

![image](https://user-images.githubusercontent.com/5892615/161544326-ce4f0b3d-ea0c-43bd-bb3e-231338815cf3.png)

The API call is:

```
GETH ttps://<RancherURL>/k8s/clusters/<Cluster>/api/v1/namespaces/neuvector-system/services/https:neuvector-service-webui:8443/proxy
```

The `neuvector-system` namespace doesn't even exist in my environment.

If I modify the API call to reference the correct namespace I get the following:

![image](https://user-images.githubusercontent.com/5892615/161544773-0e5d224a-0277-4307-9412-2b20b2336e4a.png)

This is due to my install of Neuvector - I expose it via an ingress & terminate TLS at the ingress controller with necessitates the following config:

```
manager:
  env:
    ssl: false
  ingress:
    enabled: true
    host: neuvector.mydomain.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    tls: true
    secretName: neuvector-tls-secret
```
Therefore, to make this work, the link has to be modified further to change:

`services/https:neuvector-service-webui:8443/proxy/`
to
`services/http:neuvector-service-webui:8443/proxy/`
