### ISSUE TITLE
Most RKE1 Cluster YAML keys are not validated before cluster creation

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/dashboard#5676]
**Setup**
- Rancher version: v2.6.5-rc1
- Browser type & version: Firefox 98.0.2 on MacOS 12.2.1

**Describe the bug**

Most RKE1 cluster yaml keys are not validated prior to cluster creation. Any keys that are are camel cased or begin with an uppercase letter are not flagged as invalid and the values for those keys will be lost once the cluster is created.

**To Reproduce**
Create an RKE1 cluster by editing via YAML and using uppercase keys 

**Result**
Any keys that are uppercase are replaced with their default values and lose the configured value.

**Expected Result**
The UI should validate all cluster yaml keys and block cluster creation if any configured keys are invalid, same as it does for `name` and `rancher_kubernetes_engine_config`.

**Additional context**
It currently appears to only validate the `name` and `rancher_kubernetes_engine_config` keys

[Here are the three cluster yamls from each stage shown in the screenshots](https://github.com/rancher/dashboard/files/8535232/cluster.yamls.txt)

**Screenshots**

<img width="1363" alt="Screen Shot 2022-04-21 at 5 25 12 PM" src="https://user-images.githubusercontent.com/55704795/164556224-b415bee9-0d26-4ac7-807e-242c49e6f3a3.png">
<img width="1363" alt="Screen Shot 2022-04-21 at 5 26 44 PM" src="https://user-images.githubusercontent.com/55704795/164556227-5491777c-83d6-4fb0-959a-4912b6869d1e.png">
<img width="1363" alt="Screen Shot 2022-04-21 at 5 27 11 PM" src="https://user-images.githubusercontent.com/55704795/164556231-99ce108c-6c7b-4dfb-9438-9bacd335143d.png">
<img width="1363" alt="Screen Shot 2022-04-21 at 5 28 07 PM" src="https://user-images.githubusercontent.com/55704795/164556234-802ec59b-a885-4dc7-8e2a-c410deeba45b.png">

**Comment by rosskirkpat** [comment]
This issue was discovered while investigating a docs issue with `secret_encryption_config` in RKE1 clusters.

Following the docs [here](https://rancher.com/docs/rke/latest/en/config-options/secrets-encryption/#example-using-custom-encryption-configuration-with-user-provided-32-byte-random-key), I specified the following in `kube_api`: 


Before:
<img width="1363" alt="Screen Shot 2022-04-21 at 5 25 49 PM" src="https://user-images.githubusercontent.com/55704795/164558095-32045b93-9307-4f36-b050-7c8e1f6ecc72.png">

```yaml
    kube_api:
      always_pull_images: false
      pod_security_policy: false
      secrets_encryption_config:
        enabled: true
        custom_config:
          api_version: apiserver.config.k8s.io/v1
          kind: EncryptionConfiguration
          Resources:
          - Providers:
            - AESCBC:
                Keys:
                  - Name: key1
                    Secret: b6E0EuBMGOV86UVC76SzUqRAxECZOdK7+tWSzaIP4dk=
              Resources:
                - secrets
            - identity: {}
        service_node_port_range: 30000-32767
```

This configuration passed validation but ended up as

```yml
    kube-api:
      always_pull_images: false
      pod_security_policy: false
      secrets_encryption_config:
        custom_config:
          api_version: apiserver.config.k8s.io/v1
          kind: EncryptionConfiguration
        enabled: true
      service_node_port_range: 30000-32767
```

After:

<img width="1363" alt="Screen Shot 2022-04-21 at 5 53 28 PM" src="https://user-images.githubusercontent.com/55704795/164558178-26449c7c-a633-4765-9219-12549beedb9f.png">
