### ISSUE TITLE
Add secret selectors to receiver config forms

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5743]
As part of the v2 Project Monitoring work tied to Alert Manager Config, we need to add secret selectors. This would help connect to services such as Slack via selectable tokens.

**Comment by catherineluse** [comment]
Here's the QA template for the first 6 of them added in this PR https://github.com/rancher/dashboard/pull/5772

Copied from the PR description:

# QA template

## What was fixed, or what changes have occurred

This PR adds 6 secret selectors for receiver credentials and API keys:

1. Slack: Need to configure `apiUrl` with secret selector.
2. Webhook: Need to configure `urlSecret` with secret selector.

3 and 4: PagerDuty: `routingKey` and `serviceKey` need to be configured with secret selectors.

5: Opsgenie: `apiKey` needs secret selector.
6: Email: `authPassword` needs to be from secret selector.

There is a bug fix to make sure that when you save a receiver as yaml, the result is not a crash or blank page.

## Areas or cases that should be tested

We need to validate that when you change values in the form, it affects the right field in YAML. When values are updated in YAML and then saved, the values should show up the next time the receiver details are loaded.

Basically each field that we expose in form fields for receivers needs to be validated because unfortunately all the YAML fields changed from snake case to camel case.

For example, for Slack I tried it with dummy values:
<img width="1356" alt="Screen Shot 2022-05-03 at 4 55 23 PM" src="https://user-images.githubusercontent.com/20599230/166604496-1b12f97f-e353-493f-a971-1777d8dfdb55.png">

And then made sure all 4 of the dummy values showed up in the YAML view:
```
slackConfigs:
        - apiURL:
            key: password
            name: test-secret
          channel: dtdthdtn
          httpConfig: {}
          sendResolved: false
          text: '{{ template "slack.rancher.text" . }}'
```
The `httpConfig` section can be an empty object because I'm still working on that part (that config block has the TLS selectors).

Here are the other example YAMLs that I used:

### Email

```
 emailConfigs:
        - sendResolved: false
          requireTls: false
          to: dudoidiuhd
          from: iuhiuehih
          smarthost: heihdit
          authUsername: tdtuidtui
          authPassword:
            name: test-secret
            key: password
```

### PagerDuty

If the integration type is set to "Events API V2", the `routerKey` value should be used:
```
pagerdutyConfigs:
        - sendResolved: true
          routingKey:
            name: test-secret
            key: test-secret-key
```

### Opsgenie

```
opsgenieConfigs:
        - sendResolved: true
          apiKey:
            name: test-secret
            key: password
```
If the integration type is set to Prometheus, the `serviceKey` value should be used:
```
pagerdutyConfigs:
        - sendResolved: true
          serviceKey:
            key: ''
            name: test-secret
```
### Webhook
```
webhookConfigs:
          sendResolved: false
          urlSecret:
            name: test-secret
            key: password
```

### What areas could experience regressions?
There is a bug fix to make sure that when you save a receiver as yaml, the result is not a crash or blank page. The navigation should be validated to make sure saves are working as expected


# Unfinished/not in this PR
There is a reused component that corresponds to the `httpConfig` field in YAML. It looks like this:
<img width="1114" alt="Screen Shot 2022-05-03 at 4 50 02 PM" src="https://user-images.githubusercontent.com/20599230/166602701-4cfa1fad-20f3-4988-8693-cf2fbf9085a3.png">

The SSL section is used for Email and Webhook configs. The Auth section appears under Webhook configs only. I'm still working on adding secret selectors for those sections and that will come in a separate PR.

**Comment by catherineluse** [comment]
## QA template part 2
The rest of the secret selectors are added in this other PR https://github.com/rancher/dashboard/pull/5850

### What was fixed, or what changes have occurred
 
This PR adds the last 6 secrets for the receivers in AlertmanagerConfigs. These are required to configure the `httpConfig` section defined here: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#httpconfig

The API docs lacked details about how to configure the `tlsConfig` part (it didn't have a blue link to its definition) so I found its type def in the Prometheus operator code and went off of that:

```go
type SafeTLSConfig struct {
    // Struct containing the CA cert to use for the targets.
    CA SecretOrConfigMap `json:"ca,omitempty"`
    // Struct containing the client cert file for the targets.
    Cert SecretOrConfigMap `json:"cert,omitempty"`
    // Secret containing the client key file for the targets.
    KeySecret *v1.SecretKeySelector `json:"keySecret,omitempty"`
    // Used to verify the hostname for the targets.
    ServerName string `json:"serverName,omitempty"`
    // Disable target certificate validation.
    InsecureSkipVerify bool `json:"insecureSkipVerify,omitempty"`
}
```

- in the `httpConfig` section the YAML fields are:
	- `bearerTokenSecret`
	- `basicAuth.username`
	- `basicAuth.password`
- in the `tlsConfig` section which is grouped under httpConfig:
	- CA (`CA`) - SecretOrConfigMap (the same API as the other secrets, but nested under a `secret` field)
	- Client Cert (`Cert`) - SecretOrConfigMap (the same API as the other secrets, but nested under a `secret` field)
	- Client Key (`KeySecret`) - SecretKeySelector

The new secret selectors are available from the webhook config form:
<img width="1215" alt="Screen Shot 2022-05-05 at 1 49 58 PM" src="https://user-images.githubusercontent.com/20599230/167023365-323f16f9-25e7-4f04-8e3b-770e18659a04.png">

When all secrets are selected, the webhook config yaml looks something like this:

```yaml
webhookConfigs:
        - httpConfig:
            tlsConfig:
              ca:
                secret:
                  name: test-secret
                  key: username
              cert:
                secret:
                  name: test-secret
                  key: username
              keySecret:
                name: test-secret
                key: username
            basicAuth:
              username:
                key: username
                name: test-secret
              password:
                key: password
                name: test-secret
```
Note that either `basicAuth` or `bearerTokenSecret` should be configured, but not both. So without basic auth filled in, it should look like this:

```yaml
webhookConfigs:
        - httpConfig:
            tlsConfig:
              ca:
                secret:
                  name: test-secret
                  key: username
              cert:
                secret:
                  name: test-secret
                  key: username
              keySecret:
                name: test-secret
                key: username
            bearerTokenSecret:
              name: test-secret
              key: username
```

### Areas or cases that should be tested
When selecting any of the 6 secrets from the webhook config form, the values should be updated in YAML.

When the secret selector is set to `None`, the secret in YAML should be deleted and the YAML should still be valid on submit.

The 3 TLS secrets are also configurable in the Email form, but that set of fields is reused in both places, so if the field works in webhook config I would expect it to also work in the email config.
