### ISSUE TITLE
Add receiver icons to Alert Manager Config list page

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5744]
On the list page for Alert Manager Configs, we need to add receiver icons to services like Slack.

**Comment by gaktive** [comment]
We'd need views to reflect two states: one would be a summary of the receivers and then a list view where it would show something like "Project X has Y Slack hooks and Z email notifiers".

@catherineluse

**Comment by catherineluse** [comment]
It's kind of hard to explain the exact requirements, so I'm going to show this test case in which an AlertmanagerConfig has 2 receivers and 4 receiverConfigs nested inside the receivers.

So in this example, let's say an AlertmanagerConfig named `test-2-receivers` has 2 receivers in it, and each of those contains two receiver configs. The first receiver (named `test-slack-and-email`) has Slack and Email, and the second (named `test-pagerduty-and-pagerduty`) has two PagerDuty configs:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: test-2-receivers
  namespace: default
spec:
  receivers:
  - name: test-pagerduty-and-pagerduty
    pagerdutyConfigs:
    - httpConfig: {}
      routingKey:
        key: password
        name: test-secret
      sendResolved: true
    - httpConfig: {}
      sendResolved: true
      serviceKey:
        key: password
        name: test-secret
  - emailConfigs:
    - authPassword:
        key: password
        name: test-secret
      authUsername: dthdth
      sendResolved: false
      tlsConfig: {}
    name: test-slack-and-email
    slackConfigs:
    - apiURL:
        key: username
        name: test-secret
      channel: test-channel
      httpConfig: {}
      sendResolved: false
      text: '{{ template "slack.rancher.text" . }}'
  route:
```
With the above YAML, the expected result would be that in the AlertmanagerConfig list view, the `test-2-receivers` row would have Slack, Email and PagerDuty icons. (Maybe with `x2` next to PagerDuty because there's two)
<img width="1026" alt="Screen Shot 2022-05-04 at 2 35 01 PM" src="https://user-images.githubusercontent.com/20599230/166830403-0e88410b-e2d3-4112-9a36-cb641a302d1c.png">

And then if you click on the AlertmanagerConfig name, and go to the Receivers tab within it, then you would see the breakdown. So the receiver named `test-slack-and-email` would have Slack and Email icons next to it, while `test-pagerduty-and-pagerduty` would get the PagerDuty icon (possibly with `x2`)
<img width="980" alt="Screen Shot 2022-05-04 at 2 34 45 PM" src="https://user-images.githubusercontent.com/20599230/166830667-f1deed7f-9087-45f5-8893-220e87bfafad.png">
