### ISSUE TITLE
Networking tab is missing in Edit Config page on rke2 provisioned cluster

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/dashboard#5866]
**Setup**
- Rancher version: v2.6.5-rc8
- RKE2 Version: v1.21.12-rke2r1 

**Describe the bug**
Networking tab is missing in the Edit Config page. Issue is seen in v1.21.12-rke2r1 only or any 1.21 version but not in later versions

**To Reproduce**
Provision a rke2 cluster version v1.21.12-rke2r1 in 2.6.4 and upgrade rancher version to 2.6.5-rc8. 

**Expected Result**
Networking tab is missing in Edit Config page

**Actual Result**
Networking tab should be present in Edit Config page

**Additional info**
Networking params can be edited using Edit as Yaml
Example:
```
  localClusterAuthEndpoint:
    caCerts: ''
    enabled: false
    fqdn: ''
  rkeConfig:
    chartValues:
```

**Screenshots**
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/56045581/167227368-b71627fb-0af3-4584-9dbf-fc82b3bb1a22.png">
