### ISSUE TITLE
"Clone as yaml" for a secret fails with "Internal Server Error" 

### ISSUE THREAD

**Issue by soumyalj** [rancher/dashboard#608]
Version: master-head(7b948b289)
Steps:
1. Create a secret "testnew" "by choosing type **"registry"** option Or by choosing **"opaque"** option
2. Clone the secret using "Clone as Yaml" option
The Yaml file is displayed as below, change the name to "testnew4"
```
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWcuY29tIjp7InVzZXJuYW1lIjoicmVnMTIiLCJwYXNzd29yZCI6InZhbDEyIn19fQ==
kind: Secret
metadata:
  creationTimestamp: "2020-05-05T23:44:57Z"
  name: testnew4
  namespace: default
  resourceVersion: "56505"
  selfLink: /api/v1/namespaces/default/secrets/regnew3
  uid: ca5ce609-7bf5-4885-90e1-8ea6f2c1c76a
type: kubernetes.io/dockerconfigjson

```
3. Hit "Create" button. 

Result
It fails with the error below:
```
{ "type": "error", "links": {}, "code": "", "message": "resourceVersion should not be set on objects to be created", "status": 500 }
```
Note: If we manually remove the "resourceVersion" from the yaml file, the clone succeeds.

**Comment by aaronRancher** [comment]
This is also seen when trying to clone a secret of type `certificate`
```
{ "type": "error", "links": {}, "code": "", "message": "resourceVersion should not be set on objects to be created", "status": 500 }
```

**Comment by soumyalj** [comment]
Validated with master-head(1f4a2c388)
Steps:

1. Create a secret "test" "by choosing type "registry" option Or by choosing "opaque" option
2. Clone the secret using "Clone as Yaml" option
The Yaml file is displayed as below:
```
apiVersion: v1
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJ0ZXN0MS5jb20iOnsidXNlcm5hbWUiOiJteXRlc3QiLCJwYXNzd29yZCI6Im15cGFzcyJ9fX0=
kind: Secret
metadata:
  labels:
    k2: v2
    k3: v3
  name: ' '
  namespace: default
type: kubernetes.io/dockerconfigjson
```
Fill in the name field and hit create

Result:
Secret gets created as expected without any errors.
