### ISSUE TITLE
Creating secret from yaml file fails

### ISSUE THREAD

**Issue by soumyalj** [rancher/dashboard#615]
Version: master-head(7b948b289)

Steps:
1. Create a secret using "Create from Yaml" option
```
apiVersion: v1
kind: Secret
metadata:
  name: newsecret
  namespace: default
  annotations:
    a1: a2
  labels:
    l1: l2
data:
  k1: v1
```
Create fails with the error below:
```
{ "type": "error", "links": {}, "code": "BadRequest", "message": "Secret in version \"v1\" cannot    
  be handled as a Secret: v1.Secret.ObjectMeta: v1.ObjectMeta.TypeMeta: Kind: Data: decode    
 base64: illegal base64 data at input byte 0, error found in #10     byte of ...| 
  {\"k1\":\"v1\"},\"kind\":\"|..., bigger context ...|{\"apiVersion\":\"v1\",\"data\": 
 {\"k1\":\"v1\"},\"kind\":\"Secret\",\"metadata\":{\"annotations\":{\"a1\":|...", "status": 400 }

```
Also, in the sample template provided, there are two fields `_type ` and `stringdata `. Using them also results in error. 
```
apiVersion: v1
kind: Secret
metadata:
  name: newsecret
  namespace: default
  annotations:
    a1: a2
  labels:
    l1: l2
_type: Opaque
data:
  k1: v1
stringData:
  key1: test1
```
Error seen when creating a secret from the above template
```
{ "type": "error", "links": {}, "code": "BadRequest", "message": "Secret in version \"v1\" cannot be handled as a Secret: v1.Secret.ObjectMeta: v1.ObjectMeta.TypeMeta: Kind: Data: decode base64: illegal base64 data at input byte 0, error found in rancher/dashboard#10 byte of ...|{\"k1\":\"v1\"},\"kind\":\"|..., bigger context ...|type\":\"Opaque\",\"apiVersion\":\"v1\",\"data\":{\"k1\":\"v1\"},\"kind\":\"Secret\",\"metadata\":{\"annotations\":{\"a1\":|...", "status": 400 }

```

**_type should be type** in the template

Is stringdata required in the yaml file ?

**Comment by deniseschannon** [comment]
`stringData ` is not required.

**Comment by mantis-toboggan-md** [comment]
Regarding the _type field: 
    >type is reserved for our api type, so on the few that k8s has a type field on it becomes _type  

    The yaml-creating function used here needs to remap this field. stringData can be hidden similarly.

**Comment by soumyalj** [comment]
Validated with master-head(1f4a2c388)
1. Create a secret using "Create from Yaml" option
For the data field , value should be base64 encoded . key should not be base64 encoded. 
Create secret using "yaml" file succeeded. 
```
apiVersion: v1
kind: Secret
metadata:
  name: mynewtestsecret
  namespace: default
  annotations:
    a1: a2
  labels:
    l1: l2
type: opaque
data:
  keynew: dHNldHZhbA==

```
