### ISSUE TITLE
Apps/Market view not viewable with custom role

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6161]
Internal reference: SURE-4055
Reported in 2.6.3

With a custom role, 'Installed Apps' does not show in the side nav.

**Comment by richard-cox** [comment]
See JIRA for role template

**Comment by nwmac** [comment]
This is due to a difference between the resource types used in the old and new UI.

To give a user access to apps and allow them to see the 'Installed Apps' nav item, addf the following to your custom role template:

```
- apiGroups:
  - catalog.cattle.io
  nonResourceURLs: []
  resourceNames: []
  resources:
  - '*'
  verbs:
  - '*'
```
