### ISSUE TITLE
Missing containerStatus lastState information to Pod detail page

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#6189]
**Detailed Description**
https://github.com/rancher/dashboard/pull/5353 added displaying the containerStatus error states in the container list of the Pod detail page.

The containerStatus object (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#containerstatus-v1-core) also contains a `lastState` field which gives you details about the container's last termination condition.

If there's a lastState in the containerStatus, this should also be displayed in the container list.

**Context**
This is especially useful when you need to debug why a container restarted, because it gives you the exit code, potential error message and reason as well as the time when the container terminated (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#containerstateterminated-v1-core).

**Comment by MSpencer87** [comment]
_Verified_ on `2.6.7-rc1`

The lastState error message is now displayed in the UI on the pod detail page


**Steps To Reproduce**
1) Bring up HA Rancher on 2.6.5
2) Create a deployment that will generate restarts (Import YAML)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashing-test-pod
spec:
  selector:
    matchLabels:
      app: crashing-test-pod
  template:
    metadata:
      labels: 
        app: crashing-test-pod
    spec:      
      containers:
        - command:
            - bash
            - -c
            - "echo test; sleep 10; exit 1;"
          image: ubuntu
          name: crashing-test-container
      securityContext:
        runAsUser: 2000
        runAsGroup: 3000
```
3) View pod detail page, lastState error messages NOT VISIBLE via UI (See left side of screenshot)


**Steps for Validation**
1) Bring up HA Rancher on 2.6.7-rc1
2) Create a deployment that will generate restarts (Import YAML)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashing-test-pod
spec:
  selector:
    matchLabels:
      app: crashing-test-pod
  template:
    metadata:
      labels: 
        app: crashing-test-pod
    spec:      
      containers:
        - command:
            - bash
            - -c
            - "echo test; sleep 10; exit 1;"
          image: ubuntu
          name: crashing-test-container
      securityContext:
        runAsUser: 2000
        runAsGroup: 3000
```
3) View pod detail page, lastState error messages VISIBLE via UI (See right side of screenshot)
![lastState](https://user-images.githubusercontent.com/6477538/179125366-ff34ba46-14bd-4e3a-81cc-3224deecd519.png)

![lastState2](https://user-images.githubusercontent.com/6477538/179125373-ca0b91cf-b03c-4f32-8640-99c1f24f45d7.png)
