### ISSUE TITLE
Fails to create constraint in yaml view.

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#622]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster, navigate to dashboard, enable gatekeeper.
2. Go to constraint page. Click create
3. There is a button 'Edit as yaml'. Shouldn't it be 'Create as yaml' ?
4. Enter Name and press tab or click anywhere else. Name text goes off, also it doesn't replace the ```null``` in name in yaml body.
Yaml snapshot:
```
metadata:
  name: null
```
5. Write proper yaml for constraint and click save. It shows error ```Cannot read property 'hasLink' of undefined```
<img width="1307" alt="Screen Shot 2020-05-07 at 4 00 20 PM" src="https://user-images.githubusercontent.com/60111667/81353312-8e3e9800-907d-11ea-93c0-36a8448b6c1a.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master branch on 2.4-head ```454daa475``` rancher set up.
- Installation option (single install/HA): Single

**Comment by izaac** [comment]
Create from YAML shows the codemirror text area blank. 

Previously the UI workflow was:

- Navigate to OPA Gatekeeper -> Constraints
- Click Create -> Click Edit as YAML
- The default template YAML was ready pre-filled for edit in the textarea.

Example with `k8sallowedrepos` (the default).

```yaml
type: constraints.gatekeeper.sh.k8sallowedrepos
spec:
  match:
    excludedNamespaces:
      - cattle-system
      - gatekeeper-system
      - ingress-nginx
      - kube-node-lease
      - kube-public
      - kube-system
      - security-scan
    kinds:
      - apiGroups:
          - ''
    labelSelector:
      matchExpressions: []
    namespaceSelector:
      matchExpressions: []
  parameters: {}
  enforcementAction: deny
metadata:
  name: null
  annotations:
    cattle.io/description: null
```

Not the UI workflow is:

- Navigate to OPA Gatekeeper -> Constraints
- Click Create as YAML
- The textarea is not pre-filled from the template as the previous workflow.

Blank textarea. And the text area is not pre-filled even changing the template.

![Screen Shot 2020-05-20 at 10 34 43 AM](https://user-images.githubusercontent.com/27659/82478879-6c361400-9a86-11ea-8d1b-02a2851f94e1.png)

Browset Devtools console shows if I click Save with the blank YAML:

```
TypeError: n.value.yamlForSave is not a function
    at ResourceYaml.vue:186
    at Generator.next (<anonymous>)
    at r (asyncToGenerator.js:3)
    at l (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
    at f.save (ResourceYaml.vue:185)
    at Qt (vue.runtime.esm.js:1854)
    at f.n (vue.runtime.esm.js:2179)
```

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 4911f8b`

Created a constraint from YAML using default example.
```
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedRepos
metadata:
  name: test
  annotations:
    field.cattle.io/description: ''
#    key: string
  labels:
    {}
#    key: string
#  namespace: string
spec:
  parameters: {}
  match:
    kinds: []
    namespaces: []
    excludedNamespaces: []
    labelSelector:
      matchExpressions: []
    namespaceSelector:
      matchExpressions: []
```
