### ISSUE TITLE
The field "Priority Class Name" is empty in new Rancher UI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6443]
Internal reference: SURE-4815
Reported in 2.6.4 & 2.6.5

Issue description:
The field "Priority Class Name" is empty for deployment in the new Rancher UI when Priorities are correctly configured. This is, after configuring a Priority for a Deployment, no matter the way to do it, this priority doesn't show the "Priority Class Name" field after being established.

Repro steps:

- Create a Priority for a Workaround.
-- New UI: Workload -> Deployments -> Three dots in one of the deployments -> Edit Config -> Resources -> Priority.
-- There is also the possibility of creating it by using the /g UI: Projects/Namespaces -> Project -> Workloads -> Three dots in one of the workloads -> Edit -> Node scheduling -> Show advanced options.
-- There is also the possibility of creating it by modifying directly the YAML file.
- Check the Priority of the Workaround. Field "Priority Class Name" is not shown. (Workload -> Deployments -> Three dots in one of the deployments -> Edit Config -> Resources -> Priority -> Priority Class Name is Empty).

Workaround:

- Check the YAML file instead of the UI.
- Check the Priority configurations with the /g UI: Projects/Namespaces -> Project -> Workloads -> Three dots in one of the workloads -> Edit -> Node scheduling -> Show advanced options -> Priority Class Name is properly shown.

Actual behavior:
Priority Class Name is Empty.

Expected behavior:
Priority Class Name is properly shown as it is in the /g UI.

**Comment by nwmac** [comment]
@Shavindra This is on the deployments UI that you improved recently.

**Comment by Josh-Diamond** [comment]
Ticket #6443 - Test Results

With Docker on a single-node instance:

Reproduced on rancher `v2.6.5`:
1. Fresh install of rancher `v2.6.5`
2. Provision a downstream RKE2 cluster
3. Create a priority class; `kubectl apply -f priority.yml`

priority.yml
```yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
```
4. Deploy a workload, and set Priority Class Name to `high-priority`
5. Once workload is `Active`, `Edit Config` and observe Priority Class Name field
6. Reproduced - Priority Class Name field blank;

Screenshot:

`Step 6`
<img width="1467" alt="Screen Shot 2022-09-12 at 11 00 38 AM" src="https://user-images.githubusercontent.com/46494969/189724175-19327743-2b20-4cd8-9be9-568d652a188b.png">

---

Verified on rancher `v2.6-68215bcdde090854ff28b43b01d1aa0b69611920-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream RKE2 cluster
3. Create a priority class; `kubectl apply -f priority.yml`:

priority.yml
```yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
```
4. Deploy a workload, and set Priority Class Name to `high-priority`
5. Once workload is `Active`, `Edit Config` and observe Priority Class Name field
6. Verified - Priority Class Name data persists and is properly set

Screenshot:

`Step 6`
<img width="1471" alt="Screen Shot 2022-09-12 at 10 39 24 AM" src="https://user-images.githubusercontent.com/46494969/189720376-994ddb74-cc3e-4bbb-a7bb-cb64ce3f7295.png">
