### ISSUE TITLE
Creating a configmap from yaml file fails 

### ISSUE THREAD

**Issue by soumyalj** [rancher/dashboard#645]
Version: master-head(dd102af17)

Steps:
1. Create a configmap from Yaml file. 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test20
  namespace: default
  annotations:
    a1: a2
  labels:
    key2: val1
binaryData:
  k1d: dfs
data:
  key1: test1
```
Configmap creation, fails with the below error:
```
{ "type": "error", "links": {}, "code": "BadRequest", "message": "ConfigMap in version \"v1\"  
 cannot be handled as a ConfigMap: v1.ConfigMap.Data: BinaryData: decode base64: illegal  
 base64 data at input byte 0, error found in rancher/dashboard#10 byte of ...|k1d\":\"dfs\"},\"data\":{|..., bigger  
 context ...|{\"apiVersion\":\"v1\",\"binaryData\":{\"k1d\":\"dfs\"},\"data\": 
 {\"key1\":\"test1\"},\"kind\":\"ConfigMap\",\"meta|...", "status": 400 }

```

Other Info:
The yaml has binary data field presented as key: string. While creating as a form , we provide binary data through a file.

**Comment by codyrancher** [comment]
I know we discussed this offline. With the additional information you provided I think this is intended behavior and not a bug.

It looks like binaryData values need to be a base64 encoded string, not a plain string. So to make your example work you'd use this instead:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test20
  namespace: default
  annotations:
    a1: a2
  labels:
    key2: val1
binaryData:
  k1d: ZGZz
data:
  key1: test1
```

You can use something like https://www.base64encode.net/ to do the encoding.

**Comment by vincent99** [comment]
`binaryData` is arbitrary bytes and therefore needs to be base64-encoded; `data` needs to be a valid UTF-8 string so it doesn't need encoding.

**Comment by soumyalj** [comment]
Validated with master-head(1f4a2c388)
1. Create a configmap from yaml file . Sample below:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: yamlcmap
  namespace: default
  annotations:
    a1: a2
  labels:
    l1: l2
binaryData:
  key1test: dHNldHZhbA==
data:
  key1: testval
```

Config map creation succeeds as expected. 
Note: Binary data value is base64 encoded.
