### ISSUE TITLE
[BUG] seLinux Being Disabled by Default Causing Logging Upgrade to Fail

### ISSUE THREAD

**Issue by nickwsuse** [rancher/dashboard#6630]
**Rancher Server Setup**

- Rancher version: `2.6.7-rc6`
- Installation option (Docker install/Helm Chart): HELM
  - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details: byo-valid

**Information about the Cluster**
- Kubernetes version: `v1.23.7`
- Cluster Type (Local/Downstream): `Downstream Imported AWS RKE2 cluster`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): `admin`

**Describe the bug**
After upgrading rancher from 2.6.6. to 2.6.7-rc6, I upgraded logging to 3.17.7; The rancher-logging app on the installed apps page shows a FAILED tag. the rancher-logging-rke2-journalId-aggregators are in crashloop and after investigation it's because the seLinux value in the values.yaml file is set to `false` when it should be set to `true`

**To Reproduce**
1. Install previous version of logging in rke2 cluster
2. configure cluster output
3. configure cluster flow
4. verify that logs are flowing to output (eg, elasticsearch)
5. upgrade logging to latest 100.1.3-up3.17.7 [pointed charts repo to dev-2.6]
6. click the "Edit YAML" button on the second page of the install
7. search for `global` > `seLinux` > `enabled` > see it's `false` instead of `true`

Result
Upgrade fails; rke2 logging aggregator pods in crashloop

Expected Result
Upgrade succeeds and logs resume flowing to elasticsearch

**Screenshots**

App Failed State:
![app_failed_state](https://user-images.githubusercontent.com/107147272/183769953-c4ff69e9-339f-4a08-97aa-1eb1c0af9427.png)

Crashloop:
![crashloop](https://user-images.githubusercontent.com/107147272/183771323-1504fbd2-fc5c-4ca3-8f80-225a39c3b8db.png)

seLinux Set to False:
![seLinux_false](https://user-images.githubusercontent.com/107147272/183771354-ae72ae24-c53a-49f2-90f7-5e0177c072f2.png)

Deployed After Setting seLinux to True:
![deployed_after_edit](https://user-images.githubusercontent.com/107147272/183771427-dbf115a1-60b3-4e63-a9dd-c6ab27103810.png)

**Comment by gaktive** [comment]
Upon looking over past values.yaml files, the formatting did change.

From the 3.9 era (before the `100` prefix), towards the end of the file:
```
global:
  cattle:
    systemDefaultRegistry: ""
    # Uncomment the below two lines to either enable or disable Windows logging. If this chart is
    # installed via the Rancher UI, it will set this value to "true" if the cluster is a Windows
    # cluster. In that scenario, if you would like to disable Windows logging on Windows clusters,
    # set the value below to "false".
    # windows:
    #   enabled: true
  # Change the "dockerRootDirectory" if the default Docker directory has changed.
  dockerRootDirectory: ""
  # This psp setting differs from the upstream "rbac.psp" by only enabling psp settings for the
  # overlay files, which include the Logging CRs created, whereas the upstream "rbac.psp" affects the
  # logging operator.
  psp:
    enabled: true
  seLinux:
    enabled: false
```

From more recent versions (latest: 100.1.3+up3.17.7), there is an indent:
```
global:
  cattle:
    systemDefaultRegistry: ""
    # Uncomment the below two lines to either enable or disable Windows logging. If this chart is
    # installed via the Rancher UI, it will set this value to "true" if the cluster is a Windows
    # cluster. In that scenario, if you would like to disable Windows logging on Windows clusters,
    # set the value below to "false".
    # windows:
    #   enabled: true

  # Change the "dockerRootDirectory" if the default Docker directory has changed.
  dockerRootDirectory: ""

  # This psp setting differs from the upstream "rbac.psp" by only enabling psp settings for the
  # overlay files, which include the Logging CRs created, whereas the upstream "rbac.psp" affects the
  # logging operator.
  psp:
    enabled: true

  rkeWindowsPathPrefix: "c:\\"

  seLinux:
    enabled: false
```

**Comment by catherineluse** [comment]
@nickwsuse What was the logging chart version before you upgraded it?

**Comment by nickwsuse** [comment]
@catherineluse the original version of the logging chart I used is 100.1.2+up3.17.4

**Comment by catherineluse** [comment]
I attempted to reproduce this issue, but it appeared to work as expected. Here's what I tried:

1. Installed logging version 100.1.2+up3.17.4
2. Confirmed that SeLinux was set to false by default in the values.yaml:

```
global:
  cattle:
    systemDefaultRegistry: ''
    systemProjectId: p-26wcf
  dockerRootDirectory: ''
  psp:
    enabled: true
  rkeWindowsPathPrefix: c:\
  seLinux:
    enabled: false
```
3. Updated the chart to set `seLinux` to true, without upgrading the logging app to a newer version
4. Upgraded to logging version 100.1.3+up3.17.7
5. Confirmed that `seLinux.enabled` was still true

@nickwsuse Do you remember when the `seLinux.enabled` was originally set to true?
