### ISSUE TITLE
Selector preview in service edit form does not consider namespaces

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#6984]
**Setup**
- Rancher version: 2.6.8
- Browser type & version: Chrome

**Describe the bug**
When you create or edit a service. The preview box that tells you which Pods are matched by the selector does not consider namespaces. A service can only match pods from the same namespace.

**To Reproduce**
Create a deployment in the `default` namespace:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: container-0
```

Then create a service in the `kube-system` namespace and add the selector `app: nginx`.

Another effect is that the number of total pods is not the number of pods in the namespace, but the number of total pods in the cluster.

**Result**
The preview box shows that it matches the pod from the nginx deployment.

**Expected Result**
The preview box should show that it does not match any pods.

**Screenshots**
<img width="1127" alt="Bildschirmfoto 2022-09-23 um 16 26 44" src="https://user-images.githubusercontent.com/243056/191984059-f7f43f63-c7f2-4147-b924-e683a0549324.png">
