### ISSUE TITLE
User is logged out when selecting a cluster that is in `updating` state

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#7033]
**Setup**
- Rancher version: v2.7-head (c567ef3)
- Browser type & version: chrome

**Describe the bug**

when a user clicks on a cluster that is in an `updating` state, the user is logged out of rancher.

**To Reproduce**

* deploy a k3s cluster with 1 node for each role
* wait for the cluster to get to an active state
* edit as yaml and add the following under `rkeConfig`
```
    machineSelectorConfig:
    - config:
        docker: false
        flannel-conf: testvar1
        flannel-iface: testvar2
        kube-proxy-arg:
        - kprox1
        - kprox2
        kubelet-arg:
        - addKarg1
        - addKarg2
        pause-image: rancher/pause
        protect-kernel-defaults: false
        resolv-conf: resolveisNotKnown
        selinux: false
        snapshotter: overlayfs
```
* wait for the cluster to get to an `updating` state
* explore the cluster

**Result**
user is logged out upon selecting the updating cluster

**Expected Result**

user should not be logged out when selecting a cluster from the `explore cluster` or `home` page

**Screenshots**

[testvideo](https://user-images.githubusercontent.com/16691014/192874330-1dc0e79f-5118-4178-81dd-8356eedb84f8.mov)

**Additional context**

* unsure if user should be able to select an `updating` cluster at all, but if they should then they should not be logged out after selecting it.  
* this might be dependent on a cluster being in a _certain_ updating state. The video above has etcd in `unavailable`, controlplane in `reconciling` and worker `active`.
