### ISSUE TITLE
k3s cluster in `error` state still accessible through `explore cluster` and home page

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#7036]
**Setup**
- Rancher version: v2.7-head (c567ef3)
- Browser type & version: chrome

**Describe the bug**

if a k3s cluster gets into an error state, the cluster is still selectable from the `explore cluster` menu and home page

**To Reproduce**

* deploy a k3s cluster with dedicated nodes-per-role
* wait for the cluster to get to an active state
* edit the cluster.yaml and add the following to the `rkeConfig` section:
```
machineSelectorConfig:
    - config:
      kubelet-arg:
        - 'streaming-connection-idle-timeout=5m'
      flannel-conf: /tmp/fake.conf
      flannel-iface: eth0
      kube-proxy-arg: feature-gates=CSIMigrationAWS=false
      resolv-conf: /tmp/resolv.conf
```
* wait for the worker node to get to an `error` state (~5 minutes)

**Result**
the cluster gets to an error state, but the cluster is still selectable from both the home page and in the `explore cluster` menu
clicking the cluster results in a 500 error

**Expected Result**

cluster should not be accessible if it is in an error state

**Screenshots**

<img width="782" alt="Screen Shot 2022-09-28 at 4 22 37 PM" src="https://user-images.githubusercontent.com/16691014/192906018-ae23adb2-11c0-4384-9744-1caab2d58dba.png">

**Additional context**
