### ISSUE TITLE
node status updates on machine-pools page, but not in `explore cluster` -> `nodes` page.  Node statuses do not match.

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#7037]
**Setup**
- Rancher version:v2.7-head (c567ef3)
- Browser type & version: chrome

**Describe the bug**

if a cluster's nodes are changing states, the states appear to only update on the `cluster management` -> select cluster -> `machine pools` page, and not on `explore cluster` -> select cluster -> `nodes` for all states except `active` and `unavailable`

**To Reproduce**

* deploy a k3s cluster with dedicated nodes-per-role
* wait for the cluster to get to an active state
* edit the cluster.yaml and add the following to the `rkeConfig` section:
```
machineSelectorConfig:
    - config:
      kubelet-arg:
        - 'streaming-connection-idle-timeout=5m'
      flannel-conf: /tmp/fake.conf
      flannel-iface: eth0
      kube-proxy-arg: feature-gates=CSIMigrationAWS=false
      resolv-conf: /tmp/resolv.conf
```
* observe that one more more nodes go into an `updating` or `reconciling` state
* immediately check the status from `explore cluster` -> select cluster -> `nodes`

**Result**
node states do not match. 

**Expected Result**

expecting node states to match.

**Screenshots**

<img width="1031" alt="Screen Shot 2022-09-28 at 4 17 50 PM" src="https://user-images.githubusercontent.com/16691014/192907192-b8b5a98a-2652-4d72-aeae-c6a64694ecf8.png">
<img width="759" alt="Screen Shot 2022-09-28 at 4 17 36 PM" src="https://user-images.githubusercontent.com/16691014/192907198-c6463ee6-1bc7-48d7-9d07-c86e1a9111b0.png">
