### ISSUE TITLE
Rancher UI showing same cpu/mem/securityContext for multi container APPs

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7066]
Internal reference: SURE-5300
Reported in 2.6.8

Issue description:
After deployment of a multi-container app, app config shows wrong values for certain fields like cpu reservation and securityContext.runAsUser 

Troubleshooting steps:
After deploying the multi container app with different configuration, go to config or "edit config" to see the fields like cpu/memory/runAsUser field. For each container, it will show the value of first container in the yaml files. Same case for UI deployed containers

Repro steps:

1) Deploy multi container app with below yaml file, with cpu requests and securityContext

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: myappsone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        appname: myappsone
    spec:
      containers:
      - image: redis
        imagePullPolicy: Always
        name: myapp1
        resources:
          requests:
            cpu: 100m
        securityContext:
          runAsUser: 1111
      - image: tomcat
        imagePullPolicy: Always
        name: myapp2
        resources:
          requests:
            cpu: 300m
        securityContext:
          runAsUser: 2222
``` 

2) Go Apps >> Workloads >> Deployment >> Click on the deployed App >> Click on the "config" on top

3) Select the tab Containers >> Select each containers and check the fields cpu reservation, Run As userid

No workaround

Actual behavior:
For each containers, same value is shown,  which are the values of first container in the yaml. 

Expected behavior:
For each container, its own field values should be show in the UI

**Comment by Shavindra** [comment]
Fixed by https://github.com/rancher/dashboard/pull/6841

https://github.com/rancher/dashboard/pull/6841/files#diff-1e8612cdc344c04a806d686e55bd67c1d30eef9cd86bb0f7a9d803fed5cb5f6aR197

**Comment by markusewalker** [comment]
**QA TEST PLAN - TO REPRODUCE**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|On a fresh install of Rancher `v2.6.8`, provision an RKE2 node driver cluster as a standard user, deploy multi-container app, validate if same CPU/memory/securityContext are shown|
|2|On Rancher `v2.6.8`, provision an RKE2 node driver cluster as a standard user, deploy multi-container app, validate if same CPU/memory/securityContext are show, upgrade Rancher to `v2.6.9`, validate once more|

**QA TEST PLAN - TO VALIDATE**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|On a fresh install of Rancher `v2.7-head`, provision an RKE2 node driver cluster as a standard user, deploy multi-container app, validate if same CPU/memory/securityContext are shown|
|2|On Rancher `v2.6.9`, provision an RKE2 node driver cluster as a standard user, deploy multi-container app, validate if same CPU/memory/securityContext are show, upgrade Rancher to `v2.6.9`, validate once more|

**Comment by markusewalker** [comment]
Reproduced this behavior on `v2.6.8`. Validated this is fixed against `v2.7-head` https://github.com/rancher/rancher/commit/6b4cf8845dd52213a41dd8af1a11b8005f5c9161.

**ENVIRONMENT DETAILS**
- Rancher install:
     - Docker - `v2.6.8`
     - Helm - `v2.7-head https://github.com/rancher/rancher/commit/6b4cf8845dd52213a41dd8af1a11b8005f5c9161`
- Rancher version:
     - Reproduced: `v2.6.8`
     - Verified: `v2.7-head` https://github.com/rancher/rancher/commit/6b4cf8845dd52213a41dd8af1a11b8005f5c9161
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|On a fresh install, provision an RKE2 node driver cluster as a standard user, deploy multi-container app, validate if same CPU/memory/securityContext are shown|:white_check_mark:|

**REPRODUCTION STEPS**

**Scenario 1**
1. Setup Rancher, created a standard user and logged in as that user.
2. Provisioned a downstream RKE2 node driver cluster; validated that the cluster and nodes came up as `Active`.
3. Navigated to Cluster Explorer > cluster> Workloads > Deployments.
4. Created a new deployment with the following YAML:
 ```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: myappsone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        appname: myappsone
    spec:
      containers:
      - image: redis
        imagePullPolicy: Always
        name: myapp1
        resources:
          requests:
            cpu: 100m
        securityContext:
          runAsUser: 1111
      - image: tomcat
        imagePullPolicy: Always
        name: myapp2
        resources:
          requests:
            cpu: 300m
        securityContext:
          runAsUser: 2222
```
5. Edited the deployment's config and reproduced the original information; there is duplicate shown:

_**Same in container `myapp1` and `myapp2`**_
![image](https://user-images.githubusercontent.com/52591819/199103749-381d49cd-cb35-42c7-bc1b-a376af11c6a5.png)


**VALIDATION STEPS**

**Scenario 1**
1. Setup Rancher, created a standard user and logged in as that user.
2. Provisioned a downstream RKE2 node driver cluster; validated that the cluster and nodes came up as `Active`.
3. Navigated to Cluster Explorer > cluster> Workloads > Deployments.
4. Created a new deployment with the following YAML:
 ```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: myappsone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        appname: myappsone
    spec:
      containers:
      - image: redis
        imagePullPolicy: Always
        name: myapp1
        resources:
          requests:
            cpu: 100m
        securityContext:
          runAsUser: 1111
      - image: tomcat
        imagePullPolicy: Always
        name: myapp2
        resources:
          requests:
            cpu: 300m
        securityContext:
          runAsUser: 2222
```
5. Edited the deployment's config and validated that there is no duplicate information in `Resources` or in `Security Context`:
![image](https://user-images.githubusercontent.com/52591819/199102858-27536c79-0b15-46f2-adb0-f2781e426f01.png)
![image](https://user-images.githubusercontent.com/52591819/199102869-e1bfaf44-f24c-4dec-a1cf-f5a85cd3b1ed.png)
![image](https://user-images.githubusercontent.com/52591819/199102884-064f44c0-7a56-4bd9-ae64-a1a4580b2d70.png)
![image](https://user-images.githubusercontent.com/52591819/199102892-b93feebd-c652-4c16-8165-0bde342e7ceb.png)
