### ISSUE TITLE
Enable possibility to set private DNS on AKS provisioning

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7163]
Internal reference: SURE-3392

Request description:
Enable the possibility to set private DNS on AKS provisioning cluster. Currently, clusters are manually provisioned (or via Terraform) and skips the UI completely.

Actual behavior:
Currently, there is no setting in Rancher to set a private DNS for AKS cluster.

Expected behavior:
Add the possibility to set private DNS on AKS provisioning cluster.

Additional notes:
Based on one environment, the network infrastructure is more or less the same as the "hub and spoke" on the page: https://docs.microsoft.com/en-us/azure/aks/private-clusters#hub-and-spoke-with-custom-dns

Their DNS is centralized in the hub network, and they want to run AKS clusters in spoke networks.
To get it to work, they need to be able to point the AKS clusters to the central private DNS zone. Otherwise, the created AKS cluster's Kubernetes API endpoint address won't resolve, and the cluster will fail to provision, and the VMs can't resolve the Kubernetes API address.

Additional Azure documentation on how to set a custom private DNS zone: https://docs.microsoft.com/en-us/azure/aks/private-clusters#create-a-private-aks-cluster-with-a-custom-private-dns-zone

Usage: under clusters.tf, within the `resource` JSON, there'd be a `private_dns_zone_id` to leverage

**Comment by nwmac** [comment]
I think we need to talk to backend about this to understand where we would wire this in to the request we send to create an AKS cluster

**Comment by mantis-toboggan-md** [comment]
There's no private dns zone field defined in the relevant schema so I think we'll need backend involvement to add support for the feature then UI work to expose it; the backend issue is [here](https://github.com/rancher/rancher/issues/39422)

**Comment by mantis-toboggan-md** [comment]
@gaktive I don't think we're unblocked here. I still don't see this field defined in the aksClusterConfigSpec schema; I believe we're waiting on https://github.com/rancher/rancher/issues/39422

**Comment by gaktive** [comment]
Taking Team 2 (Hostbusters) off and putting Highlander instead.

**Comment by mjura** [comment]
To be specific we are talking about this case when AKS is deployed as private cluster  and we are setting cluster with these options:
```
--enable-managed-identity --assign-identity <resourceID> --private-dns-zone <custom private dns zone or custom private dns subzone resourceID>

Here is the link to documentation:

https://learn.microsoft.com/en-us/azure/aks/private-clusters?tabs=azure-portal#create-a-private-aks-cluster-with-a-custom-private-dns-zone-or-private-dns-subzone

Fields which have to be set:
https://github.com/rancher/aks-operator/blob/release-v2.8/pkg/apis/aks.cattle.io/v1/types.go#L127
https://github.com/rancher/aks-operator/blob/release-v2.8/pkg/apis/aks.cattle.io/v1/types.go#L144
https://github.com/rancher/aks-operator/blob/release-v2.8/pkg/apis/aks.cattle.io/v1/types.go#L146

**Comment by mjura** [comment]
@gaktive @mantis-toboggan-md What help do you need for this ? Did you check link from documentation

 https://learn.microsoft.com/en-us/azure/aks/private-clusters?tabs=azure-portal#create-a-private-aks-cluster-with-a-custom-private-dns-zone-or-private-dns-subzone

**Comment by mjura** [comment]
Please let me know if I can help you somehow?

**Comment by mantis-toboggan-md** [comment]
Thank you for the clarification on this @mjura - looks like we are unblocked @gaktive. The fields to be set are:
 
 `privateDNSZone` - string Private dns zone mode for private cluster.
	
`managedIdentity` - boolean Should a managed identity be enabled or not?
	
`userAssignedIdentity` - string User assigned identity to be used for the cluster.

And this requires `privateCluster` to be `true`

**Comment by cpinjani** [comment]
Validated on build: `v2.9-a9534addc5745ec2c93cde7f5e3c54bc9b3a1f91-head`
The new fields `privateDNSZone`, `managedIdentity`, `userAssignedIdentity` are visible on UI while provisioning AKS cluster.

AKS expects `privateDNSZone` string to be in format: `/subscriptions/<subscription_id>/resourceGroups/<rg_id>/providers/Microsoft.Network/privateDnsZones/<name>`

The current validation on UI is not allowing the above format so needs to be fixed.
![image](https://github.com/rancher/dashboard/assets/73099870/35ad371a-5971-40d6-b1c3-efe769cfb766)

If `privateDNSZone` is provided in format _NAME.private.REGION.azmk8s.io_, cluster fails to provision.
![image](https://github.com/rancher/dashboard/assets/73099870/2e0053c6-ffad-4a2a-b37f-28673be7b74e)

**Comment by mantis-toboggan-md** [comment]
@cpinjani is the expected format for privateDNSZone documented somewhere? What you have quoted doesn't seem to line up with the error message in your screenshot

**Comment by cpinjani** [comment]
@mantis-toboggan-md In the UI field "Private DNS Zone ID", user is suppose to provide full resource-id of privateDNSZone which on Azure postal is of format, as error message states. [Reference](https://learn.microsoft.com/en-us/azure/aks/private-clusters?tabs=azure-portal#create-a-private-aks-cluster-with-a-custom-private-dns-zone-and-custom-subdomain)

```
/subscriptions/<subscription_id>/resourceGroups/<resourcegroup_name>/providers/Microsoft.Network/privateDnsZones/<private_dns_zone_name>
```

![image](https://github.com/rancher/dashboard/assets/73099870/e481e3e6-477c-4818-ae84-a971c2a9b458)

Let me know if this clarifies.

**Comment by mantis-toboggan-md** [comment]
Ahhh I see, the error message has a lot of information about the zone _name_ but what the user needs to enter here is the _id_ which has a bunch of other stuff prefixed to the name. Thank you for clarifying @cpinjani 

I was unable to find a reliable way to validate the resource id field - AKS documentation generally covers what is allowed in user inputs but not this system-generated field. I made a PR to remove UI validation for this field because we can't do it correctly it seems.

**Comment by cpinjani** [comment]
Validation passed on build: `v2.9-c1d92781561c0d4d5a18b32b2f312655dfe67e9c-head`
User able to set privateDNS on AKS provisioning.

![image](https://github.com/rancher/dashboard/assets/73099870/6dc1a9ee-8a4b-425a-a419-b5a4391491b2)

**Spec:**
```
aksConfig:
    authBaseUrl: null
    authorizedIpRanges: null
    azureCredentialSecret: cattle-global-data:cc-dcgtt
    baseUrl: null
    clusterName: cpinjani-priv
    dnsPrefix: cpinjani-priv
    dnsServiceIp: 10.0.0.10
    dockerBridgeCidr: null
    httpApplicationRouting: null
    imported: false
    kubernetesVersion: 1.29.2
    linuxAdminUsername: azureuser
    loadBalancerSku: standard
    logAnalyticsWorkspaceGroup: null
    logAnalyticsWorkspaceName: null
    managedIdentity: true
    monitoring: null
    networkPlugin: kubenet
    networkPolicy: calico
    nodePools:
      - availabilityZones:
          - '1'
          - '2'
          - '3'
        count: 1
        maxPods: 110
        maxSurge: '1'
        mode: System
        name: agentpool
        orchestratorVersion: 1.29.2
        osDiskSizeGB: 128
        osDiskType: Managed
        osType: Linux
        vmSize: Standard_DS2_v2
    outboundType: loadBalancer
    podCidr: null
    privateCluster: true
    privateDnsZone: >-
      /subscriptions/<REDACTED>/resourceGroups/<REDACTED>/providers/Microsoft.Network/privateDnsZones/<REDACTED>
    resourceGroup: <REDACTED>
    resourceLocation: eastus
    serviceCidr: 10.0.0.0/16
    subnet: null
    tags:
      Account Type: group
    userAssignedIdentity: >-
      /subscriptions/<REDACTED>/resourcegroups/<REDACTED>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<REDACTED>
    virtualNetwork: null
    virtualNetworkResourceGroup: null
```
