### ISSUE TITLE
Kubernetes 1.25 Support for Rancher Distros

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7176]
Internal reference: SURE-4603

Kubernetes 1.25 is out so as backend does it work in https://github.com/rancher/rancher/issues/38701, this ticket is a placeholder (or waits in the wings) in case UI is required.

Connection to one known feature; API Removals: https://github.com/rancher/dashboard/issues/7175 or rancher/dashboard#7175

**Comment by jiaqiluo** [comment]
PodSecurityPolicy is removed and replaced by the built-in PodSecurityAdmission plugin in 1.25, therefore the Dashboard UI needs to be updated to support setting PSA, instead of PSP, for the 1.25 cluster.

## For the RKE1 cluster
### On the Cluster creation/edit page 
Under the `Advanced Options` section, we would like to have a new field named `Pod Security Admission Configuration`, and it has two options in the dropdown list: `restricted` and  `unrestricted`;
 
The fields and available values in the dropdown list should match the following YAML:
```
rancher_kubernetes_engine_config:
  services:
    kube-api:
      pod_security_admission_config: <restrictedPSAConfig, unrestrictedPSAConfig>
```

### on the Project creation/edit page 
We would like to have a new section named `Pod Security Standard`, it has two options in the dropdown list: `restricted` and  `unrestricted`.
The default values match the ones set in the `Pod Security Admission Configuration` section. 

Behind the scene, those values are translated to the following labels on the Namespace in the Project:
```
apiVersion: v1
kind: Namespace
metadata:
  name: my-baseline-namespace
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: v1.25 
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.25
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.25
```
