### ISSUE TITLE
UI list pods from multiple statefulset if they share the same label

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7555]
Internal reference: SURE-5576
Reported in 2.6.9

If there are two StatefulSets with the same label. The UI will list the pods from both StatefulSet.
As you can see in the screenshots below, when selecting StatefulSet busybox-1, the user can list the pods of both busybox-1 and busybox-2 because they share the same label (app: busybox). (This is from 2.6.9)

![image-2022-11-18-15-10-32-703.png](https://zube.io/files/rancher/b104e318a4bbbf7a42382e1def733beb-image-2022-11-18-15-10-32-703.png)

And when selecting any of the two StatefulSets, the user can see pods from both StatefulSets

![image-2022-11-18-15-11-15-357.png](https://zube.io/files/rancher/719f59650f8b77a08286a63c13e016b1-image-2022-11-18-15-11-15-357.png)

It seems even kubectl doesn’t have the ability to list pods for specific StatefulSet. We can only use labels. Any guidance here will be appreciated.

Issue also affects old version 2.5

Business impact:

UI list pods from multiple StatefulSet if they share the same label

Troubleshooting steps:

Repro steps:

- Create a Rancher cluster
- Deploy two Statefulset with the same label
- Go to the Statefulset page in the UI, and it will list pods from both StatefulSets

No workaround

Expected behavior:

UI should not list pods from multiple StatefulSets if they share the same label

**Comment by gaktive** [comment]
Part of this may be permissible by Kubernetes. If that's the case, we need to document what that part is but we still have to sort out what's going on with the lack of uniqueness in labels is.

**Comment by nwmac** [comment]
I believe this is as indented k8s behaviour

**Comment by nwmac** [comment]
@aalves08 I would try creating a statefulset as per the example here: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/ and then just modify the name of the statefulset and create it again.

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As an admin user, deploy two StatefulSets with matching labels, validate that each StatefulSets displays their respective pods only|
|2|As a standard user, provision a downstream RKE1 node driver cluster, deploy two StatefulSets with matching labels, validate that each StatefulSets displays their respective pods only|
|3|As a standard user, provision a downstream RKE2 node driver cluster, deploy two StatefulSets with matching labels, validate that each StatefulSets displays their respective pods only|
|4|As a standard user, provision a downstream K3S node driver cluster, deploy two StatefulSets with matching labels, validate that each StatefulSets displays their respective pods only|

**Comment by markusewalker** [comment]
Reproduced this bug on `v2.7.0`. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7.0`
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As an admin user, deploy two StatefulSets with matching labels, validate that each StatefulSets displays their respective pods only|:x:

**VALIDATION STEPS**

**Scenario 1**
1. As an admin user,  navigated to the top-left menu > local cluster > Workload > StatefulSets.
2. Created two StatefulSets, namely `test1` and `test2`, using the following YAML:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test1
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
  volumes:
    - name: test1
      persistentVolumeClaim:
      claimName: test1
```
3. Reproduced the behavior as shown below:
![image](https://github.com/rancher/dashboard/assets/52591819/236ba034-3bb2-4513-826d-fe1878b0b4c0)
![image](https://github.com/rancher/dashboard/assets/52591819/82ecdbeb-de78-4d43-ad31-7b04d16bc843)

I will attempt to validate that this is resolved on the latest `v2.7-head`.

**Comment by markusewalker** [comment]
Validated that this is addressed on `v2.7-head` https://github.com/rancher/rancher/commit/95edd0203b7c5f0159d09e368e6897a06c48ba77. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `https://github.com/rancher/rancher/commit/95edd0203b7c5f0159d09e368e6897a06c48ba77`
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As an admin user, deploy two StatefulSets with matching labels, validate that each StatefulSets displays their respective pods only|:white_check_mark:|
|2|As a standard user, provision a downstream RKE1 node driver cluster, deploy two StatefulSets with matching labels, validate that each StatefulSets displays their respective pods only|:white_check_mark:|
|3|As a standard user, provision a downstream RKE2 node driver cluster, deploy two StatefulSets with matching labels, validate that each StatefulSets displays their respective pods only|:white_check_mark:|
|4|As a standard user, provision a downstream K3S node driver cluster, deploy two StatefulSets with matching labels, validate that each StatefulSets displays their respective pods only|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As an admin user,  navigated to the top-left menu > local cluster > Workload > StatefulSets.
2. Created two StatefulSets, namely `test1` and `test2`, using the following YAML:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test1
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
  volumes:
    - name: test1
      persistentVolumeClaim:
      claimName: test1
```
3. Viewed the StatefulSets and noted the following:
![image](https://github.com/rancher/dashboard/assets/52591819/5b7ff3b2-59f5-4cb7-b86c-bc7d2794c7df)
![image](https://github.com/rancher/dashboard/assets/52591819/a1fb1b78-2a23-40d4-904e-e534d2f36294)
_______
**Scenario 2**
1. As a standard user, provisioned a downstream RKE1 node driver `v1.26.4-rancher2-1` cluster.
2. Repeated scenario 1 steps 2-3, which yielded the same successful results.
_______
**Scenario 3**
1. As a standard user, provisioned a downstream RKE2 node driver `v1.26.4+rke2r1` cluster.
2. Repeated scenario 1 steps 2-3, which yielded the same successful results.
_______
**Scenario 4**
1. As a standard user, provisioned a downstream K3S node driver `v1.26.4+k3s1` cluster.
2. Repeated scenario 1 steps 2-3, which yielded the same successful results.
