### ISSUE TITLE
Restrict Storybook CI workflow to meaningful paths

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#7590]
# Description

Prevent Storybook to run at every single change to the application, as not every single file is meaningful for a new publication. 

## Context

Interested [paths](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) should be defined in the [current workflow](https://github.com/rancher/dashboard/blob/9a53bfa09408a42ca93f28714c8d345491a21858/.github/workflows/storybook.yaml), including only:
- `@rancher/components`
- `shell` components
- assets

E.g.

```yml
on:
  pull_request:
    paths:
      - 'pkg/rancher-components/**/*'
      - 'shell/components/**/*'
      - 'shell/assets/**/*'
    branches:
      - master
```
