### ISSUE TITLE
Reserved memory not updating correctly from the nodes view on Rancher UI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7598]
Internal reference: SURE-5598
Reported in 2.6.9

Issue description:
The user set up the configuration for reserving memory and CPU for the operational system and for Kubernetes resources. In the stress tests, everything worked as expected. Also, describing the nodes shows the difference that they configured between the capacity and the allocatable values. However, their question is related to how this information is displayed in the webUI. When they click on nodes >> Select the node, the memory information still shows the node's total value, but the CPU info was updated.

Business impact:
This can cause the information to be displayed that does not match the correct settings.

Troubleshooting steps:
No troubleshooting was done as it seems to be a webUI bug

Repro steps:

This was the configuration on rancher in order to reserve the compute resources:
```
 kubelet:
      extra_args:
        enforce-node-allocatable: 'pods,kube-reserved,system-reserved'
        eviction-hard: 'memory.available<100Mi,nodefs.available<10%'
        kube-reserved: 'cpu=500m,memory=1Gi'
        kube-reserved-cgroup: /kube-reserved.slice
        system-reserved: 'cpu=1000m,memory=2Gi'
        system-reserved-cgroup: /system.slice
```

Also, they created these groups that are not created by default in the server machines, both from kubernetes (mykube) and for the OS (system.slice):

```
/sys/fs/cgroup/hugetlb/mykube
/sys/fs/cgroup/cpu/mykube
/sys/fs/cgroup/cpuacct/mykube
/sys/fs/cgroup/cpuset/mykube
/sys/fs/cgroup/memory/mykube
/sys/fs/cgroup/systemd/mykube
/sys/fs/cgroup/pids/mykube
/sys/fs/cgroup/hugetlb/system.slice
/sys/fs/cgroup/cpu/system.slice
/sys/fs/cgroup/cpuacct/system.slice
/sys/fs/cgroup/cpuset/system.slice
/sys/fs/cgroup/memory/system.slice
/sys/fs/cgroup/systemd/system.slice
/sys/fs/cgroup/pids/system.slice
```

Workaround:
None

Actual behavior:
The reserved memory and total memory reserved were updated correctly, but from clicking on nodes under the webUI it shows the old information.

Expected behavior:
The webUI needs to update the correct value for the nodes

From the page that shows overall the usage of resources on the cluster, the reserved memory and total memory were updated correctly. 

![capacity-dashboard-webui.png](https://zube.io/files/rancher/79fcbd8e4b7bab775b88d59b52140975-capacity-dashboard-webui.png)

However, when clicking on a node, only the CPU was updated with the new allocatable memory. The total memory value should appear with the decrease in reserved memory, as it does with the CPU.

![node-information-webui.png](https://zube.io/files/rancher/4770004d925a869e6e1e5a15ab6d6ed3-node-information-webui.png)

Here's what `kubectl describe node` shows in this example:
```
Capacity:
    cpu: 8
    ephemeral-storage: 18422Mi hugepages-1Gi: 0 hugepages-2Mi: 0
    memory: 9766740Ki
    pods: 110
Allocatable:
    cpu: 6500m
    ephemeral-storage: 17385180337 hugepages-1Gi: 0 hugepages-2Mi: 0
    memory: 6518612Ki
    pods: 110
```

So they would expect that the memory value for the node would also be set to 6.5GB and not 9.31 as shown in the node in the GUI.

The ask: show the reserved memory for the node. It appears that the UI shows the node's total memory instead of what is allocatable when looking at the node view. It sounds like a missing feature or a bug in calculation with a confusing label.

**Comment by gaktive** [comment]
Key part of reproducing this is putting memory limitations on the nodes and then spinning them up.

**Comment by gaktive** [comment]
@cnotv may have reproduced this based on other work. Whoever tackles this, if you can set this up, let's document how to do this in our development docs.

This may spawn a new ticket to improve the UI here.

**Comment by cnotv** [comment]
I do not recall such operation in the past.

**Comment by cnotv** [comment]
@kwwii in the 2 designs (cluster and node) there's a difference on what we show. What they are asking, though, is not what we use for the cluster.

Should we:
- Create a new implementation based on what they asked
- Add a second meter as they asked
- Stick to what we have for the cluster
- Have all 3 of them?
- Use a toggler?

**Comment by kwwii** [comment]
We should add a reserved bar for the memory on the nodes detail page similar to the one on the cluster page.

**Comment by cnotv** [comment]
@gaktive do we know if it's possible to set the reserved memory from the UI?
If not, where am I supposed to paste this configuration?

```
 kubelet:
      extra_args:
        enforce-node-allocatable: 'pods,kube-reserved,system-reserved'
        eviction-hard: 'memory.available<100Mi,nodefs.available<10%'
        kube-reserved: 'cpu=500m,memory=1Gi'
        kube-reserved-cgroup: /kube-reserved.slice
        system-reserved: 'cpu=1000m,memory=2Gi'
        system-reserved-cgroup: /system.slice
```

**Comment by cnotv** [comment]
A similar feature request seems related to this one https://github.com/rancher/dashboard/issues/7322

**Comment by gaktive** [comment]
@nwmac do you remember if the UI has a reserved memory setting? I thought there was a field so it wasn't in YAML

@cnotv I know you spoke with @kwwii -- 7322 ties into an overall improvement to this view but this ticket is tied to the number being wrong. Am I up to date on everything here?

**Comment by cnotv** [comment]
It was just to pin-point.

**Comment by kwwii** [comment]
I think we need to show both the total memory usage as well as the reserved memory usage as they are different (but related) things.

**Comment by cnotv** [comment]
@nwmac I ask you since the other changes related to the reserved Memory for the cluster where from you.

We do not have any usage reference for the reserved memory, while for the cluster we compute it from the nodes. 
How is it possible that the values are different, then?

![Screenshot 2023-03-01 at 12 27 17](https://user-images.githubusercontent.com/5009481/222140172-348ad12d-fc95-472a-9bf4-a46bce55fb83.png)

![Screenshot 2023-03-01 at 13 32 45](https://user-images.githubusercontent.com/5009481/222140396-430e63fc-04c1-4044-8c74-78e284577d3f.png)

**Comment by cnotv** [comment]
@nwmac Also, to match the information of the description, this is what I have for the node from that cluster:

<img width="1385" alt="Screenshot 2023-03-02 at 09 33 58" src="https://user-images.githubusercontent.com/5009481/222374966-ae9de517-501b-4993-83a7-6f08568c4f71.png">
<img width="686" alt="Screenshot 2023-03-02 at 09 35 16" src="https://user-images.githubusercontent.com/5009481/222374980-64d433a1-2031-4ba0-90eb-1a4ea700120b.png">

I am not able to reproduce then the issue OR I am not able to reserve the memory as in the description.

**Comment by cnotv** [comment]
This issue is about Node `Used` memory and not `Reserved`.

**Comment by cnotv** [comment]
For the records, it's necessary to use these arguments for the cluster, but it is not clear how to do it in the UI:

```
 kubelet:
      extra_args:
        enforce-node-allocatable: 'pods,kube-reserved,system-reserved'
        eviction-hard: 'memory.available<100Mi,nodefs.available<10%'
        kube-reserved: 'cpu=500m,memory=1Gi'
        kube-reserved-cgroup: /kube-reserved.slice
        system-reserved: 'cpu=1000m,memory=2Gi'
        system-reserved-cgroup: /system.slice
```

We need to create a cluster from the CLI, identify how we display them in the UI and then eventually discuss an improvement or suggestion for this.

**Comment by cnotv** [comment]
@nwmac this is how code is displayed after editing the YAML with the given instructions:

YAML
<img width="851" alt="Screenshot 2023-05-23 at 10 19 42" src="https://github.com/rancher/dashboard/assets/5009481/209d7c6c-0dfc-4bdf-be2c-0fc0e03def8c">

UI
<img width="952" alt="Screenshot 2023-05-23 at 10 18 41" src="https://github.com/rancher/dashboard/assets/5009481/ec900878-015d-45c0-a5a5-6f8fb63f4a1d">

**Comment by cnotv** [comment]
Adding bits to the requirements.

From Mauricio Alves da Silva Perez (not GH user):
> The example configurations I used in the case.
```YAML
kubelet:  
  extra_args:  
    enforce-node-allocatable: "pods,kube-reserved,system-reserved"  
    eviction-hard: "memory.available<100Mi,nodefs.available<10%"  
    kube-reserved: "cpu=500m,memory=500Mi"  
    kube-reserved-cgroup: /runtime.slice  
    system-reserved: "cpu=500m,memory=1Gi"  
    system-reserved-cgroup: /system.slice
```

```TOML
# File runtime.slice  
# This file is being managed by Puppet  
# CHANGES WILL BE LOST  
#  
# The runtime.slice is required by Kubernetes compute resources reservation feature.  
#  
[Unit]  
Description=Kube Reserved Slice  
Documentation=https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/
Before=slices.target  
```

```TOML
# File rancher-cgroups.service  
# This file is being managed by Puppet  
# CHANGES WILL BE LOST  
#  
# This service creates the directory structure in /sys/fs/cgroup  
# required by Kubernetes compute resources reservation feature.  
#  
[Unit]  
Description=Cgroups required by Kubernetes compute resources reservation feature  
Documentation=https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/
Requires=docker.service

[Service]  
Type=oneshot  
ExecStart=/usr/local/sbin/rancher-cgroups  
Slice=/runtime.slice

[Install]  
WantedBy=multi-user.target
```

Bash
```ssh
# File script rancher-cgroups  
#!/usr/bin/env bash  
#  
# This file is being managed by Puppet  
# CHANGES WILL BE LOST  
#  
# This script creates the directory structure in /sys/fs/cgroup  
# required by Kubernetes compute resources reservation feature.  
#  
for CGROUP in runtime.slice system.slice  
do  
  for SUBSYSTEM in hugetlb cpu cpuacct cpuset memory systemd pids  
  do  
    if [ ! -d /sys/fs/cgroup/${SUBSYSTEM}/${CGROUP} ]  
    then  
      mkdir -p /sys/fs/cgroup/${SUBSYSTEM}/${CGROUP}  
    fi  
  done  
done
```
