### ISSUE TITLE
Create configmap/secret  from yaml has "immutable:boolean" field which results in error when used

### ISSUE THREAD

**Issue by soumyalj** [rancher/dashboard#760]
Version: v2.4-head(4269f6124), master-head(b89c3a572)

Steps:
1. Create a config map/secret from yaml. The yaml is displayed as below with an "immutable: boolean" field.
![Screen Shot 2020-06-11 at 12 27 58 PM](https://user-images.githubusercontent.com/18536626/84431565-57a9ef00-abe0-11ea-88ed-21b2b7682155.png)

![Screen Shot 2020-06-11 at 4 04 43 PM](https://user-images.githubusercontent.com/18536626/84447614-50dda500-abfd-11ea-8e0a-43d5bdab9493.png)

Is this field required ? It is not present when we create configmap/secret using form and observe the yaml file generated 

If we use the immutable field and create a configmap/secret, the below error is observed:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: newconfigmap
  namespace: default
  annotations:
    s1: s2
  labels:
    l1: l2
data:
  k3: v3
immutable: boolean

```

```
{ "type": "error", "links": {}, "code": "BadRequest", "message": "ConfigMap in version \"v1\"  
 cannot be handled as a ConfigMap: v1.ConfigMap.Immutable: ReadBool: expect t or f, but found  
  \", error found in rancher/dashboard#10 byte of ...|mutable\":\"boolean\",\"|..., bigger context ...|\"apiVersion\":\"v1\",\"data\": 
  {\"k3\":\"v3\"},\"immutable\":\"boolean\",\"kind\":\"ConfigMap\",\"metadata\":{\"annotatio|...", "status": 400 }
``` 

Could u please provide more info if this is a necessary field ?

**Comment by mantis-toboggan-md** [comment]
Per kubernetes docs: 

> This is an alpha field enabled by ImmutableEphemeralVolumes feature gate.

I think this falls under the category of assuming a user knows entirely what they're doing when they create/edit via yamls in the UI (e.g. we don't explicitly tell users that the data field needs to be base64 encoded, but it does). @deniseschannon what do you think?

**Comment by vincent99** [comment]
Well Boolean means it needs to be `true` or `false` (or something equivalent in yaml), so putting in literally `immutable: boolean` is correctly an error.

There's no reliable way to tell if a particular alpha feature is on or off to know if the field should be shown or not.  It's in the openapi schema so it's shown.

**Comment by deniseschannon** [comment]
This is an invalid bug based on user error.

**Comment by soumyalj** [comment]
Valdiated with master-head build(691feb01a)
Create a configmap using yaml file with immutable field as "true" or "false". Configmap gets created without any errors. 
Example:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test1
  namespace: default
  annotations:
    a1: a2
  labels:
    l1: l2
data:
  d1: d2
immutable: true

```
