### ISSUE TITLE
OPA - Not adding ApiGroups field makes the constraint to not work properly

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#764]
**What kind of request is this:**
Bug/Enhancement
Previously fixed in rancher/dashboard#387
UI Behavior changed in rancher/dashboard#392

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster, navigate to dashboard
2. Navigate to OPA Gatekeeper
3. Click Enable
4. Add a New `k8srequiredlabels` constrain as Form

Edit Parameters as YAML:

```yaml
labels:
- allowedRegex: ^$|^[a-zA-Z0-9]+
  key: gatekeep
message: All pods must have a `gatekeep` label
```

Add Kind `Pod`
Do not add an ApiGroup leave it there. Just add the Kind to match:

![Screen Shot 2020-06-11 at 4 30 14 PM](https://user-images.githubusercontent.com/27659/84448945-e2024b00-ac00-11ea-863a-a80427ab5d58.png)

**Result:**

Yaml generated for this will be:

```yaml
match:
    kinds:
    - kinds:
      - Pod
```

Expected:  If we try to create a workload without the gatekeep app gatekeeper should prevent it and raise an error. Also show violations for the existing workloads.

Actual: pods gets created without the mandatory label.

If we click in Add ApiGroup and leave it blank:

![Screen Shot 2020-06-11 at 4 37 57 PM](https://user-images.githubusercontent.com/27659/84449327-ed09ab00-ac01-11ea-9d05-4ed0490ed326.png)

YAML is now:

```yaml
match:
  kinds:
  - apiGroups:
    - ""
    kinds:
    - Pod
```

**This makes the constraint work.**

**Environment information**
- Rancher version: 
  - `master-head (06/11/2020)` b89c3a572
- Installation option (single install/HA): Single
- Cluster type: RKE (DO)

**Comment by izaac** [comment]
This was previously fixed #387

**Comment by izaac** [comment]
The behavior was recently changed as per request in this issue:

https://github.com/rancher/dashboard/issues/392#issuecomment-631074796

**Comment by izaac** [comment]
This affects all types of contraints in the Dashboard, repos and labels.

Other non-default Rancher types also include `ApiGroups`

https://github.com/open-policy-agent/gatekeeper/tree/master/library/general

**Comment by codyrancher** [comment]
With that information I'm planning to just add the empty apiGroups if it's not present when saving.

**Comment by izaac** [comment]
When not adding a n APIGroups field in the UI this is the generated `kinds` object in the YAML:

```yaml
    kinds:
    - apiGroups:
      - '*'
      kinds:
      - Pod
```

If we add one APIGroups field in the UI and left empty we get the following YAML:

```yaml
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Pod
```

Which is expected as we're leaving the field empty and therefore the `""`.

Validated in Rancher `v2.4-head` commit 7f0e24ec9
Pending validation in master due to #775
