### ISSUE TITLE
Network policy showing multiple sources improperly as separate items in an array

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7660]
Internal reference: SURE-5159
Reported in 2.6.7

Issue description:
Adding multiple sources in a single rule through rancher UI results in two separate items in the same array. 

Troubleshooting steps:

After adding the network policy, check it by "Edit YAML". We can see a hyphen (with a red dash icon) added to both `namespaceSelector` and `podSelector`, which means those are two items of the array. In this case, if either of the conditions are true, it will allow the ingress traffic.

```
  ingress:
  - from:
    - namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          - kube-system
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    - podSelector:
        matchExpressions:
        - key: k8s-app
          operator: In
          values:
          - kube-dns
        matchLabels:
          k8s-app: kube-dns
```

Repro steps:

- Go to Rancher >> Explorer >> Service Discovery >> Network Policies >> Create
- Name the policy and check "configure ingress rules to restrict traffic"
- Create a rule by pressing green plus button
- Add the first source by clicking "Add allowed traffic source" and select "Namespace Selector" from the dropdown
- Enter "kubernetes.io/metadata.name: kube-system" as Key/Value and "in list" as operator 
- Add the second source by clicking "Add allowed traffic source" again and select "Pod Selector" this time
- Enter "k8s-app: kube-dns" as Key/Value and "in list" as operator

Workaround:
Use "Edit As YAML" after adding required sources and make it part of the same item (remove `-`)

Actual behavior:
It adds namespaceSelector, podSelector as separate items of the array, resulted in matching either of it allows traffic

Expected behavior:
Should be a mechanism (AND button in the same rule) to add it as part of the same item so that it will allow traffic when both the conditions (matches both namespaceSelector and podSelector) are true. Preferably an OR button to add a second item for the existing source.
