### ISSUE TITLE
Broken error handling on create/edit workloads

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#8262]
**Setup**
- Rancher version: `v2.7-be585d369a71f4fbe88ef73865d159b0a2968f1c-head`
- UI version: `master e3a3e00b8`
- Browser type & version: Chrome

**Describe the bug**
When trying to create a StatefulSet via YAML with errors, hitting `create` causes a blocking error on the interface

**To Reproduce**
- Go to local cluster -> Create -> From YAML
- Use an invalid YAML, such as: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/ (has two resources `Service` and `StatefulSet`

**Result**
Blocking UI error

**Expected Result**
Should handle errors from server correctly

**Screenshots**
![Screenshot 2023-02-24 at 16 47 20](https://user-images.githubusercontent.com/97888974/221248503-d679d2e6-7ead-4f4b-bedb-7590613e76b0.png)

**Comment by Josh-Diamond** [comment]
Ticket #8262 - Test Results - ✅ 
---

Unable to reproduce on `v2.7-be585d369a71f4fbe88ef73865d159b0a2968f1c-head` and `v2.7.2-rc4`

---

Verified with Docker on a single-node instance w/ Rancher `v2.7-211409c9a689d8ee4d801ed1bce1d887b0fb4b00-head`:
1.  Fresh install of rancher `v2.7-head`
2. Navigate to `Cluster Explorer > Workloads > Create > StatefulSet` of local cluster
3. `Edit as YAML` and use the following configuration, then click `create`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi
```
4. Verified - proper error handling is seen and observed 

Screenshot:
<img width="1642" alt="Screenshot 2023-03-14 at 9 10 25 AM" src="https://user-images.githubusercontent.com/46494969/225069381-71addbca-3dbd-4cb7-b662-abe0813a5b2d.png">
