### ISSUE TITLE
Regression in App Values page, Group name not showing with just one question

### ISSUE THREAD

**Issue by leodotcloud** [rancher/dashboard#8358]
**Rancher Server Setup**
- Rancher version: v2.6.5

**Describe the bug**
An app with just one question in `questions.yml` doesn't show the group name in the UI.

**To Reproduce**
Create a custom app with just one question in `questions.yml`

```
questions:
# Image configuration
- variable: imagePullSecrets
  default: ""
  description: "Secret name to pull image from Registry"
  type: secret
  label: Image Pull Secrets
  group: "Container Images"
```

**Result**
The group name is not shown in the UI.

**Expected Result**

**Screenshots**

![image](https://user-images.githubusercontent.com/19392926/173431230-93f6bc8d-dabc-43b3-b411-b76ed623eb47.png)

**Additional context**
Adding a second question with a different group name resolves the problem.
