### ISSUE TITLE
[Backport v2.7] [RFE] Support overriding CRD values on main chart install (for Gatekeeper)

### ISSUE THREAD

**Issue by rancherbot** [rancher/dashboard#8382]
This is a backport issue for https://github.com/rancher/dashboard/issues/8238, automatically created via rancherbot by @mantis-toboggan-md

Original issue description:

Earlier there were not much values in crd charts but as a part of kubernetes 1.25 support now there are some more chart values are added. So support on UI is needed for these charts so that user can change the default values.

there were additional variables added for the following CRD charts:
1. rancher-gatekeeper-crd:
 https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-gatekeeper-crd/102.0.0%2Bup3.10.0/values.yaml#L15-L21
 added for the fix for issue: https://github.com/rancher/rancher/issues/40108

**Comment by gaktive** [comment]
Associated forward port still in Review so awaiting that result first before moving this to Done.

**Comment by nickwsuse** [comment]
`Verified on v2.7.2-rc8`

The values below are visible and by default are matching the code in both the CRD and main chart
```
enableRuntimeDefaultSeccompProfile: true

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
```
