### ISSUE TITLE
Resource Edit Wrapping Where No Wrap Exists

### ISSUE THREAD

**Issue by mattfarina** [rancher/dashboard#8427]
**Setup**
- Rancher version: 2.7.1
- Browser type & version: Brave Version 1.48.171  Chromium: 110.0.5481.177 (Official Build)  (64-bit)

**Describe the bug**
When editing a resource, such as a configmap, the content is wrapped in the UI.

**To Reproduce**

1. Navigate to the UI where you can create, edit, update, or delete ConfigMaps for a cluster.
2. Create a ConfigMap with the yaml below. Use direct YAML input.
3. Choose to "Edit as YAML" the new ConfigMap. Notice the comment wrapping and how the wrap has a line number.
4. Use kubectl to also view the ConfigMap.

The YAML used...
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-test2
  namespace: default
data:
  # A test comment that is more than 80 characters long in order to test yaml handling and wrapping.

  atest: >
    # Another test comment that is more than 80 characters long in order to test yaml handling and wrapping.

    test: two

```

**Result**

![Screenshot from 2023-03-13 16-13-07](https://user-images.githubusercontent.com/62991/224821628-cd8b6836-67ed-46ed-9239-69e9bfe2d3f8.png)

Notice how the comment in the section under `atest` wraps and the editor displays a new line via line number. It makes you think there is a line break.

But, fetching it with kubectl show something else...

![Screenshot from 2023-03-13 16-15-36](https://user-images.githubusercontent.com/62991/224822108-322d1645-59cb-4602-b483-a1f1032e0c86.png)

There is no line break.

**Expected Result**
Either the line should not break and you scroll right to see more, if needed, or the soft-wrap would not display a new line on the left. The soft-wrap should be handled as one the way other editors do.

**Screenshots**
See above

**Additional context**
N/A
