### ISSUE TITLE
[RFE] Add Ability to Add custom "Landing Pages" similar to Istio

### ISSUE THREAD

**Issue by brownz11** [rancher/dashboard#8704]
**Is your feature request related to a problem? Please describe.**
Sometimes, a centralized place to keep links and guidance is useful for directing downstream users to resources.

**Describe the solution you'd like**
It would be nice to be able to add "Landing Pages" to the sidebar similar to istio or NeuVector. Some links that come to mind would be for services deployed on the cluster that Ranchers in-built proxy works well for, and links to training and useful material for end users.

Ideally, this could be configured via K8s objects on the downstream cluster, with a mock up like
```
kind: SidebarPage
metadata:
  name: mycoolthing
spec:
  title: ACME Links
  banner: Banner Text
  buttons:
    - name: Cool Service
      icon: www.example.com/tree.svg
      description: A fun link to share with your friends
      link: /k8s/clusters/${ this.currentCluster.id }/api/v1/namespaces/xyz/services/https:abc:8443/proxy
    - name: Purple Thing
      icon: www.example.com/purple.svg
      description: A list of things in the office that are purple
      link: /k8s/clusters/${ this.currentCluster.id }/api/v1/namespaces/xyz/services/https:abc:8443/proxy
```

**Describe alternatives you've considered**
Creating a fork of the Rancher Dashboard

**Additional context**
A mocked UI example
![image](https://user-images.githubusercontent.com/74672092/233204609-f7af681f-a22a-4878-94fe-395bdebe0ea7.png)
