### ISSUE TITLE
Pod config's node scheduling tab doesn't always show pre-defined affinity

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#8719]
To Reproduce:
1. Create a deployment with the following affinity configuration:
```
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: cattle.io/cluster-agent
                operator: In
                values:
                  - 'true'
          weight: 1
```
2. Navigate to the pod list view and select 'edit config' for the associated pod
3. Within the pod config, select pod>node scheduling
4. `Run pods on specific node(s)` is selected and the above affinity rule is hidden

Looking at the pod's yaml, `nodeName` is set - according to the [docs](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodename) this overrules affinity so it makes sense for the UI to show this option; however, it is misleading to hide the affinity that is configured for the pod. We should have some visual indication that there are scheduling rules set, but overruled by `nodeName`.
