### ISSUE TITLE
Failed to provision GKE cluster as the clusterIpv4CidrBlock and clusterSecondaryRangeName fields conflict

### ISSUE THREAD

**Issue by niusmallnan** [rancher/dashboard#8749]
**Setup**
- Rancher version: v2.7.2
- Browser type & version: Chrome on Mac

**Describe the bug**

The API request payload is illegal, causing Google API to refuse to execute the request.
![image](https://user-images.githubusercontent.com/998984/234755425-980c7a60-a389-478b-a9a0-baee2ca525a3.png)

**To Reproduce**

To provision the GKE cluster like this:
<img width="987" alt="截屏2023-04-27 上午11 52 47" src="https://user-images.githubusercontent.com/998984/234755208-ac986d8c-f3f5-456f-b998-dffc46cb3753.png">

The payload details:
```
...
      "ipAllocationPolicy": {
        "clusterIpv4CidrBlock": "10.160.0.0/21",  <-- conflict here
        "clusterSecondaryRangeName": "pod-range", <-- conflict here
        "createSubnetwork": false,
        "nodeIpv4CidrBlock": null,
        "servicesIpv4CidrBlock": "10.160.8.0/21",
        "servicesSecondaryRangeName": "svc-range",
        "subnetworkName": null,
        "useIpAliases": true,
        "clusterIpv4Cidr": ""
      },
...
```

**Result**
GKE provisioning failed.

**Expected Result**

GKE provisioning can succeed

**Screenshots**

**Additional context**

The Google API declares that these two fields cannot be used at the same time.
> Specify cluster_secondary_range_name or cluster_ipv4_cidr_block but not both.

https://googleapis.dev/dotnet/Google.Apis.CloudComposer.v1beta1/latest/api/Google.Apis.CloudComposer.v1beta1.Data.IPAllocationPolicy.html#Google_Apis_CloudComposer_v1beta1_Data_IPAllocationPolicy_ClusterIpv4CidrBlock

workaround: https://ranchermanager.docs.rancher.com/pages-for-subheaders/about-the-api#capturing-rancher-api-calls

**Comment by gaktive** [comment]
Internal reference: SURE-7026

**Comment by gaktive** [comment]
Solution here: allow a title and radio buttons before selecting which dropdown from the first two options since only one can be picked.

**Comment by nwmac** [comment]
Useful doc: https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#Cluster.IPAllocationPolicy

**Comment by IsaSih** [comment]
Tested this in v2.9-3ae1c6ac8d3524f8ded4544f1db75fc9e07911a5-head and the UI is still allowing the user to create GKE clusters setting different values for both clusterIpv4CidrBlock and clusterSecondaryRangeName. When the cluster is provisioned, the UI just displays an error message, but there are no available logs or details about the error. Shouldn't the UI be locking one of the fields if the other one already has an input? 

![Image](https://github.com/rancher/dashboard/assets/70187881/9846db8c-dda1-416c-91d7-e8ec3fb15a28)

**Comment by cpinjani** [comment]
Build details:
Rancher - v2.9-3c4ccdc5bc9fde3510089153b5ad58fdbe604880-head
Dashboard - master 206ad94

Hitting the initial reported issue.

![image](https://github.com/user-attachments/assets/064b4780-113b-4877-abd7-84605b161102)

**Comment by cpinjani** [comment]
Is this issue still planned to addressed in v2.9.0 ?

**Comment by gaktive** [comment]
@cpinjani it's not a blocker but I'll check with @nwmac on what to do here. For now, we should release note this and target this for 2.10.0 and back port to 2.9.x if we can't unblock QA quickly here.

**Comment by nwmac** [comment]
The fix was made to the old GKE UI which has been ported to Vue - looks like it is an issue there @mantis-toboggan-md - for now, we'll need to go with the what @gaktive says in his comment above.

**Comment by gaktive** [comment]
I'll reopen this for 2.10.0 and list it as a backport candidate for 2.9.x. For @rancher/docs since this has happened in earlier versions, I don't know if we have a known issue for this in place already.

**Comment by sunilarjun** [comment]
> I'll reopen this for 2.10.0 and list it as a backport candidate for 2.9.x. For @rancher/docs since this has happened in earlier versions, I don't know if we have a known issue for this in place already.

@gaktive Can't find anything in recent release notes but I will add this to the v2.9.0 RN in the long standing known issues section if that works?

**Comment by rancher-max** [comment]
#### Validated using rancher v2.10.0-alpha11

The request no longer sends both fields together, and instead sends an empty string, which works fine. See both cases for clusterIpv4 and servicesIpv4:
```yaml
    "ipAllocationPolicy": {
      "clusterIpv4CidrBlock": "10.124.0.0/14",
      "clusterSecondaryRangeName": "gke-isa-gke-pods-9e28b4c8",
      "createSubnetwork": false,
      "nodeIpv4CidrBlock": null,
      "servicesIpv4CidrBlock": null,
      "servicesSecondaryRangeName": null,
      "subnetworkName": null,
      "useIpAliases": true,
      "clusterIpv4Cidr": ""
    },
```

```yaml
    "ipAllocationPolicy": {
      "clusterIpv4CidrBlock": "",
      "clusterSecondaryRangeName": "",
      "createSubnetwork": false,
      "nodeIpv4CidrBlock": null,
      "servicesIpv4CidrBlock": "",
      "servicesSecondaryRangeName": "gke-test3-pods-12ece79b",
      "subnetworkName": null,
      "useIpAliases": true,
      "clusterIpv4Cidr": ""
    },
```
