### ISSUE TITLE
Creating a `NetworkAttachmentDefinition` resource type references invalid labels/config

### ISSUE THREAD

**Issue by David-VTUK** [rancher/dashboard#8824]
**Setup**
- Rancher version: v2.7.3
- Rancher UI Extensions: None
- Browser type & version: Firefox 112.0.2

**Describe the bug**
When creating a cluster on a Infrastructure provider such as vSphere, and enabling multus the cluster explorer will display references to: `%harvester.network.tabs.basics% ` and `%harvester.network.tabs.layer3Network%`

**To Reproduce**
* Create an RKE2 cluster on a IaaS provider
* Select Multus with an accompanying default CNI as the CNI from the dropdown list
* Navigate into this cluster via `cluster explorer`
* Open `NetworkAttachmentDefinitions` from the resource search
* Create an new object of this type

**Result**

![image](https://github.com/rancher/dashboard/assets/5892615/0600b9b1-8502-46c0-9bca-4ab7e33a0f19)
![image](https://github.com/rancher/dashboard/assets/5892615/0f5f5852-839f-40ce-a1b5-d02574a8274c)

The empty yaml also references the harvester bridge network:

```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    network.harvesterhci.io/type: L2VlanNetwork
#    key: string
  namespace: default
spec:
  config: >-
    {"cniVersion":"0.3.1","type":"bridge","bridge":"harvester-br0","promiscMode":true,"vlan":"","ipam":{}}
__clone: true
```

**Expected Result**
* Correct label values (Generic)
* Generic `NetworkAttachmentDefinition` `spec.config` for new object type.

**Additional context**
* No harvester clusters are added to this Rancher instance
