### ISSUE TITLE
Simplify creation of clusters with reserved resources

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#8958]
# Describe

As outcome of the issue https://github.com/rancher/dashboard/issues/7598, it is quite complex to use our UI to create a cluster with reserved resources.

As in the example:
```
 kubelet:
      extra_args:
        enforce-node-allocatable: 'pods,kube-reserved,system-reserved'
        eviction-hard: 'memory.available<100Mi,nodefs.available<10%'
        kube-reserved: 'cpu=500m,memory=1Gi'
        kube-reserved-cgroup: /kube-reserved.slice
        system-reserved: 'cpu=1000m,memory=2Gi'
        system-reserved-cgroup: /system.slice
```

Current interface, at the moment unclear validity of the format entered as well:

<img width="964" alt="Screenshot 2023-05-23 at 10 10 08" src="https://github.com/rancher/dashboard/assets/5009481/99e398cb-0f82-4fa4-929a-c44d5bd697f1">
