### ISSUE TITLE
Apps - namespaces "xxx-xxx" not found. When we first try to install an App from Dashboard

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#904]
Rancher version `master-head (07/27/2020)` _8c2e2583c_

- At this moment This is only working in local HA k8s cluster due to rancher/dashboard#903  
- Enable the `dev-charts` repo

```yaml
apiVersion: catalog.cattle.io/v1
kind: Repo
metadata:
  name: dev-charts
  namespace: default
spec:
  url: https://dev-charts.rancher.io
```

Go to Charts and select one of the apps, keep all defaults and click Finish to deploy de App.
I tried gatekeeper and rancher-logging

Results:

**namespaces "xxx-xxx" not found**

![Screen Shot 2020-07-27 at 9 26 30 AM](https://user-images.githubusercontent.com/27659/88566942-a0c8cd80-cfeb-11ea-8793-b46b85b610f2.png)

Workaround:

Try deploying the app again, this time it will succeed.
