### ISSUE TITLE
UI says "Matches no existing clusters" when there is a null value for cluster selector in cluster groups

### ISSUE THREAD

**Issue by JeffParkes** [rancher/dashboard#9256]
**Setup**
- Rancher version: 2.7.2
- Rancher UI Extensions: none
- Browser type & version: 
Found in Chrome Version 114.0.5735.134 but also duplicated in Firefox and Edge.

**Describe the bug**

In the UI when there is a null value for cluster selector in cluster groups. The UI says "Matches no existing clusters" but when you add a space in the value field it changes to "Matches all 1 existing clusters" (this is a lab environment with only 1 downstream cluster…atm).

**To Reproduce**

1. create a cluster group with null in the values section
```
apiVersion: fleet.cattle.io/v1alpha1
kind: ClusterGroup
metadata:
  name: runway-shared-lab-eastus
  namespace: fleet-default
  annotations:
    field.cattle.io/description: Lab fleet cluster group for east clusters
spec:
  selector:
    matchExpressions:
    - key: fleet_cluster_group_override
      operator: In
      values:
      - ""
    - key: dx_k8s_cluster_detailed_type
      operator: In
      values:
      - "lab-eastus"
```
2. In the UI go into Continuous Delivery > Cluster Groups > Select cluster group > Edit Config
3. UI will say "Matches all 0 existing clusters" 
4. click into the "value" field and add a space
5. UI will now say "Matches all 1 existing clusters"

**Result**
Result is in step 3-5 above

**Expected Result**

UI should be able to match the cluster to cluster group with a null value in cluster selectors section.
