### ISSUE TITLE
AKS: Subnet CIDR details not being displayed correctly

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#9526]
**Setup**
Rancher version: v2.7-0b2f7fa0f878c3402ddf416a5b622327949b9348-head
Browser type & version: Chrome latest

**Describe the bug**
Subnet CIDR details not being displayed as 'undefined'

**To Reproduce**
- Create downstream AKS cluster and select Network policy & Network plugin as Azure, under Networking
- Fill necessary fields and create clsuter 
- Wait for cluster to become Active
- Edit cluster and check Networking details

**Screenshots**
While cluster creation:
![image](https://github.com/rancher/dashboard/assets/73099870/6e3d51b1-a0e2-41b6-b1ef-a4ec45998bde)

Edit Cluster after creation:
![image](https://github.com/rancher/dashboard/assets/73099870/66e0ae87-b1ca-494c-8070-572d20f08b50)

**Comment by richard-cox** [comment]
Adding MS

**Comment by cpinjani** [comment]
Blocked on https://github.com/rancher/dashboard/issues/10431

**Comment by cpinjani** [comment]
Validation results on build: `v2.9-c1d92781561c0d4d5a18b32b2f312655dfe67e9c-head`
Virtual Network (Subnet CIDR) displaying - _None_
![image](https://github.com/rancher/dashboard/assets/73099870/d8f4686e-ed9d-433b-b921-15a4fd89a628)

**Spec:**
```
aksConfig:
    authBaseUrl: null
    authorizedIpRanges: null
    azureCredentialSecret: cattle-global-data:cc-dcgtt
    baseUrl: null
    clusterName: cpinjani-aks1
    dnsPrefix: cpinjani-aks1
    dnsServiceIp: 10.1.0.10
    dockerBridgeCidr: null
    httpApplicationRouting: null
    imported: false
    kubernetesVersion: 1.28.9
    linuxAdminUsername: azureuser
    loadBalancerSku: standard
    logAnalyticsWorkspaceGroup: null
    logAnalyticsWorkspaceName: null
    managedIdentity: null
    monitoring: null
    networkPlugin: azure
    networkPolicy: calico
    nodePools:
      - availabilityZones:
          - '1'
          - '2'
          - '3'
        count: 1
        maxPods: 110
        maxSurge: '1'
        mode: System
        name: agentpool
        orchestratorVersion: 1.28.9
        osDiskSizeGB: 128
        osDiskType: Managed
        osType: Linux
        vmSize: Standard_DS2_v2
        vnetSubnetID: >-
          /subscriptions/<REDACTED>/resourceGroups/<REDACTED>/providers/Microsoft.Network/virtualNetworks/<REDACTED>/subnets/default
    outboundType: loadBalancer
    podCidr: null
    privateCluster: false
    privateDnsZone: null
    resourceGroup: <REDACTED>
    resourceLocation: eastus
    serviceCidr: 10.1.0.0/16
    subnet: null
    tags:
      Account Type: group
    userAssignedIdentity: null
    virtualNetwork: null
    virtualNetworkResourceGroup: null
```
