### ISSUE TITLE
HPA displays duplicate metric data when multiple metrics are defined

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9621]
Internal reference: SURE-6796
Reported in 2.7.5

Issue description:
When using multiple metrics in an HPA, the dashboard displays both metrics, however the values for the metrics are duplicated from the first metrics (see below screenshot).

Repro steps:

Create a deployment and HPA with multiple scaling metrics
Example:

```
kubectl apply -f https://k8s.io/examples/application/php-apache.yaml
kubectl apply -f hpa-php-apache.yaml ** see below
```

Once the metric data has been retrieved, check the UI

Workaround:
Rely on data from API/kubectl reports as expected

Actual behavior:
Dashboard shows confusing output under Service Discovery -> HorizontalPodAutoscalers

Expected behavior: Similar output to kubectl

![image-2023-08-17-10-03-41-862.png](https://zube.io/files/rancher/27bbac5d8f46f921ca7471b4c9cc51be-image-2023-08-17-10-03-41-862.png)

hpa-php-apache.yaml:
```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  maxReplicas: 10
  metrics:
    - resource:
        name: memory
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
```
