### ISSUE TITLE
rancher-logging chart options install UI - The Cluster Name field should be Index Name 

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#973]
This is the chart options UI for Logging

![Screen Shot 2020-08-06 at 10 14 27 AM](https://user-images.githubusercontent.com/27659/89562263-8ef6df80-d7ce-11ea-9961-cb6b5e2f0eeb.png)

After installation the `ClusterOutput` spec gets configured like this:

```yaml
spec:
  elasticsearch:
    host: <host>
    index_name: fluentd
    port: 9200
    scheme: http
```

Cluster Name is actually `index_name` in the crd.
