### ISSUE TITLE
Projects without a `.spec.displayName` are not displayed in the UI

### ISSUE THREAD

**Issue by pjbgf** [rancher/dashboard#9770]
**Setup**
- Rancher version: `v2.8-head`
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

 Projects without a `.spec.displayName` can be created via kubectl, but once created, they are not shown in the UI.

**To Reproduce**
- Create a new `Project` via `kubectl` without setting `.spec.displayName` (using yaml below):
```yaml
apiVersion: management.cattle.io/v3
kind: Project
metadata:
  name: das-unsichtbar-projekt
  namespace: default
spec:
```

**Result**
- Project can be listed via `kubectl get project -A` but it is not visible through Rancher Manger UI.

**Expected Result**
- The UI to display the created project, in this case falling back to the actual project name (`.metadata.name`).

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/5452977/511e2a02-fb86-448c-9cf8-d8d2e5ccd980)

**Additional context**
