### ISSUE TITLE
Project Resource Quotas Fields Appear to Clear Once Focus has Moved

### ISSUE THREAD

**Issue by brudnak** [rancher/dashboard#9795]
# Setup

| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version                  | v2.8-e5ce94a4c8572a8af176188172a57805e1dc76a4-head                                 |
| Rancher commit link              | https://github.com/rancher/rancher/commit/e5ce94a4c8572a8af176188172a57805e1dc76a4 |
| Installation option              | Helm (high availability)                                                           |
| RKE binary version used          | v1.4.8                                                                             |
| If Helm Chart k8s cluster        | v2.16.8-rancher2                                                                   |
| Cert Details                     | external tls aws acm                                                               |
| Docker version                   | 20.10.7, build f0df350                                                             |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | Linode K3s                                                                         |
| Downstream K8s version           | v1.27.6+k3s1                                                                       |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | standard user                                                                      |
| Browser type                     | Brave                                                                              |
| Browser version                  | v1.58.131                                                                          |
| Dashboard                        | master d3e7e6474                                                                   |
| Rancher env setup via            | https://github.com/brudnak/aws-ha-infra                                            |

# Describe the bug

Creating a project via kubectl. Then attempting to edit via the UI and add resource quotas. Fields appear to auto clear before being able to save them. (They actually are present upon saving) but you can't see them.

# To Reproduce

1. As admin create a standard user
2. Login to Rancher as the standard user and create a downstream K3s Linode cluster
3. Create a kubeconfig for the standard user
   - replace `$SERVER_URL` with the server url and `$API_KEY` with the API Key

    ```yaml
    apiVersion: v1
    kind: Config
    clusters:
    - name: "rancher"
      cluster:
        server: "$SERVER_URL"
        # Uncomment the following line if your server is using self-signed certs
        # This option is not recommended for production
        # insecure-skip-tls-verify: true

    users:
    - name: "rancher"
      user:
        token: "$API_KEY"


    contexts:
    - name: "rancher"
      context:
        user: "rancher"
        cluster: "rancher"

    current-context: "rancher"
    ```

4. Use kubectl apply to create a project

    ```yaml
    apiVersion: management.cattle.io/v3
    kind: Project
    metadata:
      name: kube-test-project
      namespace: c-m-r6k85pt8
    spec:
      clusterName: c-m-r6k85pt8
      displayName: display-name-kube-test
    ```

5. After the project is created via kubectl apply
6. Login to the Rancher UI, check that the project is visible
7. Try to edit the created project by clicking the `ellipsis (three dots)` >>> then click `Edit Config`
8. Click >>> `Resource Qoutas` >>> `Add Resource` >>> `Config Maps` >>>
9. Try to set `Project Limit` to `200`
10. Try to set `Namesapce Fefault Limit` to `20`

# Result

These fields appear to be automatically cleared when focus has been removed from them.

# Expected Result

The these fields not to appear to be cleared once focus has been moved away from them.

# Screenshots/Video

https://github.com/rancher/dashboard/assets/40877149/8ecbffee-2a32-4a0a-b580-e852c1a06603

# Bug Frequency

| Frequency                                                                                          | Selected Option |
| -------------------------------------------------------------------------------------------------- | --------------- |
| Consistent (10/10) - A consistent bug can be replicated every time the test is executed.           | ❎               |
| Frequent (7/10)- A frequent bug can be replicated like 7 out of 10 times when a test is replicated |                 |
| Occasional (5/10) - Occasional bug is more hard to replicate than a frequent bug.                  |                 |
| Once thus far, twice thus far - Few bugs cannot be reproduced every time you run the test.         |                 |

**Comment by richard-cox** [comment]
We need to do a root cause analysis and write tests to avoid regression

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment

Reproduction not required.

## Validation Environment


| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version starting         | v2.8-fc12e7d779577d10ded1a8e249f51727848b878e-head                                 |
| Rancher version upgraded         | not applicable / `fresh install`                                                   |
| Rancher commit link              | https://github.com/rancher/rancher/commit/fc12e7d779577d10ded1a8e249f51727848b878e |
| Installation option              | Docker                                                                             |
| Cert Details                     | `--acme-domain`                                                                    |
| Docker version                   | 20.10.7, build f0df350                                                             |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | not applicable                                                                     |
| Downstream K8s version           | not applicable                                                                     |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | admin                                                                              |
| Browser type                     | Firefox Developer Edition                                                          |
| Browser version                  | 119.0b5 (64-bit)                                                                   |
| Dashboard                        | master 702c54e96                                                                   |
| Webhook version                  | rancher-webhook:v0.4.0-rc10                                                        |
| Rancher env setup via            | https://github.com/brudnak/linode-docker-cattle                                    |


<a name="top"></a>

### :muscle: Test Cases

| \#  | Priority | Description & Link | PASS/FAIL |
| --- | -------- | ------------------ | --------- |
| 1   | P0       | [Test 1](#test-1)  | ✅ PASS    |

<details>
    <summary>🚨 1 test case... CLICK TO EXPAND! (For table links to work) ⬅️</summary>

<br>

# 1 / Status: ✅ PASS 

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps for Validation**


1. Use kubectl apply to create a project

    ```yaml
    apiVersion: management.cattle.io/v3
    kind: Project
    metadata:
      name: kube-test-project
      namespace: local
    spec:
      clusterName: local
      displayName: display-name-kube-test
    ```

2. After the project is created via kubectl apply
3. Login to the Rancher UI, check that the project is visible
4. Try to edit the created project by clicking the `ellipsis (three dots)` >>> then click `Edit Config`
5. Click >>> `Resource Qoutas` >>> `Add Resource` >>> `Config Maps` >>>
6. Try to set `Project Limit` to `200`
7.  Try to set `Namesapce Fefault Limit` to `20`

**✅ Expected Outcome**

The these fields not to appear to be cleared once focus has been moved away from them.

**✅ Actual Outcome**

Was able to set these fields as expected. They did not clear when changing focus. Was able to save and use them as expected.


</details>

<hr>

</details>
