### ISSUE TITLE
Disable RKE1 completely through UI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9823]
Internal reference: SURE-6568

Request description:
As Rancher is a UI that various users are using to start clusters on top of the Harvester, they would would like to have an option/button to disable RKE1 features completely to avoid accidental deployment.

Actual behavior:
RKE1 features are always available

Expected behavior:
It should be possible to disable RKE1 features in the configuration 

There will be a new feature flag added

When this feature flag is NOT set, we should hide RKE1 features from the UI:

- The toggle switch in provisioning should be hidden - the user will only see RKE2
- Hide the 'RKE1 Configuration' section in Cluster Management

![image](https://github.com/rancher/dashboard/assets/1955897/ec8fb788-4f7f-4812-b145-26fe00276671)

We should write automated tests for this feature.

See linked backend issue - suggest feature flag is, name: `rke1-ui`, description: `Enable RKE1 provisioning in the Rancher UI` - default is true.

Ahead of backend adding the required feature flag, you can add it yourself for development by importing/applying the following yaml:

```
apiVersion: management.cattle.io/v3
kind: Feature
metadata:
  name: rke1-ui
spec:
  value: null
status:
  default: true
  description: Enable RKE1 provisioning in the Rancher UI
  dynamic: true
  lockedValue: null
```
