### ISSUE TITLE
Cannot see Nodes in Explorer if using Dummy Node

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9955]
Internal Reference: SURE-7126

**Adding a dummy node to a cluster breaks the node view in Cluster Explorer**

To Reproduce:

In the local cluster, import the following yaml:

```
apiVersion: v1
kind: Node
metadata:
  name: bigip1
annotations:
  flannel.alpha.coreos.com/public-ip: "10.10.168.2"
  flannel.alpha.coreos.com/backend-data: '{"VtepMAC":"00:0a:49:ce:c3:82"}'
  flannel.alpha.coreos.com/backend-type: "vxlan"
  flannel.alpha.coreos.com/kube-subnet-manager: "true"
spec:
  podCIDR: "10.42.255.0/24"
```

Go the nodes view - the page breaks with `Cannot read properties of undefined (reading 'cpu')`
