### ISSUE TITLE
Storage Class List's Provisioner column shows `undefined` for unknown providers

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9968]
**Setup**
- Rancher version: 2.8.0 pre release

**Describe the bug**
- Storage Class List's Provisioner column shows `undefined` for non csi providers
- Looks like this is a regression from 2.7.2 via https://github.com/rancher/dashboard/pull/7287

**To Reproduce**
- In either an epinio cluster, or one with the yaml below, navigate to the storage class list
- View the provider column

**Result**
- see screenshot
- the provisionerDisplay getter appends `persistentVolume.csi.drivers.suffix`, which does not exist

**Expected Result**
- For this use case, probably no suffix. I'm not sure if removing it would break the fallback for when it is a csi driver?

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/18697775/44490022-7cd1-4039-97ab-0f97ad63ecbe)

**Additional context**

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
  labels:
  name: local-path-yaml
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
